
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AgencyRating` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AgencyRating
 * 
 */
export type AgencyRatingModel = runtime.Types.Result.DefaultSelection<Prisma.$AgencyRatingPayload>

export type AggregateAgencyRating = {
  _count: AgencyRatingCountAggregateOutputType | null
  _avg: AgencyRatingAvgAggregateOutputType | null
  _sum: AgencyRatingSumAggregateOutputType | null
  _min: AgencyRatingMinAggregateOutputType | null
  _max: AgencyRatingMaxAggregateOutputType | null
}

export type AgencyRatingAvgAggregateOutputType = {
  reliability: number | null
  punctuality: number | null
  warmth: number | null
  dignity: number | null
  hygiene: number | null
  skillsMatch: number | null
}

export type AgencyRatingSumAggregateOutputType = {
  reliability: number | null
  punctuality: number | null
  warmth: number | null
  dignity: number | null
  hygiene: number | null
  skillsMatch: number | null
}

export type AgencyRatingMinAggregateOutputType = {
  id: string | null
  relationshipId: string | null
  agencyId: string | null
  caregiverId: string | null
  reliability: number | null
  punctuality: number | null
  warmth: number | null
  dignity: number | null
  hygiene: number | null
  skillsMatch: number | null
  wouldReengage: boolean | null
  publicComment: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgencyRatingMaxAggregateOutputType = {
  id: string | null
  relationshipId: string | null
  agencyId: string | null
  caregiverId: string | null
  reliability: number | null
  punctuality: number | null
  warmth: number | null
  dignity: number | null
  hygiene: number | null
  skillsMatch: number | null
  wouldReengage: boolean | null
  publicComment: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgencyRatingCountAggregateOutputType = {
  id: number
  relationshipId: number
  agencyId: number
  caregiverId: number
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: number
  publicComment: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AgencyRatingAvgAggregateInputType = {
  reliability?: true
  punctuality?: true
  warmth?: true
  dignity?: true
  hygiene?: true
  skillsMatch?: true
}

export type AgencyRatingSumAggregateInputType = {
  reliability?: true
  punctuality?: true
  warmth?: true
  dignity?: true
  hygiene?: true
  skillsMatch?: true
}

export type AgencyRatingMinAggregateInputType = {
  id?: true
  relationshipId?: true
  agencyId?: true
  caregiverId?: true
  reliability?: true
  punctuality?: true
  warmth?: true
  dignity?: true
  hygiene?: true
  skillsMatch?: true
  wouldReengage?: true
  publicComment?: true
  createdAt?: true
  updatedAt?: true
}

export type AgencyRatingMaxAggregateInputType = {
  id?: true
  relationshipId?: true
  agencyId?: true
  caregiverId?: true
  reliability?: true
  punctuality?: true
  warmth?: true
  dignity?: true
  hygiene?: true
  skillsMatch?: true
  wouldReengage?: true
  publicComment?: true
  createdAt?: true
  updatedAt?: true
}

export type AgencyRatingCountAggregateInputType = {
  id?: true
  relationshipId?: true
  agencyId?: true
  caregiverId?: true
  reliability?: true
  punctuality?: true
  warmth?: true
  dignity?: true
  hygiene?: true
  skillsMatch?: true
  wouldReengage?: true
  publicComment?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AgencyRatingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgencyRating to aggregate.
   */
  where?: Prisma.AgencyRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencyRatings to fetch.
   */
  orderBy?: Prisma.AgencyRatingOrderByWithRelationInput | Prisma.AgencyRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgencyRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencyRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencyRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AgencyRatings
  **/
  _count?: true | AgencyRatingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AgencyRatingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AgencyRatingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgencyRatingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgencyRatingMaxAggregateInputType
}

export type GetAgencyRatingAggregateType<T extends AgencyRatingAggregateArgs> = {
      [P in keyof T & keyof AggregateAgencyRating]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgencyRating[P]>
    : Prisma.GetScalarType<T[P], AggregateAgencyRating[P]>
}




export type AgencyRatingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgencyRatingWhereInput
  orderBy?: Prisma.AgencyRatingOrderByWithAggregationInput | Prisma.AgencyRatingOrderByWithAggregationInput[]
  by: Prisma.AgencyRatingScalarFieldEnum[] | Prisma.AgencyRatingScalarFieldEnum
  having?: Prisma.AgencyRatingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgencyRatingCountAggregateInputType | true
  _avg?: AgencyRatingAvgAggregateInputType
  _sum?: AgencyRatingSumAggregateInputType
  _min?: AgencyRatingMinAggregateInputType
  _max?: AgencyRatingMaxAggregateInputType
}

export type AgencyRatingGroupByOutputType = {
  id: string
  relationshipId: string
  agencyId: string
  caregiverId: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment: string | null
  createdAt: Date
  updatedAt: Date
  _count: AgencyRatingCountAggregateOutputType | null
  _avg: AgencyRatingAvgAggregateOutputType | null
  _sum: AgencyRatingSumAggregateOutputType | null
  _min: AgencyRatingMinAggregateOutputType | null
  _max: AgencyRatingMaxAggregateOutputType | null
}

export type GetAgencyRatingGroupByPayload<T extends AgencyRatingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgencyRatingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgencyRatingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgencyRatingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgencyRatingGroupByOutputType[P]>
      }
    >
  >



export type AgencyRatingWhereInput = {
  AND?: Prisma.AgencyRatingWhereInput | Prisma.AgencyRatingWhereInput[]
  OR?: Prisma.AgencyRatingWhereInput[]
  NOT?: Prisma.AgencyRatingWhereInput | Prisma.AgencyRatingWhereInput[]
  id?: Prisma.StringFilter<"AgencyRating"> | string
  relationshipId?: Prisma.StringFilter<"AgencyRating"> | string
  agencyId?: Prisma.StringFilter<"AgencyRating"> | string
  caregiverId?: Prisma.StringFilter<"AgencyRating"> | string
  reliability?: Prisma.IntFilter<"AgencyRating"> | number
  punctuality?: Prisma.IntFilter<"AgencyRating"> | number
  warmth?: Prisma.IntFilter<"AgencyRating"> | number
  dignity?: Prisma.IntFilter<"AgencyRating"> | number
  hygiene?: Prisma.IntFilter<"AgencyRating"> | number
  skillsMatch?: Prisma.IntFilter<"AgencyRating"> | number
  wouldReengage?: Prisma.BoolFilter<"AgencyRating"> | boolean
  publicComment?: Prisma.StringNullableFilter<"AgencyRating"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AgencyRating"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AgencyRating"> | Date | string
  agency?: Prisma.XOR<Prisma.AgencyScalarRelationFilter, Prisma.AgencyWhereInput>
  caregiver?: Prisma.XOR<Prisma.CaregiverScalarRelationFilter, Prisma.CaregiverWhereInput>
  relationship?: Prisma.XOR<Prisma.AgencyCaregiverRelationshipScalarRelationFilter, Prisma.AgencyCaregiverRelationshipWhereInput>
}

export type AgencyRatingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  relationshipId?: Prisma.SortOrder
  agencyId?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  reliability?: Prisma.SortOrder
  punctuality?: Prisma.SortOrder
  warmth?: Prisma.SortOrder
  dignity?: Prisma.SortOrder
  hygiene?: Prisma.SortOrder
  skillsMatch?: Prisma.SortOrder
  wouldReengage?: Prisma.SortOrder
  publicComment?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  agency?: Prisma.AgencyOrderByWithRelationInput
  caregiver?: Prisma.CaregiverOrderByWithRelationInput
  relationship?: Prisma.AgencyCaregiverRelationshipOrderByWithRelationInput
}

export type AgencyRatingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  relationshipId?: string
  AND?: Prisma.AgencyRatingWhereInput | Prisma.AgencyRatingWhereInput[]
  OR?: Prisma.AgencyRatingWhereInput[]
  NOT?: Prisma.AgencyRatingWhereInput | Prisma.AgencyRatingWhereInput[]
  agencyId?: Prisma.StringFilter<"AgencyRating"> | string
  caregiverId?: Prisma.StringFilter<"AgencyRating"> | string
  reliability?: Prisma.IntFilter<"AgencyRating"> | number
  punctuality?: Prisma.IntFilter<"AgencyRating"> | number
  warmth?: Prisma.IntFilter<"AgencyRating"> | number
  dignity?: Prisma.IntFilter<"AgencyRating"> | number
  hygiene?: Prisma.IntFilter<"AgencyRating"> | number
  skillsMatch?: Prisma.IntFilter<"AgencyRating"> | number
  wouldReengage?: Prisma.BoolFilter<"AgencyRating"> | boolean
  publicComment?: Prisma.StringNullableFilter<"AgencyRating"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AgencyRating"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AgencyRating"> | Date | string
  agency?: Prisma.XOR<Prisma.AgencyScalarRelationFilter, Prisma.AgencyWhereInput>
  caregiver?: Prisma.XOR<Prisma.CaregiverScalarRelationFilter, Prisma.CaregiverWhereInput>
  relationship?: Prisma.XOR<Prisma.AgencyCaregiverRelationshipScalarRelationFilter, Prisma.AgencyCaregiverRelationshipWhereInput>
}, "id" | "relationshipId">

export type AgencyRatingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  relationshipId?: Prisma.SortOrder
  agencyId?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  reliability?: Prisma.SortOrder
  punctuality?: Prisma.SortOrder
  warmth?: Prisma.SortOrder
  dignity?: Prisma.SortOrder
  hygiene?: Prisma.SortOrder
  skillsMatch?: Prisma.SortOrder
  wouldReengage?: Prisma.SortOrder
  publicComment?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AgencyRatingCountOrderByAggregateInput
  _avg?: Prisma.AgencyRatingAvgOrderByAggregateInput
  _max?: Prisma.AgencyRatingMaxOrderByAggregateInput
  _min?: Prisma.AgencyRatingMinOrderByAggregateInput
  _sum?: Prisma.AgencyRatingSumOrderByAggregateInput
}

export type AgencyRatingScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgencyRatingScalarWhereWithAggregatesInput | Prisma.AgencyRatingScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgencyRatingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgencyRatingScalarWhereWithAggregatesInput | Prisma.AgencyRatingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AgencyRating"> | string
  relationshipId?: Prisma.StringWithAggregatesFilter<"AgencyRating"> | string
  agencyId?: Prisma.StringWithAggregatesFilter<"AgencyRating"> | string
  caregiverId?: Prisma.StringWithAggregatesFilter<"AgencyRating"> | string
  reliability?: Prisma.IntWithAggregatesFilter<"AgencyRating"> | number
  punctuality?: Prisma.IntWithAggregatesFilter<"AgencyRating"> | number
  warmth?: Prisma.IntWithAggregatesFilter<"AgencyRating"> | number
  dignity?: Prisma.IntWithAggregatesFilter<"AgencyRating"> | number
  hygiene?: Prisma.IntWithAggregatesFilter<"AgencyRating"> | number
  skillsMatch?: Prisma.IntWithAggregatesFilter<"AgencyRating"> | number
  wouldReengage?: Prisma.BoolWithAggregatesFilter<"AgencyRating"> | boolean
  publicComment?: Prisma.StringNullableWithAggregatesFilter<"AgencyRating"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AgencyRating"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AgencyRating"> | Date | string
}

export type AgencyRatingCreateInput = {
  id?: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  agency: Prisma.AgencyCreateNestedOneWithoutRatingsInput
  caregiver: Prisma.CaregiverCreateNestedOneWithoutAgencyRatingsInput
  relationship: Prisma.AgencyCaregiverRelationshipCreateNestedOneWithoutRatingInput
}

export type AgencyRatingUncheckedCreateInput = {
  id?: string
  relationshipId: string
  agencyId: string
  caregiverId: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyRatingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agency?: Prisma.AgencyUpdateOneRequiredWithoutRatingsNestedInput
  caregiver?: Prisma.CaregiverUpdateOneRequiredWithoutAgencyRatingsNestedInput
  relationship?: Prisma.AgencyCaregiverRelationshipUpdateOneRequiredWithoutRatingNestedInput
}

export type AgencyRatingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relationshipId?: Prisma.StringFieldUpdateOperationsInput | string
  agencyId?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyRatingCreateManyInput = {
  id?: string
  relationshipId: string
  agencyId: string
  caregiverId: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyRatingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyRatingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relationshipId?: Prisma.StringFieldUpdateOperationsInput | string
  agencyId?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyRatingListRelationFilter = {
  every?: Prisma.AgencyRatingWhereInput
  some?: Prisma.AgencyRatingWhereInput
  none?: Prisma.AgencyRatingWhereInput
}

export type AgencyRatingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AgencyRatingNullableScalarRelationFilter = {
  is?: Prisma.AgencyRatingWhereInput | null
  isNot?: Prisma.AgencyRatingWhereInput | null
}

export type AgencyRatingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  relationshipId?: Prisma.SortOrder
  agencyId?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  reliability?: Prisma.SortOrder
  punctuality?: Prisma.SortOrder
  warmth?: Prisma.SortOrder
  dignity?: Prisma.SortOrder
  hygiene?: Prisma.SortOrder
  skillsMatch?: Prisma.SortOrder
  wouldReengage?: Prisma.SortOrder
  publicComment?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgencyRatingAvgOrderByAggregateInput = {
  reliability?: Prisma.SortOrder
  punctuality?: Prisma.SortOrder
  warmth?: Prisma.SortOrder
  dignity?: Prisma.SortOrder
  hygiene?: Prisma.SortOrder
  skillsMatch?: Prisma.SortOrder
}

export type AgencyRatingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  relationshipId?: Prisma.SortOrder
  agencyId?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  reliability?: Prisma.SortOrder
  punctuality?: Prisma.SortOrder
  warmth?: Prisma.SortOrder
  dignity?: Prisma.SortOrder
  hygiene?: Prisma.SortOrder
  skillsMatch?: Prisma.SortOrder
  wouldReengage?: Prisma.SortOrder
  publicComment?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgencyRatingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  relationshipId?: Prisma.SortOrder
  agencyId?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  reliability?: Prisma.SortOrder
  punctuality?: Prisma.SortOrder
  warmth?: Prisma.SortOrder
  dignity?: Prisma.SortOrder
  hygiene?: Prisma.SortOrder
  skillsMatch?: Prisma.SortOrder
  wouldReengage?: Prisma.SortOrder
  publicComment?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgencyRatingSumOrderByAggregateInput = {
  reliability?: Prisma.SortOrder
  punctuality?: Prisma.SortOrder
  warmth?: Prisma.SortOrder
  dignity?: Prisma.SortOrder
  hygiene?: Prisma.SortOrder
  skillsMatch?: Prisma.SortOrder
}

export type AgencyRatingCreateNestedManyWithoutCaregiverInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutCaregiverInput, Prisma.AgencyRatingUncheckedCreateWithoutCaregiverInput> | Prisma.AgencyRatingCreateWithoutCaregiverInput[] | Prisma.AgencyRatingUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutCaregiverInput | Prisma.AgencyRatingCreateOrConnectWithoutCaregiverInput[]
  createMany?: Prisma.AgencyRatingCreateManyCaregiverInputEnvelope
  connect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
}

export type AgencyRatingUncheckedCreateNestedManyWithoutCaregiverInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutCaregiverInput, Prisma.AgencyRatingUncheckedCreateWithoutCaregiverInput> | Prisma.AgencyRatingCreateWithoutCaregiverInput[] | Prisma.AgencyRatingUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutCaregiverInput | Prisma.AgencyRatingCreateOrConnectWithoutCaregiverInput[]
  createMany?: Prisma.AgencyRatingCreateManyCaregiverInputEnvelope
  connect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
}

export type AgencyRatingUpdateManyWithoutCaregiverNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutCaregiverInput, Prisma.AgencyRatingUncheckedCreateWithoutCaregiverInput> | Prisma.AgencyRatingCreateWithoutCaregiverInput[] | Prisma.AgencyRatingUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutCaregiverInput | Prisma.AgencyRatingCreateOrConnectWithoutCaregiverInput[]
  upsert?: Prisma.AgencyRatingUpsertWithWhereUniqueWithoutCaregiverInput | Prisma.AgencyRatingUpsertWithWhereUniqueWithoutCaregiverInput[]
  createMany?: Prisma.AgencyRatingCreateManyCaregiverInputEnvelope
  set?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  disconnect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  delete?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  connect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  update?: Prisma.AgencyRatingUpdateWithWhereUniqueWithoutCaregiverInput | Prisma.AgencyRatingUpdateWithWhereUniqueWithoutCaregiverInput[]
  updateMany?: Prisma.AgencyRatingUpdateManyWithWhereWithoutCaregiverInput | Prisma.AgencyRatingUpdateManyWithWhereWithoutCaregiverInput[]
  deleteMany?: Prisma.AgencyRatingScalarWhereInput | Prisma.AgencyRatingScalarWhereInput[]
}

export type AgencyRatingUncheckedUpdateManyWithoutCaregiverNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutCaregiverInput, Prisma.AgencyRatingUncheckedCreateWithoutCaregiverInput> | Prisma.AgencyRatingCreateWithoutCaregiverInput[] | Prisma.AgencyRatingUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutCaregiverInput | Prisma.AgencyRatingCreateOrConnectWithoutCaregiverInput[]
  upsert?: Prisma.AgencyRatingUpsertWithWhereUniqueWithoutCaregiverInput | Prisma.AgencyRatingUpsertWithWhereUniqueWithoutCaregiverInput[]
  createMany?: Prisma.AgencyRatingCreateManyCaregiverInputEnvelope
  set?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  disconnect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  delete?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  connect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  update?: Prisma.AgencyRatingUpdateWithWhereUniqueWithoutCaregiverInput | Prisma.AgencyRatingUpdateWithWhereUniqueWithoutCaregiverInput[]
  updateMany?: Prisma.AgencyRatingUpdateManyWithWhereWithoutCaregiverInput | Prisma.AgencyRatingUpdateManyWithWhereWithoutCaregiverInput[]
  deleteMany?: Prisma.AgencyRatingScalarWhereInput | Prisma.AgencyRatingScalarWhereInput[]
}

export type AgencyRatingCreateNestedManyWithoutAgencyInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutAgencyInput, Prisma.AgencyRatingUncheckedCreateWithoutAgencyInput> | Prisma.AgencyRatingCreateWithoutAgencyInput[] | Prisma.AgencyRatingUncheckedCreateWithoutAgencyInput[]
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutAgencyInput | Prisma.AgencyRatingCreateOrConnectWithoutAgencyInput[]
  createMany?: Prisma.AgencyRatingCreateManyAgencyInputEnvelope
  connect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
}

export type AgencyRatingUncheckedCreateNestedManyWithoutAgencyInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutAgencyInput, Prisma.AgencyRatingUncheckedCreateWithoutAgencyInput> | Prisma.AgencyRatingCreateWithoutAgencyInput[] | Prisma.AgencyRatingUncheckedCreateWithoutAgencyInput[]
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutAgencyInput | Prisma.AgencyRatingCreateOrConnectWithoutAgencyInput[]
  createMany?: Prisma.AgencyRatingCreateManyAgencyInputEnvelope
  connect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
}

export type AgencyRatingUpdateManyWithoutAgencyNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutAgencyInput, Prisma.AgencyRatingUncheckedCreateWithoutAgencyInput> | Prisma.AgencyRatingCreateWithoutAgencyInput[] | Prisma.AgencyRatingUncheckedCreateWithoutAgencyInput[]
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutAgencyInput | Prisma.AgencyRatingCreateOrConnectWithoutAgencyInput[]
  upsert?: Prisma.AgencyRatingUpsertWithWhereUniqueWithoutAgencyInput | Prisma.AgencyRatingUpsertWithWhereUniqueWithoutAgencyInput[]
  createMany?: Prisma.AgencyRatingCreateManyAgencyInputEnvelope
  set?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  disconnect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  delete?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  connect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  update?: Prisma.AgencyRatingUpdateWithWhereUniqueWithoutAgencyInput | Prisma.AgencyRatingUpdateWithWhereUniqueWithoutAgencyInput[]
  updateMany?: Prisma.AgencyRatingUpdateManyWithWhereWithoutAgencyInput | Prisma.AgencyRatingUpdateManyWithWhereWithoutAgencyInput[]
  deleteMany?: Prisma.AgencyRatingScalarWhereInput | Prisma.AgencyRatingScalarWhereInput[]
}

export type AgencyRatingUncheckedUpdateManyWithoutAgencyNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutAgencyInput, Prisma.AgencyRatingUncheckedCreateWithoutAgencyInput> | Prisma.AgencyRatingCreateWithoutAgencyInput[] | Prisma.AgencyRatingUncheckedCreateWithoutAgencyInput[]
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutAgencyInput | Prisma.AgencyRatingCreateOrConnectWithoutAgencyInput[]
  upsert?: Prisma.AgencyRatingUpsertWithWhereUniqueWithoutAgencyInput | Prisma.AgencyRatingUpsertWithWhereUniqueWithoutAgencyInput[]
  createMany?: Prisma.AgencyRatingCreateManyAgencyInputEnvelope
  set?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  disconnect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  delete?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  connect?: Prisma.AgencyRatingWhereUniqueInput | Prisma.AgencyRatingWhereUniqueInput[]
  update?: Prisma.AgencyRatingUpdateWithWhereUniqueWithoutAgencyInput | Prisma.AgencyRatingUpdateWithWhereUniqueWithoutAgencyInput[]
  updateMany?: Prisma.AgencyRatingUpdateManyWithWhereWithoutAgencyInput | Prisma.AgencyRatingUpdateManyWithWhereWithoutAgencyInput[]
  deleteMany?: Prisma.AgencyRatingScalarWhereInput | Prisma.AgencyRatingScalarWhereInput[]
}

export type AgencyRatingCreateNestedOneWithoutRelationshipInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutRelationshipInput, Prisma.AgencyRatingUncheckedCreateWithoutRelationshipInput>
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutRelationshipInput
  connect?: Prisma.AgencyRatingWhereUniqueInput
}

export type AgencyRatingUncheckedCreateNestedOneWithoutRelationshipInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutRelationshipInput, Prisma.AgencyRatingUncheckedCreateWithoutRelationshipInput>
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutRelationshipInput
  connect?: Prisma.AgencyRatingWhereUniqueInput
}

export type AgencyRatingUpdateOneWithoutRelationshipNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutRelationshipInput, Prisma.AgencyRatingUncheckedCreateWithoutRelationshipInput>
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutRelationshipInput
  upsert?: Prisma.AgencyRatingUpsertWithoutRelationshipInput
  disconnect?: Prisma.AgencyRatingWhereInput | boolean
  delete?: Prisma.AgencyRatingWhereInput | boolean
  connect?: Prisma.AgencyRatingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencyRatingUpdateToOneWithWhereWithoutRelationshipInput, Prisma.AgencyRatingUpdateWithoutRelationshipInput>, Prisma.AgencyRatingUncheckedUpdateWithoutRelationshipInput>
}

export type AgencyRatingUncheckedUpdateOneWithoutRelationshipNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyRatingCreateWithoutRelationshipInput, Prisma.AgencyRatingUncheckedCreateWithoutRelationshipInput>
  connectOrCreate?: Prisma.AgencyRatingCreateOrConnectWithoutRelationshipInput
  upsert?: Prisma.AgencyRatingUpsertWithoutRelationshipInput
  disconnect?: Prisma.AgencyRatingWhereInput | boolean
  delete?: Prisma.AgencyRatingWhereInput | boolean
  connect?: Prisma.AgencyRatingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencyRatingUpdateToOneWithWhereWithoutRelationshipInput, Prisma.AgencyRatingUpdateWithoutRelationshipInput>, Prisma.AgencyRatingUncheckedUpdateWithoutRelationshipInput>
}

export type AgencyRatingCreateWithoutCaregiverInput = {
  id?: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  agency: Prisma.AgencyCreateNestedOneWithoutRatingsInput
  relationship: Prisma.AgencyCaregiverRelationshipCreateNestedOneWithoutRatingInput
}

export type AgencyRatingUncheckedCreateWithoutCaregiverInput = {
  id?: string
  relationshipId: string
  agencyId: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyRatingCreateOrConnectWithoutCaregiverInput = {
  where: Prisma.AgencyRatingWhereUniqueInput
  create: Prisma.XOR<Prisma.AgencyRatingCreateWithoutCaregiverInput, Prisma.AgencyRatingUncheckedCreateWithoutCaregiverInput>
}

export type AgencyRatingCreateManyCaregiverInputEnvelope = {
  data: Prisma.AgencyRatingCreateManyCaregiverInput | Prisma.AgencyRatingCreateManyCaregiverInput[]
  skipDuplicates?: boolean
}

export type AgencyRatingUpsertWithWhereUniqueWithoutCaregiverInput = {
  where: Prisma.AgencyRatingWhereUniqueInput
  update: Prisma.XOR<Prisma.AgencyRatingUpdateWithoutCaregiverInput, Prisma.AgencyRatingUncheckedUpdateWithoutCaregiverInput>
  create: Prisma.XOR<Prisma.AgencyRatingCreateWithoutCaregiverInput, Prisma.AgencyRatingUncheckedCreateWithoutCaregiverInput>
}

export type AgencyRatingUpdateWithWhereUniqueWithoutCaregiverInput = {
  where: Prisma.AgencyRatingWhereUniqueInput
  data: Prisma.XOR<Prisma.AgencyRatingUpdateWithoutCaregiverInput, Prisma.AgencyRatingUncheckedUpdateWithoutCaregiverInput>
}

export type AgencyRatingUpdateManyWithWhereWithoutCaregiverInput = {
  where: Prisma.AgencyRatingScalarWhereInput
  data: Prisma.XOR<Prisma.AgencyRatingUpdateManyMutationInput, Prisma.AgencyRatingUncheckedUpdateManyWithoutCaregiverInput>
}

export type AgencyRatingScalarWhereInput = {
  AND?: Prisma.AgencyRatingScalarWhereInput | Prisma.AgencyRatingScalarWhereInput[]
  OR?: Prisma.AgencyRatingScalarWhereInput[]
  NOT?: Prisma.AgencyRatingScalarWhereInput | Prisma.AgencyRatingScalarWhereInput[]
  id?: Prisma.StringFilter<"AgencyRating"> | string
  relationshipId?: Prisma.StringFilter<"AgencyRating"> | string
  agencyId?: Prisma.StringFilter<"AgencyRating"> | string
  caregiverId?: Prisma.StringFilter<"AgencyRating"> | string
  reliability?: Prisma.IntFilter<"AgencyRating"> | number
  punctuality?: Prisma.IntFilter<"AgencyRating"> | number
  warmth?: Prisma.IntFilter<"AgencyRating"> | number
  dignity?: Prisma.IntFilter<"AgencyRating"> | number
  hygiene?: Prisma.IntFilter<"AgencyRating"> | number
  skillsMatch?: Prisma.IntFilter<"AgencyRating"> | number
  wouldReengage?: Prisma.BoolFilter<"AgencyRating"> | boolean
  publicComment?: Prisma.StringNullableFilter<"AgencyRating"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AgencyRating"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AgencyRating"> | Date | string
}

export type AgencyRatingCreateWithoutAgencyInput = {
  id?: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  caregiver: Prisma.CaregiverCreateNestedOneWithoutAgencyRatingsInput
  relationship: Prisma.AgencyCaregiverRelationshipCreateNestedOneWithoutRatingInput
}

export type AgencyRatingUncheckedCreateWithoutAgencyInput = {
  id?: string
  relationshipId: string
  caregiverId: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyRatingCreateOrConnectWithoutAgencyInput = {
  where: Prisma.AgencyRatingWhereUniqueInput
  create: Prisma.XOR<Prisma.AgencyRatingCreateWithoutAgencyInput, Prisma.AgencyRatingUncheckedCreateWithoutAgencyInput>
}

export type AgencyRatingCreateManyAgencyInputEnvelope = {
  data: Prisma.AgencyRatingCreateManyAgencyInput | Prisma.AgencyRatingCreateManyAgencyInput[]
  skipDuplicates?: boolean
}

export type AgencyRatingUpsertWithWhereUniqueWithoutAgencyInput = {
  where: Prisma.AgencyRatingWhereUniqueInput
  update: Prisma.XOR<Prisma.AgencyRatingUpdateWithoutAgencyInput, Prisma.AgencyRatingUncheckedUpdateWithoutAgencyInput>
  create: Prisma.XOR<Prisma.AgencyRatingCreateWithoutAgencyInput, Prisma.AgencyRatingUncheckedCreateWithoutAgencyInput>
}

export type AgencyRatingUpdateWithWhereUniqueWithoutAgencyInput = {
  where: Prisma.AgencyRatingWhereUniqueInput
  data: Prisma.XOR<Prisma.AgencyRatingUpdateWithoutAgencyInput, Prisma.AgencyRatingUncheckedUpdateWithoutAgencyInput>
}

export type AgencyRatingUpdateManyWithWhereWithoutAgencyInput = {
  where: Prisma.AgencyRatingScalarWhereInput
  data: Prisma.XOR<Prisma.AgencyRatingUpdateManyMutationInput, Prisma.AgencyRatingUncheckedUpdateManyWithoutAgencyInput>
}

export type AgencyRatingCreateWithoutRelationshipInput = {
  id?: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  agency: Prisma.AgencyCreateNestedOneWithoutRatingsInput
  caregiver: Prisma.CaregiverCreateNestedOneWithoutAgencyRatingsInput
}

export type AgencyRatingUncheckedCreateWithoutRelationshipInput = {
  id?: string
  agencyId: string
  caregiverId: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyRatingCreateOrConnectWithoutRelationshipInput = {
  where: Prisma.AgencyRatingWhereUniqueInput
  create: Prisma.XOR<Prisma.AgencyRatingCreateWithoutRelationshipInput, Prisma.AgencyRatingUncheckedCreateWithoutRelationshipInput>
}

export type AgencyRatingUpsertWithoutRelationshipInput = {
  update: Prisma.XOR<Prisma.AgencyRatingUpdateWithoutRelationshipInput, Prisma.AgencyRatingUncheckedUpdateWithoutRelationshipInput>
  create: Prisma.XOR<Prisma.AgencyRatingCreateWithoutRelationshipInput, Prisma.AgencyRatingUncheckedCreateWithoutRelationshipInput>
  where?: Prisma.AgencyRatingWhereInput
}

export type AgencyRatingUpdateToOneWithWhereWithoutRelationshipInput = {
  where?: Prisma.AgencyRatingWhereInput
  data: Prisma.XOR<Prisma.AgencyRatingUpdateWithoutRelationshipInput, Prisma.AgencyRatingUncheckedUpdateWithoutRelationshipInput>
}

export type AgencyRatingUpdateWithoutRelationshipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agency?: Prisma.AgencyUpdateOneRequiredWithoutRatingsNestedInput
  caregiver?: Prisma.CaregiverUpdateOneRequiredWithoutAgencyRatingsNestedInput
}

export type AgencyRatingUncheckedUpdateWithoutRelationshipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agencyId?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyRatingCreateManyCaregiverInput = {
  id?: string
  relationshipId: string
  agencyId: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyRatingUpdateWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agency?: Prisma.AgencyUpdateOneRequiredWithoutRatingsNestedInput
  relationship?: Prisma.AgencyCaregiverRelationshipUpdateOneRequiredWithoutRatingNestedInput
}

export type AgencyRatingUncheckedUpdateWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relationshipId?: Prisma.StringFieldUpdateOperationsInput | string
  agencyId?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyRatingUncheckedUpdateManyWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relationshipId?: Prisma.StringFieldUpdateOperationsInput | string
  agencyId?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyRatingCreateManyAgencyInput = {
  id?: string
  relationshipId: string
  caregiverId: string
  reliability: number
  punctuality: number
  warmth: number
  dignity: number
  hygiene: number
  skillsMatch: number
  wouldReengage: boolean
  publicComment?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyRatingUpdateWithoutAgencyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  caregiver?: Prisma.CaregiverUpdateOneRequiredWithoutAgencyRatingsNestedInput
  relationship?: Prisma.AgencyCaregiverRelationshipUpdateOneRequiredWithoutRatingNestedInput
}

export type AgencyRatingUncheckedUpdateWithoutAgencyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relationshipId?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyRatingUncheckedUpdateManyWithoutAgencyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relationshipId?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  reliability?: Prisma.IntFieldUpdateOperationsInput | number
  punctuality?: Prisma.IntFieldUpdateOperationsInput | number
  warmth?: Prisma.IntFieldUpdateOperationsInput | number
  dignity?: Prisma.IntFieldUpdateOperationsInput | number
  hygiene?: Prisma.IntFieldUpdateOperationsInput | number
  skillsMatch?: Prisma.IntFieldUpdateOperationsInput | number
  wouldReengage?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicComment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AgencyRatingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  relationshipId?: boolean
  agencyId?: boolean
  caregiverId?: boolean
  reliability?: boolean
  punctuality?: boolean
  warmth?: boolean
  dignity?: boolean
  hygiene?: boolean
  skillsMatch?: boolean
  wouldReengage?: boolean
  publicComment?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  agency?: boolean | Prisma.AgencyDefaultArgs<ExtArgs>
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agencyRating"]>

export type AgencyRatingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  relationshipId?: boolean
  agencyId?: boolean
  caregiverId?: boolean
  reliability?: boolean
  punctuality?: boolean
  warmth?: boolean
  dignity?: boolean
  hygiene?: boolean
  skillsMatch?: boolean
  wouldReengage?: boolean
  publicComment?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  agency?: boolean | Prisma.AgencyDefaultArgs<ExtArgs>
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agencyRating"]>

export type AgencyRatingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  relationshipId?: boolean
  agencyId?: boolean
  caregiverId?: boolean
  reliability?: boolean
  punctuality?: boolean
  warmth?: boolean
  dignity?: boolean
  hygiene?: boolean
  skillsMatch?: boolean
  wouldReengage?: boolean
  publicComment?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  agency?: boolean | Prisma.AgencyDefaultArgs<ExtArgs>
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agencyRating"]>

export type AgencyRatingSelectScalar = {
  id?: boolean
  relationshipId?: boolean
  agencyId?: boolean
  caregiverId?: boolean
  reliability?: boolean
  punctuality?: boolean
  warmth?: boolean
  dignity?: boolean
  hygiene?: boolean
  skillsMatch?: boolean
  wouldReengage?: boolean
  publicComment?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AgencyRatingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "relationshipId" | "agencyId" | "caregiverId" | "reliability" | "punctuality" | "warmth" | "dignity" | "hygiene" | "skillsMatch" | "wouldReengage" | "publicComment" | "createdAt" | "updatedAt", ExtArgs["result"]["agencyRating"]>
export type AgencyRatingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  agency?: boolean | Prisma.AgencyDefaultArgs<ExtArgs>
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}
export type AgencyRatingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  agency?: boolean | Prisma.AgencyDefaultArgs<ExtArgs>
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}
export type AgencyRatingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  agency?: boolean | Prisma.AgencyDefaultArgs<ExtArgs>
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}

export type $AgencyRatingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AgencyRating"
  objects: {
    agency: Prisma.$AgencyPayload<ExtArgs>
    caregiver: Prisma.$CaregiverPayload<ExtArgs>
    relationship: Prisma.$AgencyCaregiverRelationshipPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    relationshipId: string
    agencyId: string
    caregiverId: string
    reliability: number
    punctuality: number
    warmth: number
    dignity: number
    hygiene: number
    skillsMatch: number
    wouldReengage: boolean
    publicComment: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["agencyRating"]>
  composites: {}
}

export type AgencyRatingGetPayload<S extends boolean | null | undefined | AgencyRatingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload, S>

export type AgencyRatingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgencyRatingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgencyRatingCountAggregateInputType | true
  }

export interface AgencyRatingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AgencyRating'], meta: { name: 'AgencyRating' } }
  /**
   * Find zero or one AgencyRating that matches the filter.
   * @param {AgencyRatingFindUniqueArgs} args - Arguments to find a AgencyRating
   * @example
   * // Get one AgencyRating
   * const agencyRating = await prisma.agencyRating.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgencyRatingFindUniqueArgs>(args: Prisma.SelectSubset<T, AgencyRatingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgencyRatingClient<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AgencyRating that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgencyRatingFindUniqueOrThrowArgs} args - Arguments to find a AgencyRating
   * @example
   * // Get one AgencyRating
   * const agencyRating = await prisma.agencyRating.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgencyRatingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgencyRatingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgencyRatingClient<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgencyRating that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyRatingFindFirstArgs} args - Arguments to find a AgencyRating
   * @example
   * // Get one AgencyRating
   * const agencyRating = await prisma.agencyRating.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgencyRatingFindFirstArgs>(args?: Prisma.SelectSubset<T, AgencyRatingFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgencyRatingClient<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgencyRating that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyRatingFindFirstOrThrowArgs} args - Arguments to find a AgencyRating
   * @example
   * // Get one AgencyRating
   * const agencyRating = await prisma.agencyRating.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgencyRatingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgencyRatingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgencyRatingClient<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AgencyRatings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyRatingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AgencyRatings
   * const agencyRatings = await prisma.agencyRating.findMany()
   * 
   * // Get first 10 AgencyRatings
   * const agencyRatings = await prisma.agencyRating.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agencyRatingWithIdOnly = await prisma.agencyRating.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgencyRatingFindManyArgs>(args?: Prisma.SelectSubset<T, AgencyRatingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AgencyRating.
   * @param {AgencyRatingCreateArgs} args - Arguments to create a AgencyRating.
   * @example
   * // Create one AgencyRating
   * const AgencyRating = await prisma.agencyRating.create({
   *   data: {
   *     // ... data to create a AgencyRating
   *   }
   * })
   * 
   */
  create<T extends AgencyRatingCreateArgs>(args: Prisma.SelectSubset<T, AgencyRatingCreateArgs<ExtArgs>>): Prisma.Prisma__AgencyRatingClient<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AgencyRatings.
   * @param {AgencyRatingCreateManyArgs} args - Arguments to create many AgencyRatings.
   * @example
   * // Create many AgencyRatings
   * const agencyRating = await prisma.agencyRating.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgencyRatingCreateManyArgs>(args?: Prisma.SelectSubset<T, AgencyRatingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AgencyRatings and returns the data saved in the database.
   * @param {AgencyRatingCreateManyAndReturnArgs} args - Arguments to create many AgencyRatings.
   * @example
   * // Create many AgencyRatings
   * const agencyRating = await prisma.agencyRating.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AgencyRatings and only return the `id`
   * const agencyRatingWithIdOnly = await prisma.agencyRating.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgencyRatingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgencyRatingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AgencyRating.
   * @param {AgencyRatingDeleteArgs} args - Arguments to delete one AgencyRating.
   * @example
   * // Delete one AgencyRating
   * const AgencyRating = await prisma.agencyRating.delete({
   *   where: {
   *     // ... filter to delete one AgencyRating
   *   }
   * })
   * 
   */
  delete<T extends AgencyRatingDeleteArgs>(args: Prisma.SelectSubset<T, AgencyRatingDeleteArgs<ExtArgs>>): Prisma.Prisma__AgencyRatingClient<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AgencyRating.
   * @param {AgencyRatingUpdateArgs} args - Arguments to update one AgencyRating.
   * @example
   * // Update one AgencyRating
   * const agencyRating = await prisma.agencyRating.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgencyRatingUpdateArgs>(args: Prisma.SelectSubset<T, AgencyRatingUpdateArgs<ExtArgs>>): Prisma.Prisma__AgencyRatingClient<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AgencyRatings.
   * @param {AgencyRatingDeleteManyArgs} args - Arguments to filter AgencyRatings to delete.
   * @example
   * // Delete a few AgencyRatings
   * const { count } = await prisma.agencyRating.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgencyRatingDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgencyRatingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgencyRatings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyRatingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AgencyRatings
   * const agencyRating = await prisma.agencyRating.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgencyRatingUpdateManyArgs>(args: Prisma.SelectSubset<T, AgencyRatingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgencyRatings and returns the data updated in the database.
   * @param {AgencyRatingUpdateManyAndReturnArgs} args - Arguments to update many AgencyRatings.
   * @example
   * // Update many AgencyRatings
   * const agencyRating = await prisma.agencyRating.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AgencyRatings and only return the `id`
   * const agencyRatingWithIdOnly = await prisma.agencyRating.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgencyRatingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgencyRatingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AgencyRating.
   * @param {AgencyRatingUpsertArgs} args - Arguments to update or create a AgencyRating.
   * @example
   * // Update or create a AgencyRating
   * const agencyRating = await prisma.agencyRating.upsert({
   *   create: {
   *     // ... data to create a AgencyRating
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AgencyRating we want to update
   *   }
   * })
   */
  upsert<T extends AgencyRatingUpsertArgs>(args: Prisma.SelectSubset<T, AgencyRatingUpsertArgs<ExtArgs>>): Prisma.Prisma__AgencyRatingClient<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AgencyRatings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyRatingCountArgs} args - Arguments to filter AgencyRatings to count.
   * @example
   * // Count the number of AgencyRatings
   * const count = await prisma.agencyRating.count({
   *   where: {
   *     // ... the filter for the AgencyRatings we want to count
   *   }
   * })
  **/
  count<T extends AgencyRatingCountArgs>(
    args?: Prisma.Subset<T, AgencyRatingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgencyRatingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AgencyRating.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyRatingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgencyRatingAggregateArgs>(args: Prisma.Subset<T, AgencyRatingAggregateArgs>): Prisma.PrismaPromise<GetAgencyRatingAggregateType<T>>

  /**
   * Group by AgencyRating.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyRatingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgencyRatingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgencyRatingGroupByArgs['orderBy'] }
      : { orderBy?: AgencyRatingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgencyRatingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgencyRatingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AgencyRating model
 */
readonly fields: AgencyRatingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AgencyRating.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgencyRatingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  agency<T extends Prisma.AgencyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AgencyDefaultArgs<ExtArgs>>): Prisma.Prisma__AgencyClient<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  caregiver<T extends Prisma.CaregiverDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CaregiverDefaultArgs<ExtArgs>>): Prisma.Prisma__CaregiverClient<runtime.Types.Result.GetResult<Prisma.$CaregiverPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  relationship<T extends Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>>): Prisma.Prisma__AgencyCaregiverRelationshipClient<runtime.Types.Result.GetResult<Prisma.$AgencyCaregiverRelationshipPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AgencyRating model
 */
export interface AgencyRatingFieldRefs {
  readonly id: Prisma.FieldRef<"AgencyRating", 'String'>
  readonly relationshipId: Prisma.FieldRef<"AgencyRating", 'String'>
  readonly agencyId: Prisma.FieldRef<"AgencyRating", 'String'>
  readonly caregiverId: Prisma.FieldRef<"AgencyRating", 'String'>
  readonly reliability: Prisma.FieldRef<"AgencyRating", 'Int'>
  readonly punctuality: Prisma.FieldRef<"AgencyRating", 'Int'>
  readonly warmth: Prisma.FieldRef<"AgencyRating", 'Int'>
  readonly dignity: Prisma.FieldRef<"AgencyRating", 'Int'>
  readonly hygiene: Prisma.FieldRef<"AgencyRating", 'Int'>
  readonly skillsMatch: Prisma.FieldRef<"AgencyRating", 'Int'>
  readonly wouldReengage: Prisma.FieldRef<"AgencyRating", 'Boolean'>
  readonly publicComment: Prisma.FieldRef<"AgencyRating", 'String'>
  readonly createdAt: Prisma.FieldRef<"AgencyRating", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AgencyRating", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AgencyRating findUnique
 */
export type AgencyRatingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
  /**
   * Filter, which AgencyRating to fetch.
   */
  where: Prisma.AgencyRatingWhereUniqueInput
}

/**
 * AgencyRating findUniqueOrThrow
 */
export type AgencyRatingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
  /**
   * Filter, which AgencyRating to fetch.
   */
  where: Prisma.AgencyRatingWhereUniqueInput
}

/**
 * AgencyRating findFirst
 */
export type AgencyRatingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
  /**
   * Filter, which AgencyRating to fetch.
   */
  where?: Prisma.AgencyRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencyRatings to fetch.
   */
  orderBy?: Prisma.AgencyRatingOrderByWithRelationInput | Prisma.AgencyRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgencyRatings.
   */
  cursor?: Prisma.AgencyRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencyRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencyRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgencyRatings.
   */
  distinct?: Prisma.AgencyRatingScalarFieldEnum | Prisma.AgencyRatingScalarFieldEnum[]
}

/**
 * AgencyRating findFirstOrThrow
 */
export type AgencyRatingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
  /**
   * Filter, which AgencyRating to fetch.
   */
  where?: Prisma.AgencyRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencyRatings to fetch.
   */
  orderBy?: Prisma.AgencyRatingOrderByWithRelationInput | Prisma.AgencyRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgencyRatings.
   */
  cursor?: Prisma.AgencyRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencyRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencyRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgencyRatings.
   */
  distinct?: Prisma.AgencyRatingScalarFieldEnum | Prisma.AgencyRatingScalarFieldEnum[]
}

/**
 * AgencyRating findMany
 */
export type AgencyRatingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
  /**
   * Filter, which AgencyRatings to fetch.
   */
  where?: Prisma.AgencyRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencyRatings to fetch.
   */
  orderBy?: Prisma.AgencyRatingOrderByWithRelationInput | Prisma.AgencyRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AgencyRatings.
   */
  cursor?: Prisma.AgencyRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencyRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencyRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgencyRatings.
   */
  distinct?: Prisma.AgencyRatingScalarFieldEnum | Prisma.AgencyRatingScalarFieldEnum[]
}

/**
 * AgencyRating create
 */
export type AgencyRatingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
  /**
   * The data needed to create a AgencyRating.
   */
  data: Prisma.XOR<Prisma.AgencyRatingCreateInput, Prisma.AgencyRatingUncheckedCreateInput>
}

/**
 * AgencyRating createMany
 */
export type AgencyRatingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AgencyRatings.
   */
  data: Prisma.AgencyRatingCreateManyInput | Prisma.AgencyRatingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AgencyRating createManyAndReturn
 */
export type AgencyRatingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * The data used to create many AgencyRatings.
   */
  data: Prisma.AgencyRatingCreateManyInput | Prisma.AgencyRatingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AgencyRating update
 */
export type AgencyRatingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
  /**
   * The data needed to update a AgencyRating.
   */
  data: Prisma.XOR<Prisma.AgencyRatingUpdateInput, Prisma.AgencyRatingUncheckedUpdateInput>
  /**
   * Choose, which AgencyRating to update.
   */
  where: Prisma.AgencyRatingWhereUniqueInput
}

/**
 * AgencyRating updateMany
 */
export type AgencyRatingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AgencyRatings.
   */
  data: Prisma.XOR<Prisma.AgencyRatingUpdateManyMutationInput, Prisma.AgencyRatingUncheckedUpdateManyInput>
  /**
   * Filter which AgencyRatings to update
   */
  where?: Prisma.AgencyRatingWhereInput
  /**
   * Limit how many AgencyRatings to update.
   */
  limit?: number
}

/**
 * AgencyRating updateManyAndReturn
 */
export type AgencyRatingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * The data used to update AgencyRatings.
   */
  data: Prisma.XOR<Prisma.AgencyRatingUpdateManyMutationInput, Prisma.AgencyRatingUncheckedUpdateManyInput>
  /**
   * Filter which AgencyRatings to update
   */
  where?: Prisma.AgencyRatingWhereInput
  /**
   * Limit how many AgencyRatings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AgencyRating upsert
 */
export type AgencyRatingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
  /**
   * The filter to search for the AgencyRating to update in case it exists.
   */
  where: Prisma.AgencyRatingWhereUniqueInput
  /**
   * In case the AgencyRating found by the `where` argument doesn't exist, create a new AgencyRating with this data.
   */
  create: Prisma.XOR<Prisma.AgencyRatingCreateInput, Prisma.AgencyRatingUncheckedCreateInput>
  /**
   * In case the AgencyRating was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgencyRatingUpdateInput, Prisma.AgencyRatingUncheckedUpdateInput>
}

/**
 * AgencyRating delete
 */
export type AgencyRatingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
  /**
   * Filter which AgencyRating to delete.
   */
  where: Prisma.AgencyRatingWhereUniqueInput
}

/**
 * AgencyRating deleteMany
 */
export type AgencyRatingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgencyRatings to delete
   */
  where?: Prisma.AgencyRatingWhereInput
  /**
   * Limit how many AgencyRatings to delete.
   */
  limit?: number
}

/**
 * AgencyRating without action
 */
export type AgencyRatingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
}
