
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Agency` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Agency
 * 
 */
export type AgencyModel = runtime.Types.Result.DefaultSelection<Prisma.$AgencyPayload>

export type AggregateAgency = {
  _count: AgencyCountAggregateOutputType | null
  _min: AgencyMinAggregateOutputType | null
  _max: AgencyMaxAggregateOutputType | null
}

export type AgencyMinAggregateOutputType = {
  id: string | null
  userId: string | null
  name: string | null
  description: string | null
  phone: string | null
  website: string | null
  logoUrl: string | null
  address: string | null
  city: string | null
  state: string | null
  postalCode: string | null
  isVerified: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgencyMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  name: string | null
  description: string | null
  phone: string | null
  website: string | null
  logoUrl: string | null
  address: string | null
  city: string | null
  state: string | null
  postalCode: string | null
  isVerified: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgencyCountAggregateOutputType = {
  id: number
  userId: number
  name: number
  description: number
  phone: number
  website: number
  logoUrl: number
  address: number
  city: number
  state: number
  postalCode: number
  isVerified: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AgencyMinAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  description?: true
  phone?: true
  website?: true
  logoUrl?: true
  address?: true
  city?: true
  state?: true
  postalCode?: true
  isVerified?: true
  createdAt?: true
  updatedAt?: true
}

export type AgencyMaxAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  description?: true
  phone?: true
  website?: true
  logoUrl?: true
  address?: true
  city?: true
  state?: true
  postalCode?: true
  isVerified?: true
  createdAt?: true
  updatedAt?: true
}

export type AgencyCountAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  description?: true
  phone?: true
  website?: true
  logoUrl?: true
  address?: true
  city?: true
  state?: true
  postalCode?: true
  isVerified?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AgencyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Agency to aggregate.
   */
  where?: Prisma.AgencyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agencies to fetch.
   */
  orderBy?: Prisma.AgencyOrderByWithRelationInput | Prisma.AgencyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgencyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agencies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agencies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Agencies
  **/
  _count?: true | AgencyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgencyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgencyMaxAggregateInputType
}

export type GetAgencyAggregateType<T extends AgencyAggregateArgs> = {
      [P in keyof T & keyof AggregateAgency]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgency[P]>
    : Prisma.GetScalarType<T[P], AggregateAgency[P]>
}




export type AgencyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgencyWhereInput
  orderBy?: Prisma.AgencyOrderByWithAggregationInput | Prisma.AgencyOrderByWithAggregationInput[]
  by: Prisma.AgencyScalarFieldEnum[] | Prisma.AgencyScalarFieldEnum
  having?: Prisma.AgencyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgencyCountAggregateInputType | true
  _min?: AgencyMinAggregateInputType
  _max?: AgencyMaxAggregateInputType
}

export type AgencyGroupByOutputType = {
  id: string
  userId: string
  name: string
  description: string | null
  phone: string | null
  website: string | null
  logoUrl: string | null
  address: string | null
  city: string | null
  state: string | null
  postalCode: string | null
  isVerified: boolean
  createdAt: Date
  updatedAt: Date
  _count: AgencyCountAggregateOutputType | null
  _min: AgencyMinAggregateOutputType | null
  _max: AgencyMaxAggregateOutputType | null
}

export type GetAgencyGroupByPayload<T extends AgencyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgencyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgencyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgencyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgencyGroupByOutputType[P]>
      }
    >
  >



export type AgencyWhereInput = {
  AND?: Prisma.AgencyWhereInput | Prisma.AgencyWhereInput[]
  OR?: Prisma.AgencyWhereInput[]
  NOT?: Prisma.AgencyWhereInput | Prisma.AgencyWhereInput[]
  id?: Prisma.StringFilter<"Agency"> | string
  userId?: Prisma.StringFilter<"Agency"> | string
  name?: Prisma.StringFilter<"Agency"> | string
  description?: Prisma.StringNullableFilter<"Agency"> | string | null
  phone?: Prisma.StringNullableFilter<"Agency"> | string | null
  website?: Prisma.StringNullableFilter<"Agency"> | string | null
  logoUrl?: Prisma.StringNullableFilter<"Agency"> | string | null
  address?: Prisma.StringNullableFilter<"Agency"> | string | null
  city?: Prisma.StringNullableFilter<"Agency"> | string | null
  state?: Prisma.StringNullableFilter<"Agency"> | string | null
  postalCode?: Prisma.StringNullableFilter<"Agency"> | string | null
  isVerified?: Prisma.BoolFilter<"Agency"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Agency"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Agency"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  relationships?: Prisma.AgencyCaregiverRelationshipListRelationFilter
  ratings?: Prisma.AgencyRatingListRelationFilter
  savedSearches?: Prisma.AgencySavedSearchListRelationFilter
}

export type AgencyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  website?: Prisma.SortOrderInput | Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  city?: Prisma.SortOrderInput | Prisma.SortOrder
  state?: Prisma.SortOrderInput | Prisma.SortOrder
  postalCode?: Prisma.SortOrderInput | Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  relationships?: Prisma.AgencyCaregiverRelationshipOrderByRelationAggregateInput
  ratings?: Prisma.AgencyRatingOrderByRelationAggregateInput
  savedSearches?: Prisma.AgencySavedSearchOrderByRelationAggregateInput
}

export type AgencyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.AgencyWhereInput | Prisma.AgencyWhereInput[]
  OR?: Prisma.AgencyWhereInput[]
  NOT?: Prisma.AgencyWhereInput | Prisma.AgencyWhereInput[]
  name?: Prisma.StringFilter<"Agency"> | string
  description?: Prisma.StringNullableFilter<"Agency"> | string | null
  phone?: Prisma.StringNullableFilter<"Agency"> | string | null
  website?: Prisma.StringNullableFilter<"Agency"> | string | null
  logoUrl?: Prisma.StringNullableFilter<"Agency"> | string | null
  address?: Prisma.StringNullableFilter<"Agency"> | string | null
  city?: Prisma.StringNullableFilter<"Agency"> | string | null
  state?: Prisma.StringNullableFilter<"Agency"> | string | null
  postalCode?: Prisma.StringNullableFilter<"Agency"> | string | null
  isVerified?: Prisma.BoolFilter<"Agency"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Agency"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Agency"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  relationships?: Prisma.AgencyCaregiverRelationshipListRelationFilter
  ratings?: Prisma.AgencyRatingListRelationFilter
  savedSearches?: Prisma.AgencySavedSearchListRelationFilter
}, "id" | "userId">

export type AgencyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  website?: Prisma.SortOrderInput | Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  city?: Prisma.SortOrderInput | Prisma.SortOrder
  state?: Prisma.SortOrderInput | Prisma.SortOrder
  postalCode?: Prisma.SortOrderInput | Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AgencyCountOrderByAggregateInput
  _max?: Prisma.AgencyMaxOrderByAggregateInput
  _min?: Prisma.AgencyMinOrderByAggregateInput
}

export type AgencyScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgencyScalarWhereWithAggregatesInput | Prisma.AgencyScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgencyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgencyScalarWhereWithAggregatesInput | Prisma.AgencyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Agency"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Agency"> | string
  name?: Prisma.StringWithAggregatesFilter<"Agency"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Agency"> | string | null
  phone?: Prisma.StringNullableWithAggregatesFilter<"Agency"> | string | null
  website?: Prisma.StringNullableWithAggregatesFilter<"Agency"> | string | null
  logoUrl?: Prisma.StringNullableWithAggregatesFilter<"Agency"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"Agency"> | string | null
  city?: Prisma.StringNullableWithAggregatesFilter<"Agency"> | string | null
  state?: Prisma.StringNullableWithAggregatesFilter<"Agency"> | string | null
  postalCode?: Prisma.StringNullableWithAggregatesFilter<"Agency"> | string | null
  isVerified?: Prisma.BoolWithAggregatesFilter<"Agency"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Agency"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Agency"> | Date | string
}

export type AgencyCreateInput = {
  id?: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAgencyInput
  relationships?: Prisma.AgencyCaregiverRelationshipCreateNestedManyWithoutAgencyInput
  ratings?: Prisma.AgencyRatingCreateNestedManyWithoutAgencyInput
  savedSearches?: Prisma.AgencySavedSearchCreateNestedManyWithoutAgencyInput
}

export type AgencyUncheckedCreateInput = {
  id?: string
  userId: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  relationships?: Prisma.AgencyCaregiverRelationshipUncheckedCreateNestedManyWithoutAgencyInput
  ratings?: Prisma.AgencyRatingUncheckedCreateNestedManyWithoutAgencyInput
  savedSearches?: Prisma.AgencySavedSearchUncheckedCreateNestedManyWithoutAgencyInput
}

export type AgencyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAgencyNestedInput
  relationships?: Prisma.AgencyCaregiverRelationshipUpdateManyWithoutAgencyNestedInput
  ratings?: Prisma.AgencyRatingUpdateManyWithoutAgencyNestedInput
  savedSearches?: Prisma.AgencySavedSearchUpdateManyWithoutAgencyNestedInput
}

export type AgencyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  relationships?: Prisma.AgencyCaregiverRelationshipUncheckedUpdateManyWithoutAgencyNestedInput
  ratings?: Prisma.AgencyRatingUncheckedUpdateManyWithoutAgencyNestedInput
  savedSearches?: Prisma.AgencySavedSearchUncheckedUpdateManyWithoutAgencyNestedInput
}

export type AgencyCreateManyInput = {
  id?: string
  userId: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyNullableScalarRelationFilter = {
  is?: Prisma.AgencyWhereInput | null
  isNot?: Prisma.AgencyWhereInput | null
}

export type AgencyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  website?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  state?: Prisma.SortOrder
  postalCode?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgencyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  website?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  state?: Prisma.SortOrder
  postalCode?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgencyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  website?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  state?: Prisma.SortOrder
  postalCode?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgencyScalarRelationFilter = {
  is?: Prisma.AgencyWhereInput
  isNot?: Prisma.AgencyWhereInput
}

export type AgencyCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AgencyCreateWithoutUserInput, Prisma.AgencyUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencyCreateOrConnectWithoutUserInput
  connect?: Prisma.AgencyWhereUniqueInput
}

export type AgencyUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AgencyCreateWithoutUserInput, Prisma.AgencyUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencyCreateOrConnectWithoutUserInput
  connect?: Prisma.AgencyWhereUniqueInput
}

export type AgencyUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyCreateWithoutUserInput, Prisma.AgencyUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencyCreateOrConnectWithoutUserInput
  upsert?: Prisma.AgencyUpsertWithoutUserInput
  disconnect?: Prisma.AgencyWhereInput | boolean
  delete?: Prisma.AgencyWhereInput | boolean
  connect?: Prisma.AgencyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencyUpdateToOneWithWhereWithoutUserInput, Prisma.AgencyUpdateWithoutUserInput>, Prisma.AgencyUncheckedUpdateWithoutUserInput>
}

export type AgencyUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyCreateWithoutUserInput, Prisma.AgencyUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencyCreateOrConnectWithoutUserInput
  upsert?: Prisma.AgencyUpsertWithoutUserInput
  disconnect?: Prisma.AgencyWhereInput | boolean
  delete?: Prisma.AgencyWhereInput | boolean
  connect?: Prisma.AgencyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencyUpdateToOneWithWhereWithoutUserInput, Prisma.AgencyUpdateWithoutUserInput>, Prisma.AgencyUncheckedUpdateWithoutUserInput>
}

export type AgencyCreateNestedOneWithoutRelationshipsInput = {
  create?: Prisma.XOR<Prisma.AgencyCreateWithoutRelationshipsInput, Prisma.AgencyUncheckedCreateWithoutRelationshipsInput>
  connectOrCreate?: Prisma.AgencyCreateOrConnectWithoutRelationshipsInput
  connect?: Prisma.AgencyWhereUniqueInput
}

export type AgencyUpdateOneRequiredWithoutRelationshipsNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyCreateWithoutRelationshipsInput, Prisma.AgencyUncheckedCreateWithoutRelationshipsInput>
  connectOrCreate?: Prisma.AgencyCreateOrConnectWithoutRelationshipsInput
  upsert?: Prisma.AgencyUpsertWithoutRelationshipsInput
  connect?: Prisma.AgencyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencyUpdateToOneWithWhereWithoutRelationshipsInput, Prisma.AgencyUpdateWithoutRelationshipsInput>, Prisma.AgencyUncheckedUpdateWithoutRelationshipsInput>
}

export type AgencyCreateNestedOneWithoutRatingsInput = {
  create?: Prisma.XOR<Prisma.AgencyCreateWithoutRatingsInput, Prisma.AgencyUncheckedCreateWithoutRatingsInput>
  connectOrCreate?: Prisma.AgencyCreateOrConnectWithoutRatingsInput
  connect?: Prisma.AgencyWhereUniqueInput
}

export type AgencyUpdateOneRequiredWithoutRatingsNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyCreateWithoutRatingsInput, Prisma.AgencyUncheckedCreateWithoutRatingsInput>
  connectOrCreate?: Prisma.AgencyCreateOrConnectWithoutRatingsInput
  upsert?: Prisma.AgencyUpsertWithoutRatingsInput
  connect?: Prisma.AgencyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencyUpdateToOneWithWhereWithoutRatingsInput, Prisma.AgencyUpdateWithoutRatingsInput>, Prisma.AgencyUncheckedUpdateWithoutRatingsInput>
}

export type AgencyCreateNestedOneWithoutSavedSearchesInput = {
  create?: Prisma.XOR<Prisma.AgencyCreateWithoutSavedSearchesInput, Prisma.AgencyUncheckedCreateWithoutSavedSearchesInput>
  connectOrCreate?: Prisma.AgencyCreateOrConnectWithoutSavedSearchesInput
  connect?: Prisma.AgencyWhereUniqueInput
}

export type AgencyUpdateOneRequiredWithoutSavedSearchesNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyCreateWithoutSavedSearchesInput, Prisma.AgencyUncheckedCreateWithoutSavedSearchesInput>
  connectOrCreate?: Prisma.AgencyCreateOrConnectWithoutSavedSearchesInput
  upsert?: Prisma.AgencyUpsertWithoutSavedSearchesInput
  connect?: Prisma.AgencyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencyUpdateToOneWithWhereWithoutSavedSearchesInput, Prisma.AgencyUpdateWithoutSavedSearchesInput>, Prisma.AgencyUncheckedUpdateWithoutSavedSearchesInput>
}

export type AgencyCreateWithoutUserInput = {
  id?: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  relationships?: Prisma.AgencyCaregiverRelationshipCreateNestedManyWithoutAgencyInput
  ratings?: Prisma.AgencyRatingCreateNestedManyWithoutAgencyInput
  savedSearches?: Prisma.AgencySavedSearchCreateNestedManyWithoutAgencyInput
}

export type AgencyUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  relationships?: Prisma.AgencyCaregiverRelationshipUncheckedCreateNestedManyWithoutAgencyInput
  ratings?: Prisma.AgencyRatingUncheckedCreateNestedManyWithoutAgencyInput
  savedSearches?: Prisma.AgencySavedSearchUncheckedCreateNestedManyWithoutAgencyInput
}

export type AgencyCreateOrConnectWithoutUserInput = {
  where: Prisma.AgencyWhereUniqueInput
  create: Prisma.XOR<Prisma.AgencyCreateWithoutUserInput, Prisma.AgencyUncheckedCreateWithoutUserInput>
}

export type AgencyUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.AgencyUpdateWithoutUserInput, Prisma.AgencyUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AgencyCreateWithoutUserInput, Prisma.AgencyUncheckedCreateWithoutUserInput>
  where?: Prisma.AgencyWhereInput
}

export type AgencyUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.AgencyWhereInput
  data: Prisma.XOR<Prisma.AgencyUpdateWithoutUserInput, Prisma.AgencyUncheckedUpdateWithoutUserInput>
}

export type AgencyUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  relationships?: Prisma.AgencyCaregiverRelationshipUpdateManyWithoutAgencyNestedInput
  ratings?: Prisma.AgencyRatingUpdateManyWithoutAgencyNestedInput
  savedSearches?: Prisma.AgencySavedSearchUpdateManyWithoutAgencyNestedInput
}

export type AgencyUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  relationships?: Prisma.AgencyCaregiverRelationshipUncheckedUpdateManyWithoutAgencyNestedInput
  ratings?: Prisma.AgencyRatingUncheckedUpdateManyWithoutAgencyNestedInput
  savedSearches?: Prisma.AgencySavedSearchUncheckedUpdateManyWithoutAgencyNestedInput
}

export type AgencyCreateWithoutRelationshipsInput = {
  id?: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAgencyInput
  ratings?: Prisma.AgencyRatingCreateNestedManyWithoutAgencyInput
  savedSearches?: Prisma.AgencySavedSearchCreateNestedManyWithoutAgencyInput
}

export type AgencyUncheckedCreateWithoutRelationshipsInput = {
  id?: string
  userId: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ratings?: Prisma.AgencyRatingUncheckedCreateNestedManyWithoutAgencyInput
  savedSearches?: Prisma.AgencySavedSearchUncheckedCreateNestedManyWithoutAgencyInput
}

export type AgencyCreateOrConnectWithoutRelationshipsInput = {
  where: Prisma.AgencyWhereUniqueInput
  create: Prisma.XOR<Prisma.AgencyCreateWithoutRelationshipsInput, Prisma.AgencyUncheckedCreateWithoutRelationshipsInput>
}

export type AgencyUpsertWithoutRelationshipsInput = {
  update: Prisma.XOR<Prisma.AgencyUpdateWithoutRelationshipsInput, Prisma.AgencyUncheckedUpdateWithoutRelationshipsInput>
  create: Prisma.XOR<Prisma.AgencyCreateWithoutRelationshipsInput, Prisma.AgencyUncheckedCreateWithoutRelationshipsInput>
  where?: Prisma.AgencyWhereInput
}

export type AgencyUpdateToOneWithWhereWithoutRelationshipsInput = {
  where?: Prisma.AgencyWhereInput
  data: Prisma.XOR<Prisma.AgencyUpdateWithoutRelationshipsInput, Prisma.AgencyUncheckedUpdateWithoutRelationshipsInput>
}

export type AgencyUpdateWithoutRelationshipsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAgencyNestedInput
  ratings?: Prisma.AgencyRatingUpdateManyWithoutAgencyNestedInput
  savedSearches?: Prisma.AgencySavedSearchUpdateManyWithoutAgencyNestedInput
}

export type AgencyUncheckedUpdateWithoutRelationshipsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ratings?: Prisma.AgencyRatingUncheckedUpdateManyWithoutAgencyNestedInput
  savedSearches?: Prisma.AgencySavedSearchUncheckedUpdateManyWithoutAgencyNestedInput
}

export type AgencyCreateWithoutRatingsInput = {
  id?: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAgencyInput
  relationships?: Prisma.AgencyCaregiverRelationshipCreateNestedManyWithoutAgencyInput
  savedSearches?: Prisma.AgencySavedSearchCreateNestedManyWithoutAgencyInput
}

export type AgencyUncheckedCreateWithoutRatingsInput = {
  id?: string
  userId: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  relationships?: Prisma.AgencyCaregiverRelationshipUncheckedCreateNestedManyWithoutAgencyInput
  savedSearches?: Prisma.AgencySavedSearchUncheckedCreateNestedManyWithoutAgencyInput
}

export type AgencyCreateOrConnectWithoutRatingsInput = {
  where: Prisma.AgencyWhereUniqueInput
  create: Prisma.XOR<Prisma.AgencyCreateWithoutRatingsInput, Prisma.AgencyUncheckedCreateWithoutRatingsInput>
}

export type AgencyUpsertWithoutRatingsInput = {
  update: Prisma.XOR<Prisma.AgencyUpdateWithoutRatingsInput, Prisma.AgencyUncheckedUpdateWithoutRatingsInput>
  create: Prisma.XOR<Prisma.AgencyCreateWithoutRatingsInput, Prisma.AgencyUncheckedCreateWithoutRatingsInput>
  where?: Prisma.AgencyWhereInput
}

export type AgencyUpdateToOneWithWhereWithoutRatingsInput = {
  where?: Prisma.AgencyWhereInput
  data: Prisma.XOR<Prisma.AgencyUpdateWithoutRatingsInput, Prisma.AgencyUncheckedUpdateWithoutRatingsInput>
}

export type AgencyUpdateWithoutRatingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAgencyNestedInput
  relationships?: Prisma.AgencyCaregiverRelationshipUpdateManyWithoutAgencyNestedInput
  savedSearches?: Prisma.AgencySavedSearchUpdateManyWithoutAgencyNestedInput
}

export type AgencyUncheckedUpdateWithoutRatingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  relationships?: Prisma.AgencyCaregiverRelationshipUncheckedUpdateManyWithoutAgencyNestedInput
  savedSearches?: Prisma.AgencySavedSearchUncheckedUpdateManyWithoutAgencyNestedInput
}

export type AgencyCreateWithoutSavedSearchesInput = {
  id?: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAgencyInput
  relationships?: Prisma.AgencyCaregiverRelationshipCreateNestedManyWithoutAgencyInput
  ratings?: Prisma.AgencyRatingCreateNestedManyWithoutAgencyInput
}

export type AgencyUncheckedCreateWithoutSavedSearchesInput = {
  id?: string
  userId: string
  name: string
  description?: string | null
  phone?: string | null
  website?: string | null
  logoUrl?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  postalCode?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  relationships?: Prisma.AgencyCaregiverRelationshipUncheckedCreateNestedManyWithoutAgencyInput
  ratings?: Prisma.AgencyRatingUncheckedCreateNestedManyWithoutAgencyInput
}

export type AgencyCreateOrConnectWithoutSavedSearchesInput = {
  where: Prisma.AgencyWhereUniqueInput
  create: Prisma.XOR<Prisma.AgencyCreateWithoutSavedSearchesInput, Prisma.AgencyUncheckedCreateWithoutSavedSearchesInput>
}

export type AgencyUpsertWithoutSavedSearchesInput = {
  update: Prisma.XOR<Prisma.AgencyUpdateWithoutSavedSearchesInput, Prisma.AgencyUncheckedUpdateWithoutSavedSearchesInput>
  create: Prisma.XOR<Prisma.AgencyCreateWithoutSavedSearchesInput, Prisma.AgencyUncheckedCreateWithoutSavedSearchesInput>
  where?: Prisma.AgencyWhereInput
}

export type AgencyUpdateToOneWithWhereWithoutSavedSearchesInput = {
  where?: Prisma.AgencyWhereInput
  data: Prisma.XOR<Prisma.AgencyUpdateWithoutSavedSearchesInput, Prisma.AgencyUncheckedUpdateWithoutSavedSearchesInput>
}

export type AgencyUpdateWithoutSavedSearchesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAgencyNestedInput
  relationships?: Prisma.AgencyCaregiverRelationshipUpdateManyWithoutAgencyNestedInput
  ratings?: Prisma.AgencyRatingUpdateManyWithoutAgencyNestedInput
}

export type AgencyUncheckedUpdateWithoutSavedSearchesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  relationships?: Prisma.AgencyCaregiverRelationshipUncheckedUpdateManyWithoutAgencyNestedInput
  ratings?: Prisma.AgencyRatingUncheckedUpdateManyWithoutAgencyNestedInput
}


/**
 * Count Type AgencyCountOutputType
 */

export type AgencyCountOutputType = {
  relationships: number
  ratings: number
  savedSearches: number
}

export type AgencyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  relationships?: boolean | AgencyCountOutputTypeCountRelationshipsArgs
  ratings?: boolean | AgencyCountOutputTypeCountRatingsArgs
  savedSearches?: boolean | AgencyCountOutputTypeCountSavedSearchesArgs
}

/**
 * AgencyCountOutputType without action
 */
export type AgencyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyCountOutputType
   */
  select?: Prisma.AgencyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AgencyCountOutputType without action
 */
export type AgencyCountOutputTypeCountRelationshipsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgencyCaregiverRelationshipWhereInput
}

/**
 * AgencyCountOutputType without action
 */
export type AgencyCountOutputTypeCountRatingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgencyRatingWhereInput
}

/**
 * AgencyCountOutputType without action
 */
export type AgencyCountOutputTypeCountSavedSearchesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgencySavedSearchWhereInput
}


export type AgencySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  description?: boolean
  phone?: boolean
  website?: boolean
  logoUrl?: boolean
  address?: boolean
  city?: boolean
  state?: boolean
  postalCode?: boolean
  isVerified?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  relationships?: boolean | Prisma.Agency$relationshipsArgs<ExtArgs>
  ratings?: boolean | Prisma.Agency$ratingsArgs<ExtArgs>
  savedSearches?: boolean | Prisma.Agency$savedSearchesArgs<ExtArgs>
  _count?: boolean | Prisma.AgencyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agency"]>

export type AgencySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  description?: boolean
  phone?: boolean
  website?: boolean
  logoUrl?: boolean
  address?: boolean
  city?: boolean
  state?: boolean
  postalCode?: boolean
  isVerified?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agency"]>

export type AgencySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  description?: boolean
  phone?: boolean
  website?: boolean
  logoUrl?: boolean
  address?: boolean
  city?: boolean
  state?: boolean
  postalCode?: boolean
  isVerified?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agency"]>

export type AgencySelectScalar = {
  id?: boolean
  userId?: boolean
  name?: boolean
  description?: boolean
  phone?: boolean
  website?: boolean
  logoUrl?: boolean
  address?: boolean
  city?: boolean
  state?: boolean
  postalCode?: boolean
  isVerified?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AgencyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "name" | "description" | "phone" | "website" | "logoUrl" | "address" | "city" | "state" | "postalCode" | "isVerified" | "createdAt" | "updatedAt", ExtArgs["result"]["agency"]>
export type AgencyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  relationships?: boolean | Prisma.Agency$relationshipsArgs<ExtArgs>
  ratings?: boolean | Prisma.Agency$ratingsArgs<ExtArgs>
  savedSearches?: boolean | Prisma.Agency$savedSearchesArgs<ExtArgs>
  _count?: boolean | Prisma.AgencyCountOutputTypeDefaultArgs<ExtArgs>
}
export type AgencyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AgencyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AgencyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Agency"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    relationships: Prisma.$AgencyCaregiverRelationshipPayload<ExtArgs>[]
    ratings: Prisma.$AgencyRatingPayload<ExtArgs>[]
    savedSearches: Prisma.$AgencySavedSearchPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    name: string
    description: string | null
    phone: string | null
    website: string | null
    logoUrl: string | null
    address: string | null
    city: string | null
    state: string | null
    postalCode: string | null
    isVerified: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["agency"]>
  composites: {}
}

export type AgencyGetPayload<S extends boolean | null | undefined | AgencyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgencyPayload, S>

export type AgencyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgencyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgencyCountAggregateInputType | true
  }

export interface AgencyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Agency'], meta: { name: 'Agency' } }
  /**
   * Find zero or one Agency that matches the filter.
   * @param {AgencyFindUniqueArgs} args - Arguments to find a Agency
   * @example
   * // Get one Agency
   * const agency = await prisma.agency.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgencyFindUniqueArgs>(args: Prisma.SelectSubset<T, AgencyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgencyClient<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Agency that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgencyFindUniqueOrThrowArgs} args - Arguments to find a Agency
   * @example
   * // Get one Agency
   * const agency = await prisma.agency.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgencyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgencyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgencyClient<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Agency that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyFindFirstArgs} args - Arguments to find a Agency
   * @example
   * // Get one Agency
   * const agency = await prisma.agency.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgencyFindFirstArgs>(args?: Prisma.SelectSubset<T, AgencyFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgencyClient<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Agency that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyFindFirstOrThrowArgs} args - Arguments to find a Agency
   * @example
   * // Get one Agency
   * const agency = await prisma.agency.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgencyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgencyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgencyClient<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Agencies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Agencies
   * const agencies = await prisma.agency.findMany()
   * 
   * // Get first 10 Agencies
   * const agencies = await prisma.agency.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agencyWithIdOnly = await prisma.agency.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgencyFindManyArgs>(args?: Prisma.SelectSubset<T, AgencyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Agency.
   * @param {AgencyCreateArgs} args - Arguments to create a Agency.
   * @example
   * // Create one Agency
   * const Agency = await prisma.agency.create({
   *   data: {
   *     // ... data to create a Agency
   *   }
   * })
   * 
   */
  create<T extends AgencyCreateArgs>(args: Prisma.SelectSubset<T, AgencyCreateArgs<ExtArgs>>): Prisma.Prisma__AgencyClient<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Agencies.
   * @param {AgencyCreateManyArgs} args - Arguments to create many Agencies.
   * @example
   * // Create many Agencies
   * const agency = await prisma.agency.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgencyCreateManyArgs>(args?: Prisma.SelectSubset<T, AgencyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Agencies and returns the data saved in the database.
   * @param {AgencyCreateManyAndReturnArgs} args - Arguments to create many Agencies.
   * @example
   * // Create many Agencies
   * const agency = await prisma.agency.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Agencies and only return the `id`
   * const agencyWithIdOnly = await prisma.agency.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgencyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgencyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Agency.
   * @param {AgencyDeleteArgs} args - Arguments to delete one Agency.
   * @example
   * // Delete one Agency
   * const Agency = await prisma.agency.delete({
   *   where: {
   *     // ... filter to delete one Agency
   *   }
   * })
   * 
   */
  delete<T extends AgencyDeleteArgs>(args: Prisma.SelectSubset<T, AgencyDeleteArgs<ExtArgs>>): Prisma.Prisma__AgencyClient<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Agency.
   * @param {AgencyUpdateArgs} args - Arguments to update one Agency.
   * @example
   * // Update one Agency
   * const agency = await prisma.agency.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgencyUpdateArgs>(args: Prisma.SelectSubset<T, AgencyUpdateArgs<ExtArgs>>): Prisma.Prisma__AgencyClient<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Agencies.
   * @param {AgencyDeleteManyArgs} args - Arguments to filter Agencies to delete.
   * @example
   * // Delete a few Agencies
   * const { count } = await prisma.agency.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgencyDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgencyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Agencies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Agencies
   * const agency = await prisma.agency.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgencyUpdateManyArgs>(args: Prisma.SelectSubset<T, AgencyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Agencies and returns the data updated in the database.
   * @param {AgencyUpdateManyAndReturnArgs} args - Arguments to update many Agencies.
   * @example
   * // Update many Agencies
   * const agency = await prisma.agency.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Agencies and only return the `id`
   * const agencyWithIdOnly = await prisma.agency.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgencyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgencyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Agency.
   * @param {AgencyUpsertArgs} args - Arguments to update or create a Agency.
   * @example
   * // Update or create a Agency
   * const agency = await prisma.agency.upsert({
   *   create: {
   *     // ... data to create a Agency
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Agency we want to update
   *   }
   * })
   */
  upsert<T extends AgencyUpsertArgs>(args: Prisma.SelectSubset<T, AgencyUpsertArgs<ExtArgs>>): Prisma.Prisma__AgencyClient<runtime.Types.Result.GetResult<Prisma.$AgencyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Agencies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyCountArgs} args - Arguments to filter Agencies to count.
   * @example
   * // Count the number of Agencies
   * const count = await prisma.agency.count({
   *   where: {
   *     // ... the filter for the Agencies we want to count
   *   }
   * })
  **/
  count<T extends AgencyCountArgs>(
    args?: Prisma.Subset<T, AgencyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgencyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Agency.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgencyAggregateArgs>(args: Prisma.Subset<T, AgencyAggregateArgs>): Prisma.PrismaPromise<GetAgencyAggregateType<T>>

  /**
   * Group by Agency.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgencyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgencyGroupByArgs['orderBy'] }
      : { orderBy?: AgencyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgencyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgencyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Agency model
 */
readonly fields: AgencyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Agency.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgencyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  relationships<T extends Prisma.Agency$relationshipsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Agency$relationshipsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencyCaregiverRelationshipPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  ratings<T extends Prisma.Agency$ratingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Agency$ratingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencyRatingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  savedSearches<T extends Prisma.Agency$savedSearchesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Agency$savedSearchesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencySavedSearchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Agency model
 */
export interface AgencyFieldRefs {
  readonly id: Prisma.FieldRef<"Agency", 'String'>
  readonly userId: Prisma.FieldRef<"Agency", 'String'>
  readonly name: Prisma.FieldRef<"Agency", 'String'>
  readonly description: Prisma.FieldRef<"Agency", 'String'>
  readonly phone: Prisma.FieldRef<"Agency", 'String'>
  readonly website: Prisma.FieldRef<"Agency", 'String'>
  readonly logoUrl: Prisma.FieldRef<"Agency", 'String'>
  readonly address: Prisma.FieldRef<"Agency", 'String'>
  readonly city: Prisma.FieldRef<"Agency", 'String'>
  readonly state: Prisma.FieldRef<"Agency", 'String'>
  readonly postalCode: Prisma.FieldRef<"Agency", 'String'>
  readonly isVerified: Prisma.FieldRef<"Agency", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Agency", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Agency", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Agency findUnique
 */
export type AgencyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyInclude<ExtArgs> | null
  /**
   * Filter, which Agency to fetch.
   */
  where: Prisma.AgencyWhereUniqueInput
}

/**
 * Agency findUniqueOrThrow
 */
export type AgencyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyInclude<ExtArgs> | null
  /**
   * Filter, which Agency to fetch.
   */
  where: Prisma.AgencyWhereUniqueInput
}

/**
 * Agency findFirst
 */
export type AgencyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyInclude<ExtArgs> | null
  /**
   * Filter, which Agency to fetch.
   */
  where?: Prisma.AgencyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agencies to fetch.
   */
  orderBy?: Prisma.AgencyOrderByWithRelationInput | Prisma.AgencyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Agencies.
   */
  cursor?: Prisma.AgencyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agencies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agencies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Agencies.
   */
  distinct?: Prisma.AgencyScalarFieldEnum | Prisma.AgencyScalarFieldEnum[]
}

/**
 * Agency findFirstOrThrow
 */
export type AgencyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyInclude<ExtArgs> | null
  /**
   * Filter, which Agency to fetch.
   */
  where?: Prisma.AgencyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agencies to fetch.
   */
  orderBy?: Prisma.AgencyOrderByWithRelationInput | Prisma.AgencyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Agencies.
   */
  cursor?: Prisma.AgencyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agencies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agencies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Agencies.
   */
  distinct?: Prisma.AgencyScalarFieldEnum | Prisma.AgencyScalarFieldEnum[]
}

/**
 * Agency findMany
 */
export type AgencyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyInclude<ExtArgs> | null
  /**
   * Filter, which Agencies to fetch.
   */
  where?: Prisma.AgencyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agencies to fetch.
   */
  orderBy?: Prisma.AgencyOrderByWithRelationInput | Prisma.AgencyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Agencies.
   */
  cursor?: Prisma.AgencyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agencies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agencies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Agencies.
   */
  distinct?: Prisma.AgencyScalarFieldEnum | Prisma.AgencyScalarFieldEnum[]
}

/**
 * Agency create
 */
export type AgencyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyInclude<ExtArgs> | null
  /**
   * The data needed to create a Agency.
   */
  data: Prisma.XOR<Prisma.AgencyCreateInput, Prisma.AgencyUncheckedCreateInput>
}

/**
 * Agency createMany
 */
export type AgencyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Agencies.
   */
  data: Prisma.AgencyCreateManyInput | Prisma.AgencyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Agency createManyAndReturn
 */
export type AgencyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * The data used to create many Agencies.
   */
  data: Prisma.AgencyCreateManyInput | Prisma.AgencyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Agency update
 */
export type AgencyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyInclude<ExtArgs> | null
  /**
   * The data needed to update a Agency.
   */
  data: Prisma.XOR<Prisma.AgencyUpdateInput, Prisma.AgencyUncheckedUpdateInput>
  /**
   * Choose, which Agency to update.
   */
  where: Prisma.AgencyWhereUniqueInput
}

/**
 * Agency updateMany
 */
export type AgencyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Agencies.
   */
  data: Prisma.XOR<Prisma.AgencyUpdateManyMutationInput, Prisma.AgencyUncheckedUpdateManyInput>
  /**
   * Filter which Agencies to update
   */
  where?: Prisma.AgencyWhereInput
  /**
   * Limit how many Agencies to update.
   */
  limit?: number
}

/**
 * Agency updateManyAndReturn
 */
export type AgencyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * The data used to update Agencies.
   */
  data: Prisma.XOR<Prisma.AgencyUpdateManyMutationInput, Prisma.AgencyUncheckedUpdateManyInput>
  /**
   * Filter which Agencies to update
   */
  where?: Prisma.AgencyWhereInput
  /**
   * Limit how many Agencies to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Agency upsert
 */
export type AgencyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyInclude<ExtArgs> | null
  /**
   * The filter to search for the Agency to update in case it exists.
   */
  where: Prisma.AgencyWhereUniqueInput
  /**
   * In case the Agency found by the `where` argument doesn't exist, create a new Agency with this data.
   */
  create: Prisma.XOR<Prisma.AgencyCreateInput, Prisma.AgencyUncheckedCreateInput>
  /**
   * In case the Agency was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgencyUpdateInput, Prisma.AgencyUncheckedUpdateInput>
}

/**
 * Agency delete
 */
export type AgencyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyInclude<ExtArgs> | null
  /**
   * Filter which Agency to delete.
   */
  where: Prisma.AgencyWhereUniqueInput
}

/**
 * Agency deleteMany
 */
export type AgencyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Agencies to delete
   */
  where?: Prisma.AgencyWhereInput
  /**
   * Limit how many Agencies to delete.
   */
  limit?: number
}

/**
 * Agency.relationships
 */
export type Agency$relationshipsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyCaregiverRelationship
   */
  select?: Prisma.AgencyCaregiverRelationshipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyCaregiverRelationship
   */
  omit?: Prisma.AgencyCaregiverRelationshipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyCaregiverRelationshipInclude<ExtArgs> | null
  where?: Prisma.AgencyCaregiverRelationshipWhereInput
  orderBy?: Prisma.AgencyCaregiverRelationshipOrderByWithRelationInput | Prisma.AgencyCaregiverRelationshipOrderByWithRelationInput[]
  cursor?: Prisma.AgencyCaregiverRelationshipWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AgencyCaregiverRelationshipScalarFieldEnum | Prisma.AgencyCaregiverRelationshipScalarFieldEnum[]
}

/**
 * Agency.ratings
 */
export type Agency$ratingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyRating
   */
  select?: Prisma.AgencyRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyRating
   */
  omit?: Prisma.AgencyRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyRatingInclude<ExtArgs> | null
  where?: Prisma.AgencyRatingWhereInput
  orderBy?: Prisma.AgencyRatingOrderByWithRelationInput | Prisma.AgencyRatingOrderByWithRelationInput[]
  cursor?: Prisma.AgencyRatingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AgencyRatingScalarFieldEnum | Prisma.AgencyRatingScalarFieldEnum[]
}

/**
 * Agency.savedSearches
 */
export type Agency$savedSearchesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySavedSearch
   */
  select?: Prisma.AgencySavedSearchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySavedSearch
   */
  omit?: Prisma.AgencySavedSearchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySavedSearchInclude<ExtArgs> | null
  where?: Prisma.AgencySavedSearchWhereInput
  orderBy?: Prisma.AgencySavedSearchOrderByWithRelationInput | Prisma.AgencySavedSearchOrderByWithRelationInput[]
  cursor?: Prisma.AgencySavedSearchWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AgencySavedSearchScalarFieldEnum | Prisma.AgencySavedSearchScalarFieldEnum[]
}

/**
 * Agency without action
 */
export type AgencyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agency
   */
  select?: Prisma.AgencySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agency
   */
  omit?: Prisma.AgencyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyInclude<ExtArgs> | null
}
