
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CaregiverSecurity` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CaregiverSecurity
 * 
 */
export type CaregiverSecurityModel = runtime.Types.Result.DefaultSelection<Prisma.$CaregiverSecurityPayload>

export type AggregateCaregiverSecurity = {
  _count: CaregiverSecurityCountAggregateOutputType | null
  _min: CaregiverSecurityMinAggregateOutputType | null
  _max: CaregiverSecurityMaxAggregateOutputType | null
}

export type CaregiverSecurityMinAggregateOutputType = {
  id: string | null
  caregiverId: string | null
  backgroundCheck: string | null
  backgroundCheckDate: Date | null
  backgroundCheckUrl: string | null
  socialSecurity: string | null
  driversLicense: string | null
  driversLicenseState: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CaregiverSecurityMaxAggregateOutputType = {
  id: string | null
  caregiverId: string | null
  backgroundCheck: string | null
  backgroundCheckDate: Date | null
  backgroundCheckUrl: string | null
  socialSecurity: string | null
  driversLicense: string | null
  driversLicenseState: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CaregiverSecurityCountAggregateOutputType = {
  id: number
  caregiverId: number
  backgroundCheck: number
  backgroundCheckDate: number
  backgroundCheckUrl: number
  socialSecurity: number
  driversLicense: number
  driversLicenseState: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CaregiverSecurityMinAggregateInputType = {
  id?: true
  caregiverId?: true
  backgroundCheck?: true
  backgroundCheckDate?: true
  backgroundCheckUrl?: true
  socialSecurity?: true
  driversLicense?: true
  driversLicenseState?: true
  createdAt?: true
  updatedAt?: true
}

export type CaregiverSecurityMaxAggregateInputType = {
  id?: true
  caregiverId?: true
  backgroundCheck?: true
  backgroundCheckDate?: true
  backgroundCheckUrl?: true
  socialSecurity?: true
  driversLicense?: true
  driversLicenseState?: true
  createdAt?: true
  updatedAt?: true
}

export type CaregiverSecurityCountAggregateInputType = {
  id?: true
  caregiverId?: true
  backgroundCheck?: true
  backgroundCheckDate?: true
  backgroundCheckUrl?: true
  socialSecurity?: true
  driversLicense?: true
  driversLicenseState?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CaregiverSecurityAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CaregiverSecurity to aggregate.
   */
  where?: Prisma.CaregiverSecurityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverSecurities to fetch.
   */
  orderBy?: Prisma.CaregiverSecurityOrderByWithRelationInput | Prisma.CaregiverSecurityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CaregiverSecurityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverSecurities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverSecurities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CaregiverSecurities
  **/
  _count?: true | CaregiverSecurityCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CaregiverSecurityMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CaregiverSecurityMaxAggregateInputType
}

export type GetCaregiverSecurityAggregateType<T extends CaregiverSecurityAggregateArgs> = {
      [P in keyof T & keyof AggregateCaregiverSecurity]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCaregiverSecurity[P]>
    : Prisma.GetScalarType<T[P], AggregateCaregiverSecurity[P]>
}




export type CaregiverSecurityGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CaregiverSecurityWhereInput
  orderBy?: Prisma.CaregiverSecurityOrderByWithAggregationInput | Prisma.CaregiverSecurityOrderByWithAggregationInput[]
  by: Prisma.CaregiverSecurityScalarFieldEnum[] | Prisma.CaregiverSecurityScalarFieldEnum
  having?: Prisma.CaregiverSecurityScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CaregiverSecurityCountAggregateInputType | true
  _min?: CaregiverSecurityMinAggregateInputType
  _max?: CaregiverSecurityMaxAggregateInputType
}

export type CaregiverSecurityGroupByOutputType = {
  id: string
  caregiverId: string
  backgroundCheck: string | null
  backgroundCheckDate: Date | null
  backgroundCheckUrl: string | null
  socialSecurity: string | null
  driversLicense: string | null
  driversLicenseState: string | null
  createdAt: Date
  updatedAt: Date
  _count: CaregiverSecurityCountAggregateOutputType | null
  _min: CaregiverSecurityMinAggregateOutputType | null
  _max: CaregiverSecurityMaxAggregateOutputType | null
}

export type GetCaregiverSecurityGroupByPayload<T extends CaregiverSecurityGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CaregiverSecurityGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CaregiverSecurityGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CaregiverSecurityGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CaregiverSecurityGroupByOutputType[P]>
      }
    >
  >



export type CaregiverSecurityWhereInput = {
  AND?: Prisma.CaregiverSecurityWhereInput | Prisma.CaregiverSecurityWhereInput[]
  OR?: Prisma.CaregiverSecurityWhereInput[]
  NOT?: Prisma.CaregiverSecurityWhereInput | Prisma.CaregiverSecurityWhereInput[]
  id?: Prisma.StringFilter<"CaregiverSecurity"> | string
  caregiverId?: Prisma.StringFilter<"CaregiverSecurity"> | string
  backgroundCheck?: Prisma.StringNullableFilter<"CaregiverSecurity"> | string | null
  backgroundCheckDate?: Prisma.DateTimeNullableFilter<"CaregiverSecurity"> | Date | string | null
  backgroundCheckUrl?: Prisma.StringNullableFilter<"CaregiverSecurity"> | string | null
  socialSecurity?: Prisma.StringNullableFilter<"CaregiverSecurity"> | string | null
  driversLicense?: Prisma.StringNullableFilter<"CaregiverSecurity"> | string | null
  driversLicenseState?: Prisma.StringNullableFilter<"CaregiverSecurity"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverSecurity"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CaregiverSecurity"> | Date | string
  caregiver?: Prisma.XOR<Prisma.CaregiverScalarRelationFilter, Prisma.CaregiverWhereInput>
}

export type CaregiverSecurityOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  backgroundCheck?: Prisma.SortOrderInput | Prisma.SortOrder
  backgroundCheckDate?: Prisma.SortOrderInput | Prisma.SortOrder
  backgroundCheckUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  socialSecurity?: Prisma.SortOrderInput | Prisma.SortOrder
  driversLicense?: Prisma.SortOrderInput | Prisma.SortOrder
  driversLicenseState?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  caregiver?: Prisma.CaregiverOrderByWithRelationInput
}

export type CaregiverSecurityWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  caregiverId?: string
  AND?: Prisma.CaregiverSecurityWhereInput | Prisma.CaregiverSecurityWhereInput[]
  OR?: Prisma.CaregiverSecurityWhereInput[]
  NOT?: Prisma.CaregiverSecurityWhereInput | Prisma.CaregiverSecurityWhereInput[]
  backgroundCheck?: Prisma.StringNullableFilter<"CaregiverSecurity"> | string | null
  backgroundCheckDate?: Prisma.DateTimeNullableFilter<"CaregiverSecurity"> | Date | string | null
  backgroundCheckUrl?: Prisma.StringNullableFilter<"CaregiverSecurity"> | string | null
  socialSecurity?: Prisma.StringNullableFilter<"CaregiverSecurity"> | string | null
  driversLicense?: Prisma.StringNullableFilter<"CaregiverSecurity"> | string | null
  driversLicenseState?: Prisma.StringNullableFilter<"CaregiverSecurity"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverSecurity"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CaregiverSecurity"> | Date | string
  caregiver?: Prisma.XOR<Prisma.CaregiverScalarRelationFilter, Prisma.CaregiverWhereInput>
}, "id" | "caregiverId">

export type CaregiverSecurityOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  backgroundCheck?: Prisma.SortOrderInput | Prisma.SortOrder
  backgroundCheckDate?: Prisma.SortOrderInput | Prisma.SortOrder
  backgroundCheckUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  socialSecurity?: Prisma.SortOrderInput | Prisma.SortOrder
  driversLicense?: Prisma.SortOrderInput | Prisma.SortOrder
  driversLicenseState?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CaregiverSecurityCountOrderByAggregateInput
  _max?: Prisma.CaregiverSecurityMaxOrderByAggregateInput
  _min?: Prisma.CaregiverSecurityMinOrderByAggregateInput
}

export type CaregiverSecurityScalarWhereWithAggregatesInput = {
  AND?: Prisma.CaregiverSecurityScalarWhereWithAggregatesInput | Prisma.CaregiverSecurityScalarWhereWithAggregatesInput[]
  OR?: Prisma.CaregiverSecurityScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CaregiverSecurityScalarWhereWithAggregatesInput | Prisma.CaregiverSecurityScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CaregiverSecurity"> | string
  caregiverId?: Prisma.StringWithAggregatesFilter<"CaregiverSecurity"> | string
  backgroundCheck?: Prisma.StringNullableWithAggregatesFilter<"CaregiverSecurity"> | string | null
  backgroundCheckDate?: Prisma.DateTimeNullableWithAggregatesFilter<"CaregiverSecurity"> | Date | string | null
  backgroundCheckUrl?: Prisma.StringNullableWithAggregatesFilter<"CaregiverSecurity"> | string | null
  socialSecurity?: Prisma.StringNullableWithAggregatesFilter<"CaregiverSecurity"> | string | null
  driversLicense?: Prisma.StringNullableWithAggregatesFilter<"CaregiverSecurity"> | string | null
  driversLicenseState?: Prisma.StringNullableWithAggregatesFilter<"CaregiverSecurity"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CaregiverSecurity"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CaregiverSecurity"> | Date | string
}

export type CaregiverSecurityCreateInput = {
  id?: string
  backgroundCheck?: string | null
  backgroundCheckDate?: Date | string | null
  backgroundCheckUrl?: string | null
  socialSecurity?: string | null
  driversLicense?: string | null
  driversLicenseState?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  caregiver: Prisma.CaregiverCreateNestedOneWithoutSecurityInput
}

export type CaregiverSecurityUncheckedCreateInput = {
  id?: string
  caregiverId: string
  backgroundCheck?: string | null
  backgroundCheckDate?: Date | string | null
  backgroundCheckUrl?: string | null
  socialSecurity?: string | null
  driversLicense?: string | null
  driversLicenseState?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CaregiverSecurityUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  backgroundCheck?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  backgroundCheckDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  backgroundCheckUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  socialSecurity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicense?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicenseState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  caregiver?: Prisma.CaregiverUpdateOneRequiredWithoutSecurityNestedInput
}

export type CaregiverSecurityUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  backgroundCheck?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  backgroundCheckDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  backgroundCheckUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  socialSecurity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicense?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicenseState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverSecurityCreateManyInput = {
  id?: string
  caregiverId: string
  backgroundCheck?: string | null
  backgroundCheckDate?: Date | string | null
  backgroundCheckUrl?: string | null
  socialSecurity?: string | null
  driversLicense?: string | null
  driversLicenseState?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CaregiverSecurityUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  backgroundCheck?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  backgroundCheckDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  backgroundCheckUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  socialSecurity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicense?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicenseState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverSecurityUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  backgroundCheck?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  backgroundCheckDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  backgroundCheckUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  socialSecurity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicense?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicenseState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverSecurityNullableScalarRelationFilter = {
  is?: Prisma.CaregiverSecurityWhereInput | null
  isNot?: Prisma.CaregiverSecurityWhereInput | null
}

export type CaregiverSecurityCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  backgroundCheck?: Prisma.SortOrder
  backgroundCheckDate?: Prisma.SortOrder
  backgroundCheckUrl?: Prisma.SortOrder
  socialSecurity?: Prisma.SortOrder
  driversLicense?: Prisma.SortOrder
  driversLicenseState?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CaregiverSecurityMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  backgroundCheck?: Prisma.SortOrder
  backgroundCheckDate?: Prisma.SortOrder
  backgroundCheckUrl?: Prisma.SortOrder
  socialSecurity?: Prisma.SortOrder
  driversLicense?: Prisma.SortOrder
  driversLicenseState?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CaregiverSecurityMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  backgroundCheck?: Prisma.SortOrder
  backgroundCheckDate?: Prisma.SortOrder
  backgroundCheckUrl?: Prisma.SortOrder
  socialSecurity?: Prisma.SortOrder
  driversLicense?: Prisma.SortOrder
  driversLicenseState?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CaregiverSecurityCreateNestedOneWithoutCaregiverInput = {
  create?: Prisma.XOR<Prisma.CaregiverSecurityCreateWithoutCaregiverInput, Prisma.CaregiverSecurityUncheckedCreateWithoutCaregiverInput>
  connectOrCreate?: Prisma.CaregiverSecurityCreateOrConnectWithoutCaregiverInput
  connect?: Prisma.CaregiverSecurityWhereUniqueInput
}

export type CaregiverSecurityUncheckedCreateNestedOneWithoutCaregiverInput = {
  create?: Prisma.XOR<Prisma.CaregiverSecurityCreateWithoutCaregiverInput, Prisma.CaregiverSecurityUncheckedCreateWithoutCaregiverInput>
  connectOrCreate?: Prisma.CaregiverSecurityCreateOrConnectWithoutCaregiverInput
  connect?: Prisma.CaregiverSecurityWhereUniqueInput
}

export type CaregiverSecurityUpdateOneWithoutCaregiverNestedInput = {
  create?: Prisma.XOR<Prisma.CaregiverSecurityCreateWithoutCaregiverInput, Prisma.CaregiverSecurityUncheckedCreateWithoutCaregiverInput>
  connectOrCreate?: Prisma.CaregiverSecurityCreateOrConnectWithoutCaregiverInput
  upsert?: Prisma.CaregiverSecurityUpsertWithoutCaregiverInput
  disconnect?: Prisma.CaregiverSecurityWhereInput | boolean
  delete?: Prisma.CaregiverSecurityWhereInput | boolean
  connect?: Prisma.CaregiverSecurityWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CaregiverSecurityUpdateToOneWithWhereWithoutCaregiverInput, Prisma.CaregiverSecurityUpdateWithoutCaregiverInput>, Prisma.CaregiverSecurityUncheckedUpdateWithoutCaregiverInput>
}

export type CaregiverSecurityUncheckedUpdateOneWithoutCaregiverNestedInput = {
  create?: Prisma.XOR<Prisma.CaregiverSecurityCreateWithoutCaregiverInput, Prisma.CaregiverSecurityUncheckedCreateWithoutCaregiverInput>
  connectOrCreate?: Prisma.CaregiverSecurityCreateOrConnectWithoutCaregiverInput
  upsert?: Prisma.CaregiverSecurityUpsertWithoutCaregiverInput
  disconnect?: Prisma.CaregiverSecurityWhereInput | boolean
  delete?: Prisma.CaregiverSecurityWhereInput | boolean
  connect?: Prisma.CaregiverSecurityWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CaregiverSecurityUpdateToOneWithWhereWithoutCaregiverInput, Prisma.CaregiverSecurityUpdateWithoutCaregiverInput>, Prisma.CaregiverSecurityUncheckedUpdateWithoutCaregiverInput>
}

export type CaregiverSecurityCreateWithoutCaregiverInput = {
  id?: string
  backgroundCheck?: string | null
  backgroundCheckDate?: Date | string | null
  backgroundCheckUrl?: string | null
  socialSecurity?: string | null
  driversLicense?: string | null
  driversLicenseState?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CaregiverSecurityUncheckedCreateWithoutCaregiverInput = {
  id?: string
  backgroundCheck?: string | null
  backgroundCheckDate?: Date | string | null
  backgroundCheckUrl?: string | null
  socialSecurity?: string | null
  driversLicense?: string | null
  driversLicenseState?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CaregiverSecurityCreateOrConnectWithoutCaregiverInput = {
  where: Prisma.CaregiverSecurityWhereUniqueInput
  create: Prisma.XOR<Prisma.CaregiverSecurityCreateWithoutCaregiverInput, Prisma.CaregiverSecurityUncheckedCreateWithoutCaregiverInput>
}

export type CaregiverSecurityUpsertWithoutCaregiverInput = {
  update: Prisma.XOR<Prisma.CaregiverSecurityUpdateWithoutCaregiverInput, Prisma.CaregiverSecurityUncheckedUpdateWithoutCaregiverInput>
  create: Prisma.XOR<Prisma.CaregiverSecurityCreateWithoutCaregiverInput, Prisma.CaregiverSecurityUncheckedCreateWithoutCaregiverInput>
  where?: Prisma.CaregiverSecurityWhereInput
}

export type CaregiverSecurityUpdateToOneWithWhereWithoutCaregiverInput = {
  where?: Prisma.CaregiverSecurityWhereInput
  data: Prisma.XOR<Prisma.CaregiverSecurityUpdateWithoutCaregiverInput, Prisma.CaregiverSecurityUncheckedUpdateWithoutCaregiverInput>
}

export type CaregiverSecurityUpdateWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  backgroundCheck?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  backgroundCheckDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  backgroundCheckUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  socialSecurity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicense?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicenseState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverSecurityUncheckedUpdateWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  backgroundCheck?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  backgroundCheckDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  backgroundCheckUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  socialSecurity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicense?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driversLicenseState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CaregiverSecuritySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caregiverId?: boolean
  backgroundCheck?: boolean
  backgroundCheckDate?: boolean
  backgroundCheckUrl?: boolean
  socialSecurity?: boolean
  driversLicense?: boolean
  driversLicenseState?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverSecurity"]>

export type CaregiverSecuritySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caregiverId?: boolean
  backgroundCheck?: boolean
  backgroundCheckDate?: boolean
  backgroundCheckUrl?: boolean
  socialSecurity?: boolean
  driversLicense?: boolean
  driversLicenseState?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverSecurity"]>

export type CaregiverSecuritySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caregiverId?: boolean
  backgroundCheck?: boolean
  backgroundCheckDate?: boolean
  backgroundCheckUrl?: boolean
  socialSecurity?: boolean
  driversLicense?: boolean
  driversLicenseState?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverSecurity"]>

export type CaregiverSecuritySelectScalar = {
  id?: boolean
  caregiverId?: boolean
  backgroundCheck?: boolean
  backgroundCheckDate?: boolean
  backgroundCheckUrl?: boolean
  socialSecurity?: boolean
  driversLicense?: boolean
  driversLicenseState?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CaregiverSecurityOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "caregiverId" | "backgroundCheck" | "backgroundCheckDate" | "backgroundCheckUrl" | "socialSecurity" | "driversLicense" | "driversLicenseState" | "createdAt" | "updatedAt", ExtArgs["result"]["caregiverSecurity"]>
export type CaregiverSecurityInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}
export type CaregiverSecurityIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}
export type CaregiverSecurityIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}

export type $CaregiverSecurityPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CaregiverSecurity"
  objects: {
    caregiver: Prisma.$CaregiverPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    caregiverId: string
    backgroundCheck: string | null
    backgroundCheckDate: Date | null
    backgroundCheckUrl: string | null
    socialSecurity: string | null
    driversLicense: string | null
    driversLicenseState: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["caregiverSecurity"]>
  composites: {}
}

export type CaregiverSecurityGetPayload<S extends boolean | null | undefined | CaregiverSecurityDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload, S>

export type CaregiverSecurityCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CaregiverSecurityFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CaregiverSecurityCountAggregateInputType | true
  }

export interface CaregiverSecurityDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CaregiverSecurity'], meta: { name: 'CaregiverSecurity' } }
  /**
   * Find zero or one CaregiverSecurity that matches the filter.
   * @param {CaregiverSecurityFindUniqueArgs} args - Arguments to find a CaregiverSecurity
   * @example
   * // Get one CaregiverSecurity
   * const caregiverSecurity = await prisma.caregiverSecurity.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CaregiverSecurityFindUniqueArgs>(args: Prisma.SelectSubset<T, CaregiverSecurityFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CaregiverSecurityClient<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CaregiverSecurity that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CaregiverSecurityFindUniqueOrThrowArgs} args - Arguments to find a CaregiverSecurity
   * @example
   * // Get one CaregiverSecurity
   * const caregiverSecurity = await prisma.caregiverSecurity.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CaregiverSecurityFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CaregiverSecurityFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CaregiverSecurityClient<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CaregiverSecurity that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverSecurityFindFirstArgs} args - Arguments to find a CaregiverSecurity
   * @example
   * // Get one CaregiverSecurity
   * const caregiverSecurity = await prisma.caregiverSecurity.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CaregiverSecurityFindFirstArgs>(args?: Prisma.SelectSubset<T, CaregiverSecurityFindFirstArgs<ExtArgs>>): Prisma.Prisma__CaregiverSecurityClient<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CaregiverSecurity that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverSecurityFindFirstOrThrowArgs} args - Arguments to find a CaregiverSecurity
   * @example
   * // Get one CaregiverSecurity
   * const caregiverSecurity = await prisma.caregiverSecurity.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CaregiverSecurityFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CaregiverSecurityFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CaregiverSecurityClient<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CaregiverSecurities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverSecurityFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CaregiverSecurities
   * const caregiverSecurities = await prisma.caregiverSecurity.findMany()
   * 
   * // Get first 10 CaregiverSecurities
   * const caregiverSecurities = await prisma.caregiverSecurity.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const caregiverSecurityWithIdOnly = await prisma.caregiverSecurity.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CaregiverSecurityFindManyArgs>(args?: Prisma.SelectSubset<T, CaregiverSecurityFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CaregiverSecurity.
   * @param {CaregiverSecurityCreateArgs} args - Arguments to create a CaregiverSecurity.
   * @example
   * // Create one CaregiverSecurity
   * const CaregiverSecurity = await prisma.caregiverSecurity.create({
   *   data: {
   *     // ... data to create a CaregiverSecurity
   *   }
   * })
   * 
   */
  create<T extends CaregiverSecurityCreateArgs>(args: Prisma.SelectSubset<T, CaregiverSecurityCreateArgs<ExtArgs>>): Prisma.Prisma__CaregiverSecurityClient<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CaregiverSecurities.
   * @param {CaregiverSecurityCreateManyArgs} args - Arguments to create many CaregiverSecurities.
   * @example
   * // Create many CaregiverSecurities
   * const caregiverSecurity = await prisma.caregiverSecurity.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CaregiverSecurityCreateManyArgs>(args?: Prisma.SelectSubset<T, CaregiverSecurityCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CaregiverSecurities and returns the data saved in the database.
   * @param {CaregiverSecurityCreateManyAndReturnArgs} args - Arguments to create many CaregiverSecurities.
   * @example
   * // Create many CaregiverSecurities
   * const caregiverSecurity = await prisma.caregiverSecurity.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CaregiverSecurities and only return the `id`
   * const caregiverSecurityWithIdOnly = await prisma.caregiverSecurity.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CaregiverSecurityCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CaregiverSecurityCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CaregiverSecurity.
   * @param {CaregiverSecurityDeleteArgs} args - Arguments to delete one CaregiverSecurity.
   * @example
   * // Delete one CaregiverSecurity
   * const CaregiverSecurity = await prisma.caregiverSecurity.delete({
   *   where: {
   *     // ... filter to delete one CaregiverSecurity
   *   }
   * })
   * 
   */
  delete<T extends CaregiverSecurityDeleteArgs>(args: Prisma.SelectSubset<T, CaregiverSecurityDeleteArgs<ExtArgs>>): Prisma.Prisma__CaregiverSecurityClient<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CaregiverSecurity.
   * @param {CaregiverSecurityUpdateArgs} args - Arguments to update one CaregiverSecurity.
   * @example
   * // Update one CaregiverSecurity
   * const caregiverSecurity = await prisma.caregiverSecurity.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CaregiverSecurityUpdateArgs>(args: Prisma.SelectSubset<T, CaregiverSecurityUpdateArgs<ExtArgs>>): Prisma.Prisma__CaregiverSecurityClient<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CaregiverSecurities.
   * @param {CaregiverSecurityDeleteManyArgs} args - Arguments to filter CaregiverSecurities to delete.
   * @example
   * // Delete a few CaregiverSecurities
   * const { count } = await prisma.caregiverSecurity.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CaregiverSecurityDeleteManyArgs>(args?: Prisma.SelectSubset<T, CaregiverSecurityDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CaregiverSecurities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverSecurityUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CaregiverSecurities
   * const caregiverSecurity = await prisma.caregiverSecurity.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CaregiverSecurityUpdateManyArgs>(args: Prisma.SelectSubset<T, CaregiverSecurityUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CaregiverSecurities and returns the data updated in the database.
   * @param {CaregiverSecurityUpdateManyAndReturnArgs} args - Arguments to update many CaregiverSecurities.
   * @example
   * // Update many CaregiverSecurities
   * const caregiverSecurity = await prisma.caregiverSecurity.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CaregiverSecurities and only return the `id`
   * const caregiverSecurityWithIdOnly = await prisma.caregiverSecurity.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CaregiverSecurityUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CaregiverSecurityUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CaregiverSecurity.
   * @param {CaregiverSecurityUpsertArgs} args - Arguments to update or create a CaregiverSecurity.
   * @example
   * // Update or create a CaregiverSecurity
   * const caregiverSecurity = await prisma.caregiverSecurity.upsert({
   *   create: {
   *     // ... data to create a CaregiverSecurity
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CaregiverSecurity we want to update
   *   }
   * })
   */
  upsert<T extends CaregiverSecurityUpsertArgs>(args: Prisma.SelectSubset<T, CaregiverSecurityUpsertArgs<ExtArgs>>): Prisma.Prisma__CaregiverSecurityClient<runtime.Types.Result.GetResult<Prisma.$CaregiverSecurityPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CaregiverSecurities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverSecurityCountArgs} args - Arguments to filter CaregiverSecurities to count.
   * @example
   * // Count the number of CaregiverSecurities
   * const count = await prisma.caregiverSecurity.count({
   *   where: {
   *     // ... the filter for the CaregiverSecurities we want to count
   *   }
   * })
  **/
  count<T extends CaregiverSecurityCountArgs>(
    args?: Prisma.Subset<T, CaregiverSecurityCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CaregiverSecurityCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CaregiverSecurity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverSecurityAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CaregiverSecurityAggregateArgs>(args: Prisma.Subset<T, CaregiverSecurityAggregateArgs>): Prisma.PrismaPromise<GetCaregiverSecurityAggregateType<T>>

  /**
   * Group by CaregiverSecurity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverSecurityGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CaregiverSecurityGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CaregiverSecurityGroupByArgs['orderBy'] }
      : { orderBy?: CaregiverSecurityGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CaregiverSecurityGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCaregiverSecurityGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CaregiverSecurity model
 */
readonly fields: CaregiverSecurityFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CaregiverSecurity.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CaregiverSecurityClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  caregiver<T extends Prisma.CaregiverDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CaregiverDefaultArgs<ExtArgs>>): Prisma.Prisma__CaregiverClient<runtime.Types.Result.GetResult<Prisma.$CaregiverPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CaregiverSecurity model
 */
export interface CaregiverSecurityFieldRefs {
  readonly id: Prisma.FieldRef<"CaregiverSecurity", 'String'>
  readonly caregiverId: Prisma.FieldRef<"CaregiverSecurity", 'String'>
  readonly backgroundCheck: Prisma.FieldRef<"CaregiverSecurity", 'String'>
  readonly backgroundCheckDate: Prisma.FieldRef<"CaregiverSecurity", 'DateTime'>
  readonly backgroundCheckUrl: Prisma.FieldRef<"CaregiverSecurity", 'String'>
  readonly socialSecurity: Prisma.FieldRef<"CaregiverSecurity", 'String'>
  readonly driversLicense: Prisma.FieldRef<"CaregiverSecurity", 'String'>
  readonly driversLicenseState: Prisma.FieldRef<"CaregiverSecurity", 'String'>
  readonly createdAt: Prisma.FieldRef<"CaregiverSecurity", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CaregiverSecurity", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CaregiverSecurity findUnique
 */
export type CaregiverSecurityFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverSecurity to fetch.
   */
  where: Prisma.CaregiverSecurityWhereUniqueInput
}

/**
 * CaregiverSecurity findUniqueOrThrow
 */
export type CaregiverSecurityFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverSecurity to fetch.
   */
  where: Prisma.CaregiverSecurityWhereUniqueInput
}

/**
 * CaregiverSecurity findFirst
 */
export type CaregiverSecurityFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverSecurity to fetch.
   */
  where?: Prisma.CaregiverSecurityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverSecurities to fetch.
   */
  orderBy?: Prisma.CaregiverSecurityOrderByWithRelationInput | Prisma.CaregiverSecurityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CaregiverSecurities.
   */
  cursor?: Prisma.CaregiverSecurityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverSecurities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverSecurities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverSecurities.
   */
  distinct?: Prisma.CaregiverSecurityScalarFieldEnum | Prisma.CaregiverSecurityScalarFieldEnum[]
}

/**
 * CaregiverSecurity findFirstOrThrow
 */
export type CaregiverSecurityFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverSecurity to fetch.
   */
  where?: Prisma.CaregiverSecurityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverSecurities to fetch.
   */
  orderBy?: Prisma.CaregiverSecurityOrderByWithRelationInput | Prisma.CaregiverSecurityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CaregiverSecurities.
   */
  cursor?: Prisma.CaregiverSecurityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverSecurities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverSecurities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverSecurities.
   */
  distinct?: Prisma.CaregiverSecurityScalarFieldEnum | Prisma.CaregiverSecurityScalarFieldEnum[]
}

/**
 * CaregiverSecurity findMany
 */
export type CaregiverSecurityFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverSecurities to fetch.
   */
  where?: Prisma.CaregiverSecurityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverSecurities to fetch.
   */
  orderBy?: Prisma.CaregiverSecurityOrderByWithRelationInput | Prisma.CaregiverSecurityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CaregiverSecurities.
   */
  cursor?: Prisma.CaregiverSecurityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverSecurities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverSecurities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverSecurities.
   */
  distinct?: Prisma.CaregiverSecurityScalarFieldEnum | Prisma.CaregiverSecurityScalarFieldEnum[]
}

/**
 * CaregiverSecurity create
 */
export type CaregiverSecurityCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityInclude<ExtArgs> | null
  /**
   * The data needed to create a CaregiverSecurity.
   */
  data: Prisma.XOR<Prisma.CaregiverSecurityCreateInput, Prisma.CaregiverSecurityUncheckedCreateInput>
}

/**
 * CaregiverSecurity createMany
 */
export type CaregiverSecurityCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CaregiverSecurities.
   */
  data: Prisma.CaregiverSecurityCreateManyInput | Prisma.CaregiverSecurityCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CaregiverSecurity createManyAndReturn
 */
export type CaregiverSecurityCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * The data used to create many CaregiverSecurities.
   */
  data: Prisma.CaregiverSecurityCreateManyInput | Prisma.CaregiverSecurityCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CaregiverSecurity update
 */
export type CaregiverSecurityUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityInclude<ExtArgs> | null
  /**
   * The data needed to update a CaregiverSecurity.
   */
  data: Prisma.XOR<Prisma.CaregiverSecurityUpdateInput, Prisma.CaregiverSecurityUncheckedUpdateInput>
  /**
   * Choose, which CaregiverSecurity to update.
   */
  where: Prisma.CaregiverSecurityWhereUniqueInput
}

/**
 * CaregiverSecurity updateMany
 */
export type CaregiverSecurityUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CaregiverSecurities.
   */
  data: Prisma.XOR<Prisma.CaregiverSecurityUpdateManyMutationInput, Prisma.CaregiverSecurityUncheckedUpdateManyInput>
  /**
   * Filter which CaregiverSecurities to update
   */
  where?: Prisma.CaregiverSecurityWhereInput
  /**
   * Limit how many CaregiverSecurities to update.
   */
  limit?: number
}

/**
 * CaregiverSecurity updateManyAndReturn
 */
export type CaregiverSecurityUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * The data used to update CaregiverSecurities.
   */
  data: Prisma.XOR<Prisma.CaregiverSecurityUpdateManyMutationInput, Prisma.CaregiverSecurityUncheckedUpdateManyInput>
  /**
   * Filter which CaregiverSecurities to update
   */
  where?: Prisma.CaregiverSecurityWhereInput
  /**
   * Limit how many CaregiverSecurities to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CaregiverSecurity upsert
 */
export type CaregiverSecurityUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityInclude<ExtArgs> | null
  /**
   * The filter to search for the CaregiverSecurity to update in case it exists.
   */
  where: Prisma.CaregiverSecurityWhereUniqueInput
  /**
   * In case the CaregiverSecurity found by the `where` argument doesn't exist, create a new CaregiverSecurity with this data.
   */
  create: Prisma.XOR<Prisma.CaregiverSecurityCreateInput, Prisma.CaregiverSecurityUncheckedCreateInput>
  /**
   * In case the CaregiverSecurity was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CaregiverSecurityUpdateInput, Prisma.CaregiverSecurityUncheckedUpdateInput>
}

/**
 * CaregiverSecurity delete
 */
export type CaregiverSecurityDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityInclude<ExtArgs> | null
  /**
   * Filter which CaregiverSecurity to delete.
   */
  where: Prisma.CaregiverSecurityWhereUniqueInput
}

/**
 * CaregiverSecurity deleteMany
 */
export type CaregiverSecurityDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CaregiverSecurities to delete
   */
  where?: Prisma.CaregiverSecurityWhereInput
  /**
   * Limit how many CaregiverSecurities to delete.
   */
  limit?: number
}

/**
 * CaregiverSecurity without action
 */
export type CaregiverSecurityDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverSecurity
   */
  select?: Prisma.CaregiverSecuritySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverSecurity
   */
  omit?: Prisma.CaregiverSecurityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverSecurityInclude<ExtArgs> | null
}
