
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CaregiverRating` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CaregiverRating
 * 
 */
export type CaregiverRatingModel = runtime.Types.Result.DefaultSelection<Prisma.$CaregiverRatingPayload>

export type AggregateCaregiverRating = {
  _count: CaregiverRatingCountAggregateOutputType | null
  _avg: CaregiverRatingAvgAggregateOutputType | null
  _sum: CaregiverRatingSumAggregateOutputType | null
  _min: CaregiverRatingMinAggregateOutputType | null
  _max: CaregiverRatingMaxAggregateOutputType | null
}

export type CaregiverRatingAvgAggregateOutputType = {
  rating: number | null
}

export type CaregiverRatingSumAggregateOutputType = {
  rating: number | null
}

export type CaregiverRatingMinAggregateOutputType = {
  id: string | null
  caregiverId: string | null
  rating: number | null
  review: string | null
  reviewerName: string | null
  createdAt: Date | null
}

export type CaregiverRatingMaxAggregateOutputType = {
  id: string | null
  caregiverId: string | null
  rating: number | null
  review: string | null
  reviewerName: string | null
  createdAt: Date | null
}

export type CaregiverRatingCountAggregateOutputType = {
  id: number
  caregiverId: number
  rating: number
  review: number
  reviewerName: number
  createdAt: number
  _all: number
}


export type CaregiverRatingAvgAggregateInputType = {
  rating?: true
}

export type CaregiverRatingSumAggregateInputType = {
  rating?: true
}

export type CaregiverRatingMinAggregateInputType = {
  id?: true
  caregiverId?: true
  rating?: true
  review?: true
  reviewerName?: true
  createdAt?: true
}

export type CaregiverRatingMaxAggregateInputType = {
  id?: true
  caregiverId?: true
  rating?: true
  review?: true
  reviewerName?: true
  createdAt?: true
}

export type CaregiverRatingCountAggregateInputType = {
  id?: true
  caregiverId?: true
  rating?: true
  review?: true
  reviewerName?: true
  createdAt?: true
  _all?: true
}

export type CaregiverRatingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CaregiverRating to aggregate.
   */
  where?: Prisma.CaregiverRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverRatings to fetch.
   */
  orderBy?: Prisma.CaregiverRatingOrderByWithRelationInput | Prisma.CaregiverRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CaregiverRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CaregiverRatings
  **/
  _count?: true | CaregiverRatingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CaregiverRatingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CaregiverRatingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CaregiverRatingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CaregiverRatingMaxAggregateInputType
}

export type GetCaregiverRatingAggregateType<T extends CaregiverRatingAggregateArgs> = {
      [P in keyof T & keyof AggregateCaregiverRating]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCaregiverRating[P]>
    : Prisma.GetScalarType<T[P], AggregateCaregiverRating[P]>
}




export type CaregiverRatingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CaregiverRatingWhereInput
  orderBy?: Prisma.CaregiverRatingOrderByWithAggregationInput | Prisma.CaregiverRatingOrderByWithAggregationInput[]
  by: Prisma.CaregiverRatingScalarFieldEnum[] | Prisma.CaregiverRatingScalarFieldEnum
  having?: Prisma.CaregiverRatingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CaregiverRatingCountAggregateInputType | true
  _avg?: CaregiverRatingAvgAggregateInputType
  _sum?: CaregiverRatingSumAggregateInputType
  _min?: CaregiverRatingMinAggregateInputType
  _max?: CaregiverRatingMaxAggregateInputType
}

export type CaregiverRatingGroupByOutputType = {
  id: string
  caregiverId: string
  rating: number
  review: string | null
  reviewerName: string | null
  createdAt: Date
  _count: CaregiverRatingCountAggregateOutputType | null
  _avg: CaregiverRatingAvgAggregateOutputType | null
  _sum: CaregiverRatingSumAggregateOutputType | null
  _min: CaregiverRatingMinAggregateOutputType | null
  _max: CaregiverRatingMaxAggregateOutputType | null
}

export type GetCaregiverRatingGroupByPayload<T extends CaregiverRatingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CaregiverRatingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CaregiverRatingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CaregiverRatingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CaregiverRatingGroupByOutputType[P]>
      }
    >
  >



export type CaregiverRatingWhereInput = {
  AND?: Prisma.CaregiverRatingWhereInput | Prisma.CaregiverRatingWhereInput[]
  OR?: Prisma.CaregiverRatingWhereInput[]
  NOT?: Prisma.CaregiverRatingWhereInput | Prisma.CaregiverRatingWhereInput[]
  id?: Prisma.StringFilter<"CaregiverRating"> | string
  caregiverId?: Prisma.StringFilter<"CaregiverRating"> | string
  rating?: Prisma.IntFilter<"CaregiverRating"> | number
  review?: Prisma.StringNullableFilter<"CaregiverRating"> | string | null
  reviewerName?: Prisma.StringNullableFilter<"CaregiverRating"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverRating"> | Date | string
  caregiver?: Prisma.XOR<Prisma.CaregiverScalarRelationFilter, Prisma.CaregiverWhereInput>
}

export type CaregiverRatingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  review?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewerName?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  caregiver?: Prisma.CaregiverOrderByWithRelationInput
}

export type CaregiverRatingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CaregiverRatingWhereInput | Prisma.CaregiverRatingWhereInput[]
  OR?: Prisma.CaregiverRatingWhereInput[]
  NOT?: Prisma.CaregiverRatingWhereInput | Prisma.CaregiverRatingWhereInput[]
  caregiverId?: Prisma.StringFilter<"CaregiverRating"> | string
  rating?: Prisma.IntFilter<"CaregiverRating"> | number
  review?: Prisma.StringNullableFilter<"CaregiverRating"> | string | null
  reviewerName?: Prisma.StringNullableFilter<"CaregiverRating"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverRating"> | Date | string
  caregiver?: Prisma.XOR<Prisma.CaregiverScalarRelationFilter, Prisma.CaregiverWhereInput>
}, "id">

export type CaregiverRatingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  review?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewerName?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CaregiverRatingCountOrderByAggregateInput
  _avg?: Prisma.CaregiverRatingAvgOrderByAggregateInput
  _max?: Prisma.CaregiverRatingMaxOrderByAggregateInput
  _min?: Prisma.CaregiverRatingMinOrderByAggregateInput
  _sum?: Prisma.CaregiverRatingSumOrderByAggregateInput
}

export type CaregiverRatingScalarWhereWithAggregatesInput = {
  AND?: Prisma.CaregiverRatingScalarWhereWithAggregatesInput | Prisma.CaregiverRatingScalarWhereWithAggregatesInput[]
  OR?: Prisma.CaregiverRatingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CaregiverRatingScalarWhereWithAggregatesInput | Prisma.CaregiverRatingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CaregiverRating"> | string
  caregiverId?: Prisma.StringWithAggregatesFilter<"CaregiverRating"> | string
  rating?: Prisma.IntWithAggregatesFilter<"CaregiverRating"> | number
  review?: Prisma.StringNullableWithAggregatesFilter<"CaregiverRating"> | string | null
  reviewerName?: Prisma.StringNullableWithAggregatesFilter<"CaregiverRating"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CaregiverRating"> | Date | string
}

export type CaregiverRatingCreateInput = {
  id?: string
  rating: number
  review?: string | null
  reviewerName?: string | null
  createdAt?: Date | string
  caregiver: Prisma.CaregiverCreateNestedOneWithoutRatingsInput
}

export type CaregiverRatingUncheckedCreateInput = {
  id?: string
  caregiverId: string
  rating: number
  review?: string | null
  reviewerName?: string | null
  createdAt?: Date | string
}

export type CaregiverRatingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  review?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  caregiver?: Prisma.CaregiverUpdateOneRequiredWithoutRatingsNestedInput
}

export type CaregiverRatingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  review?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverRatingCreateManyInput = {
  id?: string
  caregiverId: string
  rating: number
  review?: string | null
  reviewerName?: string | null
  createdAt?: Date | string
}

export type CaregiverRatingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  review?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverRatingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  review?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverRatingListRelationFilter = {
  every?: Prisma.CaregiverRatingWhereInput
  some?: Prisma.CaregiverRatingWhereInput
  none?: Prisma.CaregiverRatingWhereInput
}

export type CaregiverRatingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CaregiverRatingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  review?: Prisma.SortOrder
  reviewerName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CaregiverRatingAvgOrderByAggregateInput = {
  rating?: Prisma.SortOrder
}

export type CaregiverRatingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  review?: Prisma.SortOrder
  reviewerName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CaregiverRatingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  review?: Prisma.SortOrder
  reviewerName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CaregiverRatingSumOrderByAggregateInput = {
  rating?: Prisma.SortOrder
}

export type CaregiverRatingCreateNestedManyWithoutCaregiverInput = {
  create?: Prisma.XOR<Prisma.CaregiverRatingCreateWithoutCaregiverInput, Prisma.CaregiverRatingUncheckedCreateWithoutCaregiverInput> | Prisma.CaregiverRatingCreateWithoutCaregiverInput[] | Prisma.CaregiverRatingUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.CaregiverRatingCreateOrConnectWithoutCaregiverInput | Prisma.CaregiverRatingCreateOrConnectWithoutCaregiverInput[]
  createMany?: Prisma.CaregiverRatingCreateManyCaregiverInputEnvelope
  connect?: Prisma.CaregiverRatingWhereUniqueInput | Prisma.CaregiverRatingWhereUniqueInput[]
}

export type CaregiverRatingUncheckedCreateNestedManyWithoutCaregiverInput = {
  create?: Prisma.XOR<Prisma.CaregiverRatingCreateWithoutCaregiverInput, Prisma.CaregiverRatingUncheckedCreateWithoutCaregiverInput> | Prisma.CaregiverRatingCreateWithoutCaregiverInput[] | Prisma.CaregiverRatingUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.CaregiverRatingCreateOrConnectWithoutCaregiverInput | Prisma.CaregiverRatingCreateOrConnectWithoutCaregiverInput[]
  createMany?: Prisma.CaregiverRatingCreateManyCaregiverInputEnvelope
  connect?: Prisma.CaregiverRatingWhereUniqueInput | Prisma.CaregiverRatingWhereUniqueInput[]
}

export type CaregiverRatingUpdateManyWithoutCaregiverNestedInput = {
  create?: Prisma.XOR<Prisma.CaregiverRatingCreateWithoutCaregiverInput, Prisma.CaregiverRatingUncheckedCreateWithoutCaregiverInput> | Prisma.CaregiverRatingCreateWithoutCaregiverInput[] | Prisma.CaregiverRatingUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.CaregiverRatingCreateOrConnectWithoutCaregiverInput | Prisma.CaregiverRatingCreateOrConnectWithoutCaregiverInput[]
  upsert?: Prisma.CaregiverRatingUpsertWithWhereUniqueWithoutCaregiverInput | Prisma.CaregiverRatingUpsertWithWhereUniqueWithoutCaregiverInput[]
  createMany?: Prisma.CaregiverRatingCreateManyCaregiverInputEnvelope
  set?: Prisma.CaregiverRatingWhereUniqueInput | Prisma.CaregiverRatingWhereUniqueInput[]
  disconnect?: Prisma.CaregiverRatingWhereUniqueInput | Prisma.CaregiverRatingWhereUniqueInput[]
  delete?: Prisma.CaregiverRatingWhereUniqueInput | Prisma.CaregiverRatingWhereUniqueInput[]
  connect?: Prisma.CaregiverRatingWhereUniqueInput | Prisma.CaregiverRatingWhereUniqueInput[]
  update?: Prisma.CaregiverRatingUpdateWithWhereUniqueWithoutCaregiverInput | Prisma.CaregiverRatingUpdateWithWhereUniqueWithoutCaregiverInput[]
  updateMany?: Prisma.CaregiverRatingUpdateManyWithWhereWithoutCaregiverInput | Prisma.CaregiverRatingUpdateManyWithWhereWithoutCaregiverInput[]
  deleteMany?: Prisma.CaregiverRatingScalarWhereInput | Prisma.CaregiverRatingScalarWhereInput[]
}

export type CaregiverRatingUncheckedUpdateManyWithoutCaregiverNestedInput = {
  create?: Prisma.XOR<Prisma.CaregiverRatingCreateWithoutCaregiverInput, Prisma.CaregiverRatingUncheckedCreateWithoutCaregiverInput> | Prisma.CaregiverRatingCreateWithoutCaregiverInput[] | Prisma.CaregiverRatingUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.CaregiverRatingCreateOrConnectWithoutCaregiverInput | Prisma.CaregiverRatingCreateOrConnectWithoutCaregiverInput[]
  upsert?: Prisma.CaregiverRatingUpsertWithWhereUniqueWithoutCaregiverInput | Prisma.CaregiverRatingUpsertWithWhereUniqueWithoutCaregiverInput[]
  createMany?: Prisma.CaregiverRatingCreateManyCaregiverInputEnvelope
  set?: Prisma.CaregiverRatingWhereUniqueInput | Prisma.CaregiverRatingWhereUniqueInput[]
  disconnect?: Prisma.CaregiverRatingWhereUniqueInput | Prisma.CaregiverRatingWhereUniqueInput[]
  delete?: Prisma.CaregiverRatingWhereUniqueInput | Prisma.CaregiverRatingWhereUniqueInput[]
  connect?: Prisma.CaregiverRatingWhereUniqueInput | Prisma.CaregiverRatingWhereUniqueInput[]
  update?: Prisma.CaregiverRatingUpdateWithWhereUniqueWithoutCaregiverInput | Prisma.CaregiverRatingUpdateWithWhereUniqueWithoutCaregiverInput[]
  updateMany?: Prisma.CaregiverRatingUpdateManyWithWhereWithoutCaregiverInput | Prisma.CaregiverRatingUpdateManyWithWhereWithoutCaregiverInput[]
  deleteMany?: Prisma.CaregiverRatingScalarWhereInput | Prisma.CaregiverRatingScalarWhereInput[]
}

export type CaregiverRatingCreateWithoutCaregiverInput = {
  id?: string
  rating: number
  review?: string | null
  reviewerName?: string | null
  createdAt?: Date | string
}

export type CaregiverRatingUncheckedCreateWithoutCaregiverInput = {
  id?: string
  rating: number
  review?: string | null
  reviewerName?: string | null
  createdAt?: Date | string
}

export type CaregiverRatingCreateOrConnectWithoutCaregiverInput = {
  where: Prisma.CaregiverRatingWhereUniqueInput
  create: Prisma.XOR<Prisma.CaregiverRatingCreateWithoutCaregiverInput, Prisma.CaregiverRatingUncheckedCreateWithoutCaregiverInput>
}

export type CaregiverRatingCreateManyCaregiverInputEnvelope = {
  data: Prisma.CaregiverRatingCreateManyCaregiverInput | Prisma.CaregiverRatingCreateManyCaregiverInput[]
  skipDuplicates?: boolean
}

export type CaregiverRatingUpsertWithWhereUniqueWithoutCaregiverInput = {
  where: Prisma.CaregiverRatingWhereUniqueInput
  update: Prisma.XOR<Prisma.CaregiverRatingUpdateWithoutCaregiverInput, Prisma.CaregiverRatingUncheckedUpdateWithoutCaregiverInput>
  create: Prisma.XOR<Prisma.CaregiverRatingCreateWithoutCaregiverInput, Prisma.CaregiverRatingUncheckedCreateWithoutCaregiverInput>
}

export type CaregiverRatingUpdateWithWhereUniqueWithoutCaregiverInput = {
  where: Prisma.CaregiverRatingWhereUniqueInput
  data: Prisma.XOR<Prisma.CaregiverRatingUpdateWithoutCaregiverInput, Prisma.CaregiverRatingUncheckedUpdateWithoutCaregiverInput>
}

export type CaregiverRatingUpdateManyWithWhereWithoutCaregiverInput = {
  where: Prisma.CaregiverRatingScalarWhereInput
  data: Prisma.XOR<Prisma.CaregiverRatingUpdateManyMutationInput, Prisma.CaregiverRatingUncheckedUpdateManyWithoutCaregiverInput>
}

export type CaregiverRatingScalarWhereInput = {
  AND?: Prisma.CaregiverRatingScalarWhereInput | Prisma.CaregiverRatingScalarWhereInput[]
  OR?: Prisma.CaregiverRatingScalarWhereInput[]
  NOT?: Prisma.CaregiverRatingScalarWhereInput | Prisma.CaregiverRatingScalarWhereInput[]
  id?: Prisma.StringFilter<"CaregiverRating"> | string
  caregiverId?: Prisma.StringFilter<"CaregiverRating"> | string
  rating?: Prisma.IntFilter<"CaregiverRating"> | number
  review?: Prisma.StringNullableFilter<"CaregiverRating"> | string | null
  reviewerName?: Prisma.StringNullableFilter<"CaregiverRating"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverRating"> | Date | string
}

export type CaregiverRatingCreateManyCaregiverInput = {
  id?: string
  rating: number
  review?: string | null
  reviewerName?: string | null
  createdAt?: Date | string
}

export type CaregiverRatingUpdateWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  review?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverRatingUncheckedUpdateWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  review?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverRatingUncheckedUpdateManyWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  review?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CaregiverRatingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caregiverId?: boolean
  rating?: boolean
  review?: boolean
  reviewerName?: boolean
  createdAt?: boolean
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverRating"]>

export type CaregiverRatingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caregiverId?: boolean
  rating?: boolean
  review?: boolean
  reviewerName?: boolean
  createdAt?: boolean
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverRating"]>

export type CaregiverRatingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caregiverId?: boolean
  rating?: boolean
  review?: boolean
  reviewerName?: boolean
  createdAt?: boolean
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverRating"]>

export type CaregiverRatingSelectScalar = {
  id?: boolean
  caregiverId?: boolean
  rating?: boolean
  review?: boolean
  reviewerName?: boolean
  createdAt?: boolean
}

export type CaregiverRatingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "caregiverId" | "rating" | "review" | "reviewerName" | "createdAt", ExtArgs["result"]["caregiverRating"]>
export type CaregiverRatingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}
export type CaregiverRatingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}
export type CaregiverRatingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}

export type $CaregiverRatingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CaregiverRating"
  objects: {
    caregiver: Prisma.$CaregiverPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    caregiverId: string
    rating: number
    review: string | null
    reviewerName: string | null
    createdAt: Date
  }, ExtArgs["result"]["caregiverRating"]>
  composites: {}
}

export type CaregiverRatingGetPayload<S extends boolean | null | undefined | CaregiverRatingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload, S>

export type CaregiverRatingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CaregiverRatingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CaregiverRatingCountAggregateInputType | true
  }

export interface CaregiverRatingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CaregiverRating'], meta: { name: 'CaregiverRating' } }
  /**
   * Find zero or one CaregiverRating that matches the filter.
   * @param {CaregiverRatingFindUniqueArgs} args - Arguments to find a CaregiverRating
   * @example
   * // Get one CaregiverRating
   * const caregiverRating = await prisma.caregiverRating.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CaregiverRatingFindUniqueArgs>(args: Prisma.SelectSubset<T, CaregiverRatingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CaregiverRatingClient<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CaregiverRating that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CaregiverRatingFindUniqueOrThrowArgs} args - Arguments to find a CaregiverRating
   * @example
   * // Get one CaregiverRating
   * const caregiverRating = await prisma.caregiverRating.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CaregiverRatingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CaregiverRatingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CaregiverRatingClient<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CaregiverRating that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverRatingFindFirstArgs} args - Arguments to find a CaregiverRating
   * @example
   * // Get one CaregiverRating
   * const caregiverRating = await prisma.caregiverRating.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CaregiverRatingFindFirstArgs>(args?: Prisma.SelectSubset<T, CaregiverRatingFindFirstArgs<ExtArgs>>): Prisma.Prisma__CaregiverRatingClient<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CaregiverRating that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverRatingFindFirstOrThrowArgs} args - Arguments to find a CaregiverRating
   * @example
   * // Get one CaregiverRating
   * const caregiverRating = await prisma.caregiverRating.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CaregiverRatingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CaregiverRatingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CaregiverRatingClient<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CaregiverRatings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverRatingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CaregiverRatings
   * const caregiverRatings = await prisma.caregiverRating.findMany()
   * 
   * // Get first 10 CaregiverRatings
   * const caregiverRatings = await prisma.caregiverRating.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const caregiverRatingWithIdOnly = await prisma.caregiverRating.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CaregiverRatingFindManyArgs>(args?: Prisma.SelectSubset<T, CaregiverRatingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CaregiverRating.
   * @param {CaregiverRatingCreateArgs} args - Arguments to create a CaregiverRating.
   * @example
   * // Create one CaregiverRating
   * const CaregiverRating = await prisma.caregiverRating.create({
   *   data: {
   *     // ... data to create a CaregiverRating
   *   }
   * })
   * 
   */
  create<T extends CaregiverRatingCreateArgs>(args: Prisma.SelectSubset<T, CaregiverRatingCreateArgs<ExtArgs>>): Prisma.Prisma__CaregiverRatingClient<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CaregiverRatings.
   * @param {CaregiverRatingCreateManyArgs} args - Arguments to create many CaregiverRatings.
   * @example
   * // Create many CaregiverRatings
   * const caregiverRating = await prisma.caregiverRating.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CaregiverRatingCreateManyArgs>(args?: Prisma.SelectSubset<T, CaregiverRatingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CaregiverRatings and returns the data saved in the database.
   * @param {CaregiverRatingCreateManyAndReturnArgs} args - Arguments to create many CaregiverRatings.
   * @example
   * // Create many CaregiverRatings
   * const caregiverRating = await prisma.caregiverRating.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CaregiverRatings and only return the `id`
   * const caregiverRatingWithIdOnly = await prisma.caregiverRating.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CaregiverRatingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CaregiverRatingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CaregiverRating.
   * @param {CaregiverRatingDeleteArgs} args - Arguments to delete one CaregiverRating.
   * @example
   * // Delete one CaregiverRating
   * const CaregiverRating = await prisma.caregiverRating.delete({
   *   where: {
   *     // ... filter to delete one CaregiverRating
   *   }
   * })
   * 
   */
  delete<T extends CaregiverRatingDeleteArgs>(args: Prisma.SelectSubset<T, CaregiverRatingDeleteArgs<ExtArgs>>): Prisma.Prisma__CaregiverRatingClient<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CaregiverRating.
   * @param {CaregiverRatingUpdateArgs} args - Arguments to update one CaregiverRating.
   * @example
   * // Update one CaregiverRating
   * const caregiverRating = await prisma.caregiverRating.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CaregiverRatingUpdateArgs>(args: Prisma.SelectSubset<T, CaregiverRatingUpdateArgs<ExtArgs>>): Prisma.Prisma__CaregiverRatingClient<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CaregiverRatings.
   * @param {CaregiverRatingDeleteManyArgs} args - Arguments to filter CaregiverRatings to delete.
   * @example
   * // Delete a few CaregiverRatings
   * const { count } = await prisma.caregiverRating.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CaregiverRatingDeleteManyArgs>(args?: Prisma.SelectSubset<T, CaregiverRatingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CaregiverRatings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverRatingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CaregiverRatings
   * const caregiverRating = await prisma.caregiverRating.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CaregiverRatingUpdateManyArgs>(args: Prisma.SelectSubset<T, CaregiverRatingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CaregiverRatings and returns the data updated in the database.
   * @param {CaregiverRatingUpdateManyAndReturnArgs} args - Arguments to update many CaregiverRatings.
   * @example
   * // Update many CaregiverRatings
   * const caregiverRating = await prisma.caregiverRating.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CaregiverRatings and only return the `id`
   * const caregiverRatingWithIdOnly = await prisma.caregiverRating.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CaregiverRatingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CaregiverRatingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CaregiverRating.
   * @param {CaregiverRatingUpsertArgs} args - Arguments to update or create a CaregiverRating.
   * @example
   * // Update or create a CaregiverRating
   * const caregiverRating = await prisma.caregiverRating.upsert({
   *   create: {
   *     // ... data to create a CaregiverRating
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CaregiverRating we want to update
   *   }
   * })
   */
  upsert<T extends CaregiverRatingUpsertArgs>(args: Prisma.SelectSubset<T, CaregiverRatingUpsertArgs<ExtArgs>>): Prisma.Prisma__CaregiverRatingClient<runtime.Types.Result.GetResult<Prisma.$CaregiverRatingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CaregiverRatings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverRatingCountArgs} args - Arguments to filter CaregiverRatings to count.
   * @example
   * // Count the number of CaregiverRatings
   * const count = await prisma.caregiverRating.count({
   *   where: {
   *     // ... the filter for the CaregiverRatings we want to count
   *   }
   * })
  **/
  count<T extends CaregiverRatingCountArgs>(
    args?: Prisma.Subset<T, CaregiverRatingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CaregiverRatingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CaregiverRating.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverRatingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CaregiverRatingAggregateArgs>(args: Prisma.Subset<T, CaregiverRatingAggregateArgs>): Prisma.PrismaPromise<GetCaregiverRatingAggregateType<T>>

  /**
   * Group by CaregiverRating.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverRatingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CaregiverRatingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CaregiverRatingGroupByArgs['orderBy'] }
      : { orderBy?: CaregiverRatingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CaregiverRatingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCaregiverRatingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CaregiverRating model
 */
readonly fields: CaregiverRatingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CaregiverRating.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CaregiverRatingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  caregiver<T extends Prisma.CaregiverDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CaregiverDefaultArgs<ExtArgs>>): Prisma.Prisma__CaregiverClient<runtime.Types.Result.GetResult<Prisma.$CaregiverPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CaregiverRating model
 */
export interface CaregiverRatingFieldRefs {
  readonly id: Prisma.FieldRef<"CaregiverRating", 'String'>
  readonly caregiverId: Prisma.FieldRef<"CaregiverRating", 'String'>
  readonly rating: Prisma.FieldRef<"CaregiverRating", 'Int'>
  readonly review: Prisma.FieldRef<"CaregiverRating", 'String'>
  readonly reviewerName: Prisma.FieldRef<"CaregiverRating", 'String'>
  readonly createdAt: Prisma.FieldRef<"CaregiverRating", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CaregiverRating findUnique
 */
export type CaregiverRatingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverRating to fetch.
   */
  where: Prisma.CaregiverRatingWhereUniqueInput
}

/**
 * CaregiverRating findUniqueOrThrow
 */
export type CaregiverRatingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverRating to fetch.
   */
  where: Prisma.CaregiverRatingWhereUniqueInput
}

/**
 * CaregiverRating findFirst
 */
export type CaregiverRatingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverRating to fetch.
   */
  where?: Prisma.CaregiverRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverRatings to fetch.
   */
  orderBy?: Prisma.CaregiverRatingOrderByWithRelationInput | Prisma.CaregiverRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CaregiverRatings.
   */
  cursor?: Prisma.CaregiverRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverRatings.
   */
  distinct?: Prisma.CaregiverRatingScalarFieldEnum | Prisma.CaregiverRatingScalarFieldEnum[]
}

/**
 * CaregiverRating findFirstOrThrow
 */
export type CaregiverRatingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverRating to fetch.
   */
  where?: Prisma.CaregiverRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverRatings to fetch.
   */
  orderBy?: Prisma.CaregiverRatingOrderByWithRelationInput | Prisma.CaregiverRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CaregiverRatings.
   */
  cursor?: Prisma.CaregiverRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverRatings.
   */
  distinct?: Prisma.CaregiverRatingScalarFieldEnum | Prisma.CaregiverRatingScalarFieldEnum[]
}

/**
 * CaregiverRating findMany
 */
export type CaregiverRatingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverRatings to fetch.
   */
  where?: Prisma.CaregiverRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverRatings to fetch.
   */
  orderBy?: Prisma.CaregiverRatingOrderByWithRelationInput | Prisma.CaregiverRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CaregiverRatings.
   */
  cursor?: Prisma.CaregiverRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverRatings.
   */
  distinct?: Prisma.CaregiverRatingScalarFieldEnum | Prisma.CaregiverRatingScalarFieldEnum[]
}

/**
 * CaregiverRating create
 */
export type CaregiverRatingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingInclude<ExtArgs> | null
  /**
   * The data needed to create a CaregiverRating.
   */
  data: Prisma.XOR<Prisma.CaregiverRatingCreateInput, Prisma.CaregiverRatingUncheckedCreateInput>
}

/**
 * CaregiverRating createMany
 */
export type CaregiverRatingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CaregiverRatings.
   */
  data: Prisma.CaregiverRatingCreateManyInput | Prisma.CaregiverRatingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CaregiverRating createManyAndReturn
 */
export type CaregiverRatingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * The data used to create many CaregiverRatings.
   */
  data: Prisma.CaregiverRatingCreateManyInput | Prisma.CaregiverRatingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CaregiverRating update
 */
export type CaregiverRatingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingInclude<ExtArgs> | null
  /**
   * The data needed to update a CaregiverRating.
   */
  data: Prisma.XOR<Prisma.CaregiverRatingUpdateInput, Prisma.CaregiverRatingUncheckedUpdateInput>
  /**
   * Choose, which CaregiverRating to update.
   */
  where: Prisma.CaregiverRatingWhereUniqueInput
}

/**
 * CaregiverRating updateMany
 */
export type CaregiverRatingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CaregiverRatings.
   */
  data: Prisma.XOR<Prisma.CaregiverRatingUpdateManyMutationInput, Prisma.CaregiverRatingUncheckedUpdateManyInput>
  /**
   * Filter which CaregiverRatings to update
   */
  where?: Prisma.CaregiverRatingWhereInput
  /**
   * Limit how many CaregiverRatings to update.
   */
  limit?: number
}

/**
 * CaregiverRating updateManyAndReturn
 */
export type CaregiverRatingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * The data used to update CaregiverRatings.
   */
  data: Prisma.XOR<Prisma.CaregiverRatingUpdateManyMutationInput, Prisma.CaregiverRatingUncheckedUpdateManyInput>
  /**
   * Filter which CaregiverRatings to update
   */
  where?: Prisma.CaregiverRatingWhereInput
  /**
   * Limit how many CaregiverRatings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CaregiverRating upsert
 */
export type CaregiverRatingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingInclude<ExtArgs> | null
  /**
   * The filter to search for the CaregiverRating to update in case it exists.
   */
  where: Prisma.CaregiverRatingWhereUniqueInput
  /**
   * In case the CaregiverRating found by the `where` argument doesn't exist, create a new CaregiverRating with this data.
   */
  create: Prisma.XOR<Prisma.CaregiverRatingCreateInput, Prisma.CaregiverRatingUncheckedCreateInput>
  /**
   * In case the CaregiverRating was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CaregiverRatingUpdateInput, Prisma.CaregiverRatingUncheckedUpdateInput>
}

/**
 * CaregiverRating delete
 */
export type CaregiverRatingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingInclude<ExtArgs> | null
  /**
   * Filter which CaregiverRating to delete.
   */
  where: Prisma.CaregiverRatingWhereUniqueInput
}

/**
 * CaregiverRating deleteMany
 */
export type CaregiverRatingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CaregiverRatings to delete
   */
  where?: Prisma.CaregiverRatingWhereInput
  /**
   * Limit how many CaregiverRatings to delete.
   */
  limit?: number
}

/**
 * CaregiverRating without action
 */
export type CaregiverRatingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverRating
   */
  select?: Prisma.CaregiverRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverRating
   */
  omit?: Prisma.CaregiverRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverRatingInclude<ExtArgs> | null
}
