
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CaregiverReference` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CaregiverReference
 * 
 */
export type CaregiverReferenceModel = runtime.Types.Result.DefaultSelection<Prisma.$CaregiverReferencePayload>

export type AggregateCaregiverReference = {
  _count: CaregiverReferenceCountAggregateOutputType | null
  _min: CaregiverReferenceMinAggregateOutputType | null
  _max: CaregiverReferenceMaxAggregateOutputType | null
}

export type CaregiverReferenceMinAggregateOutputType = {
  id: string | null
  caregiverId: string | null
  name: string | null
  relationship: string | null
  phone: string | null
  email: string | null
  notes: string | null
  createdAt: Date | null
}

export type CaregiverReferenceMaxAggregateOutputType = {
  id: string | null
  caregiverId: string | null
  name: string | null
  relationship: string | null
  phone: string | null
  email: string | null
  notes: string | null
  createdAt: Date | null
}

export type CaregiverReferenceCountAggregateOutputType = {
  id: number
  caregiverId: number
  name: number
  relationship: number
  phone: number
  email: number
  notes: number
  createdAt: number
  _all: number
}


export type CaregiverReferenceMinAggregateInputType = {
  id?: true
  caregiverId?: true
  name?: true
  relationship?: true
  phone?: true
  email?: true
  notes?: true
  createdAt?: true
}

export type CaregiverReferenceMaxAggregateInputType = {
  id?: true
  caregiverId?: true
  name?: true
  relationship?: true
  phone?: true
  email?: true
  notes?: true
  createdAt?: true
}

export type CaregiverReferenceCountAggregateInputType = {
  id?: true
  caregiverId?: true
  name?: true
  relationship?: true
  phone?: true
  email?: true
  notes?: true
  createdAt?: true
  _all?: true
}

export type CaregiverReferenceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CaregiverReference to aggregate.
   */
  where?: Prisma.CaregiverReferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverReferences to fetch.
   */
  orderBy?: Prisma.CaregiverReferenceOrderByWithRelationInput | Prisma.CaregiverReferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CaregiverReferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverReferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverReferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CaregiverReferences
  **/
  _count?: true | CaregiverReferenceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CaregiverReferenceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CaregiverReferenceMaxAggregateInputType
}

export type GetCaregiverReferenceAggregateType<T extends CaregiverReferenceAggregateArgs> = {
      [P in keyof T & keyof AggregateCaregiverReference]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCaregiverReference[P]>
    : Prisma.GetScalarType<T[P], AggregateCaregiverReference[P]>
}




export type CaregiverReferenceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CaregiverReferenceWhereInput
  orderBy?: Prisma.CaregiverReferenceOrderByWithAggregationInput | Prisma.CaregiverReferenceOrderByWithAggregationInput[]
  by: Prisma.CaregiverReferenceScalarFieldEnum[] | Prisma.CaregiverReferenceScalarFieldEnum
  having?: Prisma.CaregiverReferenceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CaregiverReferenceCountAggregateInputType | true
  _min?: CaregiverReferenceMinAggregateInputType
  _max?: CaregiverReferenceMaxAggregateInputType
}

export type CaregiverReferenceGroupByOutputType = {
  id: string
  caregiverId: string
  name: string
  relationship: string
  phone: string
  email: string | null
  notes: string | null
  createdAt: Date
  _count: CaregiverReferenceCountAggregateOutputType | null
  _min: CaregiverReferenceMinAggregateOutputType | null
  _max: CaregiverReferenceMaxAggregateOutputType | null
}

export type GetCaregiverReferenceGroupByPayload<T extends CaregiverReferenceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CaregiverReferenceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CaregiverReferenceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CaregiverReferenceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CaregiverReferenceGroupByOutputType[P]>
      }
    >
  >



export type CaregiverReferenceWhereInput = {
  AND?: Prisma.CaregiverReferenceWhereInput | Prisma.CaregiverReferenceWhereInput[]
  OR?: Prisma.CaregiverReferenceWhereInput[]
  NOT?: Prisma.CaregiverReferenceWhereInput | Prisma.CaregiverReferenceWhereInput[]
  id?: Prisma.StringFilter<"CaregiverReference"> | string
  caregiverId?: Prisma.StringFilter<"CaregiverReference"> | string
  name?: Prisma.StringFilter<"CaregiverReference"> | string
  relationship?: Prisma.StringFilter<"CaregiverReference"> | string
  phone?: Prisma.StringFilter<"CaregiverReference"> | string
  email?: Prisma.StringNullableFilter<"CaregiverReference"> | string | null
  notes?: Prisma.StringNullableFilter<"CaregiverReference"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverReference"> | Date | string
  caregiver?: Prisma.XOR<Prisma.CaregiverScalarRelationFilter, Prisma.CaregiverWhereInput>
}

export type CaregiverReferenceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  relationship?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  caregiver?: Prisma.CaregiverOrderByWithRelationInput
}

export type CaregiverReferenceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CaregiverReferenceWhereInput | Prisma.CaregiverReferenceWhereInput[]
  OR?: Prisma.CaregiverReferenceWhereInput[]
  NOT?: Prisma.CaregiverReferenceWhereInput | Prisma.CaregiverReferenceWhereInput[]
  caregiverId?: Prisma.StringFilter<"CaregiverReference"> | string
  name?: Prisma.StringFilter<"CaregiverReference"> | string
  relationship?: Prisma.StringFilter<"CaregiverReference"> | string
  phone?: Prisma.StringFilter<"CaregiverReference"> | string
  email?: Prisma.StringNullableFilter<"CaregiverReference"> | string | null
  notes?: Prisma.StringNullableFilter<"CaregiverReference"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverReference"> | Date | string
  caregiver?: Prisma.XOR<Prisma.CaregiverScalarRelationFilter, Prisma.CaregiverWhereInput>
}, "id">

export type CaregiverReferenceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  relationship?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CaregiverReferenceCountOrderByAggregateInput
  _max?: Prisma.CaregiverReferenceMaxOrderByAggregateInput
  _min?: Prisma.CaregiverReferenceMinOrderByAggregateInput
}

export type CaregiverReferenceScalarWhereWithAggregatesInput = {
  AND?: Prisma.CaregiverReferenceScalarWhereWithAggregatesInput | Prisma.CaregiverReferenceScalarWhereWithAggregatesInput[]
  OR?: Prisma.CaregiverReferenceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CaregiverReferenceScalarWhereWithAggregatesInput | Prisma.CaregiverReferenceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CaregiverReference"> | string
  caregiverId?: Prisma.StringWithAggregatesFilter<"CaregiverReference"> | string
  name?: Prisma.StringWithAggregatesFilter<"CaregiverReference"> | string
  relationship?: Prisma.StringWithAggregatesFilter<"CaregiverReference"> | string
  phone?: Prisma.StringWithAggregatesFilter<"CaregiverReference"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"CaregiverReference"> | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"CaregiverReference"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CaregiverReference"> | Date | string
}

export type CaregiverReferenceCreateInput = {
  id?: string
  name: string
  relationship: string
  phone: string
  email?: string | null
  notes?: string | null
  createdAt?: Date | string
  caregiver: Prisma.CaregiverCreateNestedOneWithoutReferencesInput
}

export type CaregiverReferenceUncheckedCreateInput = {
  id?: string
  caregiverId: string
  name: string
  relationship: string
  phone: string
  email?: string | null
  notes?: string | null
  createdAt?: Date | string
}

export type CaregiverReferenceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  relationship?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  caregiver?: Prisma.CaregiverUpdateOneRequiredWithoutReferencesNestedInput
}

export type CaregiverReferenceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  relationship?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverReferenceCreateManyInput = {
  id?: string
  caregiverId: string
  name: string
  relationship: string
  phone: string
  email?: string | null
  notes?: string | null
  createdAt?: Date | string
}

export type CaregiverReferenceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  relationship?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverReferenceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caregiverId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  relationship?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverReferenceListRelationFilter = {
  every?: Prisma.CaregiverReferenceWhereInput
  some?: Prisma.CaregiverReferenceWhereInput
  none?: Prisma.CaregiverReferenceWhereInput
}

export type CaregiverReferenceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CaregiverReferenceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  relationship?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CaregiverReferenceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  relationship?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CaregiverReferenceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caregiverId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  relationship?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CaregiverReferenceCreateNestedManyWithoutCaregiverInput = {
  create?: Prisma.XOR<Prisma.CaregiverReferenceCreateWithoutCaregiverInput, Prisma.CaregiverReferenceUncheckedCreateWithoutCaregiverInput> | Prisma.CaregiverReferenceCreateWithoutCaregiverInput[] | Prisma.CaregiverReferenceUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.CaregiverReferenceCreateOrConnectWithoutCaregiverInput | Prisma.CaregiverReferenceCreateOrConnectWithoutCaregiverInput[]
  createMany?: Prisma.CaregiverReferenceCreateManyCaregiverInputEnvelope
  connect?: Prisma.CaregiverReferenceWhereUniqueInput | Prisma.CaregiverReferenceWhereUniqueInput[]
}

export type CaregiverReferenceUncheckedCreateNestedManyWithoutCaregiverInput = {
  create?: Prisma.XOR<Prisma.CaregiverReferenceCreateWithoutCaregiverInput, Prisma.CaregiverReferenceUncheckedCreateWithoutCaregiverInput> | Prisma.CaregiverReferenceCreateWithoutCaregiverInput[] | Prisma.CaregiverReferenceUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.CaregiverReferenceCreateOrConnectWithoutCaregiverInput | Prisma.CaregiverReferenceCreateOrConnectWithoutCaregiverInput[]
  createMany?: Prisma.CaregiverReferenceCreateManyCaregiverInputEnvelope
  connect?: Prisma.CaregiverReferenceWhereUniqueInput | Prisma.CaregiverReferenceWhereUniqueInput[]
}

export type CaregiverReferenceUpdateManyWithoutCaregiverNestedInput = {
  create?: Prisma.XOR<Prisma.CaregiverReferenceCreateWithoutCaregiverInput, Prisma.CaregiverReferenceUncheckedCreateWithoutCaregiverInput> | Prisma.CaregiverReferenceCreateWithoutCaregiverInput[] | Prisma.CaregiverReferenceUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.CaregiverReferenceCreateOrConnectWithoutCaregiverInput | Prisma.CaregiverReferenceCreateOrConnectWithoutCaregiverInput[]
  upsert?: Prisma.CaregiverReferenceUpsertWithWhereUniqueWithoutCaregiverInput | Prisma.CaregiverReferenceUpsertWithWhereUniqueWithoutCaregiverInput[]
  createMany?: Prisma.CaregiverReferenceCreateManyCaregiverInputEnvelope
  set?: Prisma.CaregiverReferenceWhereUniqueInput | Prisma.CaregiverReferenceWhereUniqueInput[]
  disconnect?: Prisma.CaregiverReferenceWhereUniqueInput | Prisma.CaregiverReferenceWhereUniqueInput[]
  delete?: Prisma.CaregiverReferenceWhereUniqueInput | Prisma.CaregiverReferenceWhereUniqueInput[]
  connect?: Prisma.CaregiverReferenceWhereUniqueInput | Prisma.CaregiverReferenceWhereUniqueInput[]
  update?: Prisma.CaregiverReferenceUpdateWithWhereUniqueWithoutCaregiverInput | Prisma.CaregiverReferenceUpdateWithWhereUniqueWithoutCaregiverInput[]
  updateMany?: Prisma.CaregiverReferenceUpdateManyWithWhereWithoutCaregiverInput | Prisma.CaregiverReferenceUpdateManyWithWhereWithoutCaregiverInput[]
  deleteMany?: Prisma.CaregiverReferenceScalarWhereInput | Prisma.CaregiverReferenceScalarWhereInput[]
}

export type CaregiverReferenceUncheckedUpdateManyWithoutCaregiverNestedInput = {
  create?: Prisma.XOR<Prisma.CaregiverReferenceCreateWithoutCaregiverInput, Prisma.CaregiverReferenceUncheckedCreateWithoutCaregiverInput> | Prisma.CaregiverReferenceCreateWithoutCaregiverInput[] | Prisma.CaregiverReferenceUncheckedCreateWithoutCaregiverInput[]
  connectOrCreate?: Prisma.CaregiverReferenceCreateOrConnectWithoutCaregiverInput | Prisma.CaregiverReferenceCreateOrConnectWithoutCaregiverInput[]
  upsert?: Prisma.CaregiverReferenceUpsertWithWhereUniqueWithoutCaregiverInput | Prisma.CaregiverReferenceUpsertWithWhereUniqueWithoutCaregiverInput[]
  createMany?: Prisma.CaregiverReferenceCreateManyCaregiverInputEnvelope
  set?: Prisma.CaregiverReferenceWhereUniqueInput | Prisma.CaregiverReferenceWhereUniqueInput[]
  disconnect?: Prisma.CaregiverReferenceWhereUniqueInput | Prisma.CaregiverReferenceWhereUniqueInput[]
  delete?: Prisma.CaregiverReferenceWhereUniqueInput | Prisma.CaregiverReferenceWhereUniqueInput[]
  connect?: Prisma.CaregiverReferenceWhereUniqueInput | Prisma.CaregiverReferenceWhereUniqueInput[]
  update?: Prisma.CaregiverReferenceUpdateWithWhereUniqueWithoutCaregiverInput | Prisma.CaregiverReferenceUpdateWithWhereUniqueWithoutCaregiverInput[]
  updateMany?: Prisma.CaregiverReferenceUpdateManyWithWhereWithoutCaregiverInput | Prisma.CaregiverReferenceUpdateManyWithWhereWithoutCaregiverInput[]
  deleteMany?: Prisma.CaregiverReferenceScalarWhereInput | Prisma.CaregiverReferenceScalarWhereInput[]
}

export type CaregiverReferenceCreateWithoutCaregiverInput = {
  id?: string
  name: string
  relationship: string
  phone: string
  email?: string | null
  notes?: string | null
  createdAt?: Date | string
}

export type CaregiverReferenceUncheckedCreateWithoutCaregiverInput = {
  id?: string
  name: string
  relationship: string
  phone: string
  email?: string | null
  notes?: string | null
  createdAt?: Date | string
}

export type CaregiverReferenceCreateOrConnectWithoutCaregiverInput = {
  where: Prisma.CaregiverReferenceWhereUniqueInput
  create: Prisma.XOR<Prisma.CaregiverReferenceCreateWithoutCaregiverInput, Prisma.CaregiverReferenceUncheckedCreateWithoutCaregiverInput>
}

export type CaregiverReferenceCreateManyCaregiverInputEnvelope = {
  data: Prisma.CaregiverReferenceCreateManyCaregiverInput | Prisma.CaregiverReferenceCreateManyCaregiverInput[]
  skipDuplicates?: boolean
}

export type CaregiverReferenceUpsertWithWhereUniqueWithoutCaregiverInput = {
  where: Prisma.CaregiverReferenceWhereUniqueInput
  update: Prisma.XOR<Prisma.CaregiverReferenceUpdateWithoutCaregiverInput, Prisma.CaregiverReferenceUncheckedUpdateWithoutCaregiverInput>
  create: Prisma.XOR<Prisma.CaregiverReferenceCreateWithoutCaregiverInput, Prisma.CaregiverReferenceUncheckedCreateWithoutCaregiverInput>
}

export type CaregiverReferenceUpdateWithWhereUniqueWithoutCaregiverInput = {
  where: Prisma.CaregiverReferenceWhereUniqueInput
  data: Prisma.XOR<Prisma.CaregiverReferenceUpdateWithoutCaregiverInput, Prisma.CaregiverReferenceUncheckedUpdateWithoutCaregiverInput>
}

export type CaregiverReferenceUpdateManyWithWhereWithoutCaregiverInput = {
  where: Prisma.CaregiverReferenceScalarWhereInput
  data: Prisma.XOR<Prisma.CaregiverReferenceUpdateManyMutationInput, Prisma.CaregiverReferenceUncheckedUpdateManyWithoutCaregiverInput>
}

export type CaregiverReferenceScalarWhereInput = {
  AND?: Prisma.CaregiverReferenceScalarWhereInput | Prisma.CaregiverReferenceScalarWhereInput[]
  OR?: Prisma.CaregiverReferenceScalarWhereInput[]
  NOT?: Prisma.CaregiverReferenceScalarWhereInput | Prisma.CaregiverReferenceScalarWhereInput[]
  id?: Prisma.StringFilter<"CaregiverReference"> | string
  caregiverId?: Prisma.StringFilter<"CaregiverReference"> | string
  name?: Prisma.StringFilter<"CaregiverReference"> | string
  relationship?: Prisma.StringFilter<"CaregiverReference"> | string
  phone?: Prisma.StringFilter<"CaregiverReference"> | string
  email?: Prisma.StringNullableFilter<"CaregiverReference"> | string | null
  notes?: Prisma.StringNullableFilter<"CaregiverReference"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverReference"> | Date | string
}

export type CaregiverReferenceCreateManyCaregiverInput = {
  id?: string
  name: string
  relationship: string
  phone: string
  email?: string | null
  notes?: string | null
  createdAt?: Date | string
}

export type CaregiverReferenceUpdateWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  relationship?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverReferenceUncheckedUpdateWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  relationship?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverReferenceUncheckedUpdateManyWithoutCaregiverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  relationship?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CaregiverReferenceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caregiverId?: boolean
  name?: boolean
  relationship?: boolean
  phone?: boolean
  email?: boolean
  notes?: boolean
  createdAt?: boolean
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverReference"]>

export type CaregiverReferenceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caregiverId?: boolean
  name?: boolean
  relationship?: boolean
  phone?: boolean
  email?: boolean
  notes?: boolean
  createdAt?: boolean
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverReference"]>

export type CaregiverReferenceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caregiverId?: boolean
  name?: boolean
  relationship?: boolean
  phone?: boolean
  email?: boolean
  notes?: boolean
  createdAt?: boolean
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverReference"]>

export type CaregiverReferenceSelectScalar = {
  id?: boolean
  caregiverId?: boolean
  name?: boolean
  relationship?: boolean
  phone?: boolean
  email?: boolean
  notes?: boolean
  createdAt?: boolean
}

export type CaregiverReferenceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "caregiverId" | "name" | "relationship" | "phone" | "email" | "notes" | "createdAt", ExtArgs["result"]["caregiverReference"]>
export type CaregiverReferenceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}
export type CaregiverReferenceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}
export type CaregiverReferenceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caregiver?: boolean | Prisma.CaregiverDefaultArgs<ExtArgs>
}

export type $CaregiverReferencePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CaregiverReference"
  objects: {
    caregiver: Prisma.$CaregiverPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    caregiverId: string
    name: string
    relationship: string
    phone: string
    email: string | null
    notes: string | null
    createdAt: Date
  }, ExtArgs["result"]["caregiverReference"]>
  composites: {}
}

export type CaregiverReferenceGetPayload<S extends boolean | null | undefined | CaregiverReferenceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload, S>

export type CaregiverReferenceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CaregiverReferenceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CaregiverReferenceCountAggregateInputType | true
  }

export interface CaregiverReferenceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CaregiverReference'], meta: { name: 'CaregiverReference' } }
  /**
   * Find zero or one CaregiverReference that matches the filter.
   * @param {CaregiverReferenceFindUniqueArgs} args - Arguments to find a CaregiverReference
   * @example
   * // Get one CaregiverReference
   * const caregiverReference = await prisma.caregiverReference.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CaregiverReferenceFindUniqueArgs>(args: Prisma.SelectSubset<T, CaregiverReferenceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CaregiverReferenceClient<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CaregiverReference that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CaregiverReferenceFindUniqueOrThrowArgs} args - Arguments to find a CaregiverReference
   * @example
   * // Get one CaregiverReference
   * const caregiverReference = await prisma.caregiverReference.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CaregiverReferenceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CaregiverReferenceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CaregiverReferenceClient<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CaregiverReference that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverReferenceFindFirstArgs} args - Arguments to find a CaregiverReference
   * @example
   * // Get one CaregiverReference
   * const caregiverReference = await prisma.caregiverReference.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CaregiverReferenceFindFirstArgs>(args?: Prisma.SelectSubset<T, CaregiverReferenceFindFirstArgs<ExtArgs>>): Prisma.Prisma__CaregiverReferenceClient<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CaregiverReference that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverReferenceFindFirstOrThrowArgs} args - Arguments to find a CaregiverReference
   * @example
   * // Get one CaregiverReference
   * const caregiverReference = await prisma.caregiverReference.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CaregiverReferenceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CaregiverReferenceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CaregiverReferenceClient<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CaregiverReferences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverReferenceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CaregiverReferences
   * const caregiverReferences = await prisma.caregiverReference.findMany()
   * 
   * // Get first 10 CaregiverReferences
   * const caregiverReferences = await prisma.caregiverReference.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const caregiverReferenceWithIdOnly = await prisma.caregiverReference.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CaregiverReferenceFindManyArgs>(args?: Prisma.SelectSubset<T, CaregiverReferenceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CaregiverReference.
   * @param {CaregiverReferenceCreateArgs} args - Arguments to create a CaregiverReference.
   * @example
   * // Create one CaregiverReference
   * const CaregiverReference = await prisma.caregiverReference.create({
   *   data: {
   *     // ... data to create a CaregiverReference
   *   }
   * })
   * 
   */
  create<T extends CaregiverReferenceCreateArgs>(args: Prisma.SelectSubset<T, CaregiverReferenceCreateArgs<ExtArgs>>): Prisma.Prisma__CaregiverReferenceClient<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CaregiverReferences.
   * @param {CaregiverReferenceCreateManyArgs} args - Arguments to create many CaregiverReferences.
   * @example
   * // Create many CaregiverReferences
   * const caregiverReference = await prisma.caregiverReference.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CaregiverReferenceCreateManyArgs>(args?: Prisma.SelectSubset<T, CaregiverReferenceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CaregiverReferences and returns the data saved in the database.
   * @param {CaregiverReferenceCreateManyAndReturnArgs} args - Arguments to create many CaregiverReferences.
   * @example
   * // Create many CaregiverReferences
   * const caregiverReference = await prisma.caregiverReference.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CaregiverReferences and only return the `id`
   * const caregiverReferenceWithIdOnly = await prisma.caregiverReference.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CaregiverReferenceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CaregiverReferenceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CaregiverReference.
   * @param {CaregiverReferenceDeleteArgs} args - Arguments to delete one CaregiverReference.
   * @example
   * // Delete one CaregiverReference
   * const CaregiverReference = await prisma.caregiverReference.delete({
   *   where: {
   *     // ... filter to delete one CaregiverReference
   *   }
   * })
   * 
   */
  delete<T extends CaregiverReferenceDeleteArgs>(args: Prisma.SelectSubset<T, CaregiverReferenceDeleteArgs<ExtArgs>>): Prisma.Prisma__CaregiverReferenceClient<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CaregiverReference.
   * @param {CaregiverReferenceUpdateArgs} args - Arguments to update one CaregiverReference.
   * @example
   * // Update one CaregiverReference
   * const caregiverReference = await prisma.caregiverReference.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CaregiverReferenceUpdateArgs>(args: Prisma.SelectSubset<T, CaregiverReferenceUpdateArgs<ExtArgs>>): Prisma.Prisma__CaregiverReferenceClient<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CaregiverReferences.
   * @param {CaregiverReferenceDeleteManyArgs} args - Arguments to filter CaregiverReferences to delete.
   * @example
   * // Delete a few CaregiverReferences
   * const { count } = await prisma.caregiverReference.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CaregiverReferenceDeleteManyArgs>(args?: Prisma.SelectSubset<T, CaregiverReferenceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CaregiverReferences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverReferenceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CaregiverReferences
   * const caregiverReference = await prisma.caregiverReference.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CaregiverReferenceUpdateManyArgs>(args: Prisma.SelectSubset<T, CaregiverReferenceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CaregiverReferences and returns the data updated in the database.
   * @param {CaregiverReferenceUpdateManyAndReturnArgs} args - Arguments to update many CaregiverReferences.
   * @example
   * // Update many CaregiverReferences
   * const caregiverReference = await prisma.caregiverReference.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CaregiverReferences and only return the `id`
   * const caregiverReferenceWithIdOnly = await prisma.caregiverReference.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CaregiverReferenceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CaregiverReferenceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CaregiverReference.
   * @param {CaregiverReferenceUpsertArgs} args - Arguments to update or create a CaregiverReference.
   * @example
   * // Update or create a CaregiverReference
   * const caregiverReference = await prisma.caregiverReference.upsert({
   *   create: {
   *     // ... data to create a CaregiverReference
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CaregiverReference we want to update
   *   }
   * })
   */
  upsert<T extends CaregiverReferenceUpsertArgs>(args: Prisma.SelectSubset<T, CaregiverReferenceUpsertArgs<ExtArgs>>): Prisma.Prisma__CaregiverReferenceClient<runtime.Types.Result.GetResult<Prisma.$CaregiverReferencePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CaregiverReferences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverReferenceCountArgs} args - Arguments to filter CaregiverReferences to count.
   * @example
   * // Count the number of CaregiverReferences
   * const count = await prisma.caregiverReference.count({
   *   where: {
   *     // ... the filter for the CaregiverReferences we want to count
   *   }
   * })
  **/
  count<T extends CaregiverReferenceCountArgs>(
    args?: Prisma.Subset<T, CaregiverReferenceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CaregiverReferenceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CaregiverReference.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverReferenceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CaregiverReferenceAggregateArgs>(args: Prisma.Subset<T, CaregiverReferenceAggregateArgs>): Prisma.PrismaPromise<GetCaregiverReferenceAggregateType<T>>

  /**
   * Group by CaregiverReference.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverReferenceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CaregiverReferenceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CaregiverReferenceGroupByArgs['orderBy'] }
      : { orderBy?: CaregiverReferenceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CaregiverReferenceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCaregiverReferenceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CaregiverReference model
 */
readonly fields: CaregiverReferenceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CaregiverReference.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CaregiverReferenceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  caregiver<T extends Prisma.CaregiverDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CaregiverDefaultArgs<ExtArgs>>): Prisma.Prisma__CaregiverClient<runtime.Types.Result.GetResult<Prisma.$CaregiverPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CaregiverReference model
 */
export interface CaregiverReferenceFieldRefs {
  readonly id: Prisma.FieldRef<"CaregiverReference", 'String'>
  readonly caregiverId: Prisma.FieldRef<"CaregiverReference", 'String'>
  readonly name: Prisma.FieldRef<"CaregiverReference", 'String'>
  readonly relationship: Prisma.FieldRef<"CaregiverReference", 'String'>
  readonly phone: Prisma.FieldRef<"CaregiverReference", 'String'>
  readonly email: Prisma.FieldRef<"CaregiverReference", 'String'>
  readonly notes: Prisma.FieldRef<"CaregiverReference", 'String'>
  readonly createdAt: Prisma.FieldRef<"CaregiverReference", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CaregiverReference findUnique
 */
export type CaregiverReferenceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverReference to fetch.
   */
  where: Prisma.CaregiverReferenceWhereUniqueInput
}

/**
 * CaregiverReference findUniqueOrThrow
 */
export type CaregiverReferenceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverReference to fetch.
   */
  where: Prisma.CaregiverReferenceWhereUniqueInput
}

/**
 * CaregiverReference findFirst
 */
export type CaregiverReferenceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverReference to fetch.
   */
  where?: Prisma.CaregiverReferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverReferences to fetch.
   */
  orderBy?: Prisma.CaregiverReferenceOrderByWithRelationInput | Prisma.CaregiverReferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CaregiverReferences.
   */
  cursor?: Prisma.CaregiverReferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverReferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverReferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverReferences.
   */
  distinct?: Prisma.CaregiverReferenceScalarFieldEnum | Prisma.CaregiverReferenceScalarFieldEnum[]
}

/**
 * CaregiverReference findFirstOrThrow
 */
export type CaregiverReferenceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverReference to fetch.
   */
  where?: Prisma.CaregiverReferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverReferences to fetch.
   */
  orderBy?: Prisma.CaregiverReferenceOrderByWithRelationInput | Prisma.CaregiverReferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CaregiverReferences.
   */
  cursor?: Prisma.CaregiverReferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverReferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverReferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverReferences.
   */
  distinct?: Prisma.CaregiverReferenceScalarFieldEnum | Prisma.CaregiverReferenceScalarFieldEnum[]
}

/**
 * CaregiverReference findMany
 */
export type CaregiverReferenceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverReferences to fetch.
   */
  where?: Prisma.CaregiverReferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverReferences to fetch.
   */
  orderBy?: Prisma.CaregiverReferenceOrderByWithRelationInput | Prisma.CaregiverReferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CaregiverReferences.
   */
  cursor?: Prisma.CaregiverReferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverReferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverReferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverReferences.
   */
  distinct?: Prisma.CaregiverReferenceScalarFieldEnum | Prisma.CaregiverReferenceScalarFieldEnum[]
}

/**
 * CaregiverReference create
 */
export type CaregiverReferenceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceInclude<ExtArgs> | null
  /**
   * The data needed to create a CaregiverReference.
   */
  data: Prisma.XOR<Prisma.CaregiverReferenceCreateInput, Prisma.CaregiverReferenceUncheckedCreateInput>
}

/**
 * CaregiverReference createMany
 */
export type CaregiverReferenceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CaregiverReferences.
   */
  data: Prisma.CaregiverReferenceCreateManyInput | Prisma.CaregiverReferenceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CaregiverReference createManyAndReturn
 */
export type CaregiverReferenceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * The data used to create many CaregiverReferences.
   */
  data: Prisma.CaregiverReferenceCreateManyInput | Prisma.CaregiverReferenceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CaregiverReference update
 */
export type CaregiverReferenceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceInclude<ExtArgs> | null
  /**
   * The data needed to update a CaregiverReference.
   */
  data: Prisma.XOR<Prisma.CaregiverReferenceUpdateInput, Prisma.CaregiverReferenceUncheckedUpdateInput>
  /**
   * Choose, which CaregiverReference to update.
   */
  where: Prisma.CaregiverReferenceWhereUniqueInput
}

/**
 * CaregiverReference updateMany
 */
export type CaregiverReferenceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CaregiverReferences.
   */
  data: Prisma.XOR<Prisma.CaregiverReferenceUpdateManyMutationInput, Prisma.CaregiverReferenceUncheckedUpdateManyInput>
  /**
   * Filter which CaregiverReferences to update
   */
  where?: Prisma.CaregiverReferenceWhereInput
  /**
   * Limit how many CaregiverReferences to update.
   */
  limit?: number
}

/**
 * CaregiverReference updateManyAndReturn
 */
export type CaregiverReferenceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * The data used to update CaregiverReferences.
   */
  data: Prisma.XOR<Prisma.CaregiverReferenceUpdateManyMutationInput, Prisma.CaregiverReferenceUncheckedUpdateManyInput>
  /**
   * Filter which CaregiverReferences to update
   */
  where?: Prisma.CaregiverReferenceWhereInput
  /**
   * Limit how many CaregiverReferences to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CaregiverReference upsert
 */
export type CaregiverReferenceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceInclude<ExtArgs> | null
  /**
   * The filter to search for the CaregiverReference to update in case it exists.
   */
  where: Prisma.CaregiverReferenceWhereUniqueInput
  /**
   * In case the CaregiverReference found by the `where` argument doesn't exist, create a new CaregiverReference with this data.
   */
  create: Prisma.XOR<Prisma.CaregiverReferenceCreateInput, Prisma.CaregiverReferenceUncheckedCreateInput>
  /**
   * In case the CaregiverReference was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CaregiverReferenceUpdateInput, Prisma.CaregiverReferenceUncheckedUpdateInput>
}

/**
 * CaregiverReference delete
 */
export type CaregiverReferenceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceInclude<ExtArgs> | null
  /**
   * Filter which CaregiverReference to delete.
   */
  where: Prisma.CaregiverReferenceWhereUniqueInput
}

/**
 * CaregiverReference deleteMany
 */
export type CaregiverReferenceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CaregiverReferences to delete
   */
  where?: Prisma.CaregiverReferenceWhereInput
  /**
   * Limit how many CaregiverReferences to delete.
   */
  limit?: number
}

/**
 * CaregiverReference without action
 */
export type CaregiverReferenceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverReference
   */
  select?: Prisma.CaregiverReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverReference
   */
  omit?: Prisma.CaregiverReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverReferenceInclude<ExtArgs> | null
}
