
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CaregiverShift` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CaregiverShift
 * 
 */
export type CaregiverShiftModel = runtime.Types.Result.DefaultSelection<Prisma.$CaregiverShiftPayload>

export type AggregateCaregiverShift = {
  _count: CaregiverShiftCountAggregateOutputType | null
  _avg: CaregiverShiftAvgAggregateOutputType | null
  _sum: CaregiverShiftSumAggregateOutputType | null
  _min: CaregiverShiftMinAggregateOutputType | null
  _max: CaregiverShiftMaxAggregateOutputType | null
}

export type CaregiverShiftAvgAggregateOutputType = {
  hoursWorked: runtime.Decimal | null
  payAmount: runtime.Decimal | null
}

export type CaregiverShiftSumAggregateOutputType = {
  hoursWorked: runtime.Decimal | null
  payAmount: runtime.Decimal | null
}

export type CaregiverShiftMinAggregateOutputType = {
  id: string | null
  relationshipId: string | null
  shiftDate: Date | null
  startTime: string | null
  endTime: string | null
  hoursWorked: runtime.Decimal | null
  status: string | null
  notes: string | null
  payAmount: runtime.Decimal | null
  createdAt: Date | null
}

export type CaregiverShiftMaxAggregateOutputType = {
  id: string | null
  relationshipId: string | null
  shiftDate: Date | null
  startTime: string | null
  endTime: string | null
  hoursWorked: runtime.Decimal | null
  status: string | null
  notes: string | null
  payAmount: runtime.Decimal | null
  createdAt: Date | null
}

export type CaregiverShiftCountAggregateOutputType = {
  id: number
  relationshipId: number
  shiftDate: number
  startTime: number
  endTime: number
  hoursWorked: number
  status: number
  notes: number
  payAmount: number
  createdAt: number
  _all: number
}


export type CaregiverShiftAvgAggregateInputType = {
  hoursWorked?: true
  payAmount?: true
}

export type CaregiverShiftSumAggregateInputType = {
  hoursWorked?: true
  payAmount?: true
}

export type CaregiverShiftMinAggregateInputType = {
  id?: true
  relationshipId?: true
  shiftDate?: true
  startTime?: true
  endTime?: true
  hoursWorked?: true
  status?: true
  notes?: true
  payAmount?: true
  createdAt?: true
}

export type CaregiverShiftMaxAggregateInputType = {
  id?: true
  relationshipId?: true
  shiftDate?: true
  startTime?: true
  endTime?: true
  hoursWorked?: true
  status?: true
  notes?: true
  payAmount?: true
  createdAt?: true
}

export type CaregiverShiftCountAggregateInputType = {
  id?: true
  relationshipId?: true
  shiftDate?: true
  startTime?: true
  endTime?: true
  hoursWorked?: true
  status?: true
  notes?: true
  payAmount?: true
  createdAt?: true
  _all?: true
}

export type CaregiverShiftAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CaregiverShift to aggregate.
   */
  where?: Prisma.CaregiverShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverShifts to fetch.
   */
  orderBy?: Prisma.CaregiverShiftOrderByWithRelationInput | Prisma.CaregiverShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CaregiverShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverShifts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CaregiverShifts
  **/
  _count?: true | CaregiverShiftCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CaregiverShiftAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CaregiverShiftSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CaregiverShiftMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CaregiverShiftMaxAggregateInputType
}

export type GetCaregiverShiftAggregateType<T extends CaregiverShiftAggregateArgs> = {
      [P in keyof T & keyof AggregateCaregiverShift]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCaregiverShift[P]>
    : Prisma.GetScalarType<T[P], AggregateCaregiverShift[P]>
}




export type CaregiverShiftGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CaregiverShiftWhereInput
  orderBy?: Prisma.CaregiverShiftOrderByWithAggregationInput | Prisma.CaregiverShiftOrderByWithAggregationInput[]
  by: Prisma.CaregiverShiftScalarFieldEnum[] | Prisma.CaregiverShiftScalarFieldEnum
  having?: Prisma.CaregiverShiftScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CaregiverShiftCountAggregateInputType | true
  _avg?: CaregiverShiftAvgAggregateInputType
  _sum?: CaregiverShiftSumAggregateInputType
  _min?: CaregiverShiftMinAggregateInputType
  _max?: CaregiverShiftMaxAggregateInputType
}

export type CaregiverShiftGroupByOutputType = {
  id: string
  relationshipId: string
  shiftDate: Date
  startTime: string
  endTime: string
  hoursWorked: runtime.Decimal
  status: string
  notes: string | null
  payAmount: runtime.Decimal | null
  createdAt: Date
  _count: CaregiverShiftCountAggregateOutputType | null
  _avg: CaregiverShiftAvgAggregateOutputType | null
  _sum: CaregiverShiftSumAggregateOutputType | null
  _min: CaregiverShiftMinAggregateOutputType | null
  _max: CaregiverShiftMaxAggregateOutputType | null
}

export type GetCaregiverShiftGroupByPayload<T extends CaregiverShiftGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CaregiverShiftGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CaregiverShiftGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CaregiverShiftGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CaregiverShiftGroupByOutputType[P]>
      }
    >
  >



export type CaregiverShiftWhereInput = {
  AND?: Prisma.CaregiverShiftWhereInput | Prisma.CaregiverShiftWhereInput[]
  OR?: Prisma.CaregiverShiftWhereInput[]
  NOT?: Prisma.CaregiverShiftWhereInput | Prisma.CaregiverShiftWhereInput[]
  id?: Prisma.StringFilter<"CaregiverShift"> | string
  relationshipId?: Prisma.StringFilter<"CaregiverShift"> | string
  shiftDate?: Prisma.DateTimeFilter<"CaregiverShift"> | Date | string
  startTime?: Prisma.StringFilter<"CaregiverShift"> | string
  endTime?: Prisma.StringFilter<"CaregiverShift"> | string
  hoursWorked?: Prisma.DecimalFilter<"CaregiverShift"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringFilter<"CaregiverShift"> | string
  notes?: Prisma.StringNullableFilter<"CaregiverShift"> | string | null
  payAmount?: Prisma.DecimalNullableFilter<"CaregiverShift"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverShift"> | Date | string
  relationship?: Prisma.XOR<Prisma.AgencyCaregiverRelationshipScalarRelationFilter, Prisma.AgencyCaregiverRelationshipWhereInput>
}

export type CaregiverShiftOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  relationshipId?: Prisma.SortOrder
  shiftDate?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  hoursWorked?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  payAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  relationship?: Prisma.AgencyCaregiverRelationshipOrderByWithRelationInput
}

export type CaregiverShiftWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CaregiverShiftWhereInput | Prisma.CaregiverShiftWhereInput[]
  OR?: Prisma.CaregiverShiftWhereInput[]
  NOT?: Prisma.CaregiverShiftWhereInput | Prisma.CaregiverShiftWhereInput[]
  relationshipId?: Prisma.StringFilter<"CaregiverShift"> | string
  shiftDate?: Prisma.DateTimeFilter<"CaregiverShift"> | Date | string
  startTime?: Prisma.StringFilter<"CaregiverShift"> | string
  endTime?: Prisma.StringFilter<"CaregiverShift"> | string
  hoursWorked?: Prisma.DecimalFilter<"CaregiverShift"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringFilter<"CaregiverShift"> | string
  notes?: Prisma.StringNullableFilter<"CaregiverShift"> | string | null
  payAmount?: Prisma.DecimalNullableFilter<"CaregiverShift"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverShift"> | Date | string
  relationship?: Prisma.XOR<Prisma.AgencyCaregiverRelationshipScalarRelationFilter, Prisma.AgencyCaregiverRelationshipWhereInput>
}, "id">

export type CaregiverShiftOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  relationshipId?: Prisma.SortOrder
  shiftDate?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  hoursWorked?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  payAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CaregiverShiftCountOrderByAggregateInput
  _avg?: Prisma.CaregiverShiftAvgOrderByAggregateInput
  _max?: Prisma.CaregiverShiftMaxOrderByAggregateInput
  _min?: Prisma.CaregiverShiftMinOrderByAggregateInput
  _sum?: Prisma.CaregiverShiftSumOrderByAggregateInput
}

export type CaregiverShiftScalarWhereWithAggregatesInput = {
  AND?: Prisma.CaregiverShiftScalarWhereWithAggregatesInput | Prisma.CaregiverShiftScalarWhereWithAggregatesInput[]
  OR?: Prisma.CaregiverShiftScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CaregiverShiftScalarWhereWithAggregatesInput | Prisma.CaregiverShiftScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CaregiverShift"> | string
  relationshipId?: Prisma.StringWithAggregatesFilter<"CaregiverShift"> | string
  shiftDate?: Prisma.DateTimeWithAggregatesFilter<"CaregiverShift"> | Date | string
  startTime?: Prisma.StringWithAggregatesFilter<"CaregiverShift"> | string
  endTime?: Prisma.StringWithAggregatesFilter<"CaregiverShift"> | string
  hoursWorked?: Prisma.DecimalWithAggregatesFilter<"CaregiverShift"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringWithAggregatesFilter<"CaregiverShift"> | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"CaregiverShift"> | string | null
  payAmount?: Prisma.DecimalNullableWithAggregatesFilter<"CaregiverShift"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CaregiverShift"> | Date | string
}

export type CaregiverShiftCreateInput = {
  id?: string
  shiftDate: Date | string
  startTime: string
  endTime: string
  hoursWorked: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: string
  notes?: string | null
  payAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
  relationship: Prisma.AgencyCaregiverRelationshipCreateNestedOneWithoutShiftsInput
}

export type CaregiverShiftUncheckedCreateInput = {
  id?: string
  relationshipId: string
  shiftDate: Date | string
  startTime: string
  endTime: string
  hoursWorked: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: string
  notes?: string | null
  payAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type CaregiverShiftUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shiftDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  relationship?: Prisma.AgencyCaregiverRelationshipUpdateOneRequiredWithoutShiftsNestedInput
}

export type CaregiverShiftUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relationshipId?: Prisma.StringFieldUpdateOperationsInput | string
  shiftDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverShiftCreateManyInput = {
  id?: string
  relationshipId: string
  shiftDate: Date | string
  startTime: string
  endTime: string
  hoursWorked: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: string
  notes?: string | null
  payAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type CaregiverShiftUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shiftDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverShiftUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relationshipId?: Prisma.StringFieldUpdateOperationsInput | string
  shiftDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverShiftListRelationFilter = {
  every?: Prisma.CaregiverShiftWhereInput
  some?: Prisma.CaregiverShiftWhereInput
  none?: Prisma.CaregiverShiftWhereInput
}

export type CaregiverShiftOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CaregiverShiftCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  relationshipId?: Prisma.SortOrder
  shiftDate?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  hoursWorked?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  payAmount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CaregiverShiftAvgOrderByAggregateInput = {
  hoursWorked?: Prisma.SortOrder
  payAmount?: Prisma.SortOrder
}

export type CaregiverShiftMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  relationshipId?: Prisma.SortOrder
  shiftDate?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  hoursWorked?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  payAmount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CaregiverShiftMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  relationshipId?: Prisma.SortOrder
  shiftDate?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  hoursWorked?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  payAmount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CaregiverShiftSumOrderByAggregateInput = {
  hoursWorked?: Prisma.SortOrder
  payAmount?: Prisma.SortOrder
}

export type CaregiverShiftCreateNestedManyWithoutRelationshipInput = {
  create?: Prisma.XOR<Prisma.CaregiverShiftCreateWithoutRelationshipInput, Prisma.CaregiverShiftUncheckedCreateWithoutRelationshipInput> | Prisma.CaregiverShiftCreateWithoutRelationshipInput[] | Prisma.CaregiverShiftUncheckedCreateWithoutRelationshipInput[]
  connectOrCreate?: Prisma.CaregiverShiftCreateOrConnectWithoutRelationshipInput | Prisma.CaregiverShiftCreateOrConnectWithoutRelationshipInput[]
  createMany?: Prisma.CaregiverShiftCreateManyRelationshipInputEnvelope
  connect?: Prisma.CaregiverShiftWhereUniqueInput | Prisma.CaregiverShiftWhereUniqueInput[]
}

export type CaregiverShiftUncheckedCreateNestedManyWithoutRelationshipInput = {
  create?: Prisma.XOR<Prisma.CaregiverShiftCreateWithoutRelationshipInput, Prisma.CaregiverShiftUncheckedCreateWithoutRelationshipInput> | Prisma.CaregiverShiftCreateWithoutRelationshipInput[] | Prisma.CaregiverShiftUncheckedCreateWithoutRelationshipInput[]
  connectOrCreate?: Prisma.CaregiverShiftCreateOrConnectWithoutRelationshipInput | Prisma.CaregiverShiftCreateOrConnectWithoutRelationshipInput[]
  createMany?: Prisma.CaregiverShiftCreateManyRelationshipInputEnvelope
  connect?: Prisma.CaregiverShiftWhereUniqueInput | Prisma.CaregiverShiftWhereUniqueInput[]
}

export type CaregiverShiftUpdateManyWithoutRelationshipNestedInput = {
  create?: Prisma.XOR<Prisma.CaregiverShiftCreateWithoutRelationshipInput, Prisma.CaregiverShiftUncheckedCreateWithoutRelationshipInput> | Prisma.CaregiverShiftCreateWithoutRelationshipInput[] | Prisma.CaregiverShiftUncheckedCreateWithoutRelationshipInput[]
  connectOrCreate?: Prisma.CaregiverShiftCreateOrConnectWithoutRelationshipInput | Prisma.CaregiverShiftCreateOrConnectWithoutRelationshipInput[]
  upsert?: Prisma.CaregiverShiftUpsertWithWhereUniqueWithoutRelationshipInput | Prisma.CaregiverShiftUpsertWithWhereUniqueWithoutRelationshipInput[]
  createMany?: Prisma.CaregiverShiftCreateManyRelationshipInputEnvelope
  set?: Prisma.CaregiverShiftWhereUniqueInput | Prisma.CaregiverShiftWhereUniqueInput[]
  disconnect?: Prisma.CaregiverShiftWhereUniqueInput | Prisma.CaregiverShiftWhereUniqueInput[]
  delete?: Prisma.CaregiverShiftWhereUniqueInput | Prisma.CaregiverShiftWhereUniqueInput[]
  connect?: Prisma.CaregiverShiftWhereUniqueInput | Prisma.CaregiverShiftWhereUniqueInput[]
  update?: Prisma.CaregiverShiftUpdateWithWhereUniqueWithoutRelationshipInput | Prisma.CaregiverShiftUpdateWithWhereUniqueWithoutRelationshipInput[]
  updateMany?: Prisma.CaregiverShiftUpdateManyWithWhereWithoutRelationshipInput | Prisma.CaregiverShiftUpdateManyWithWhereWithoutRelationshipInput[]
  deleteMany?: Prisma.CaregiverShiftScalarWhereInput | Prisma.CaregiverShiftScalarWhereInput[]
}

export type CaregiverShiftUncheckedUpdateManyWithoutRelationshipNestedInput = {
  create?: Prisma.XOR<Prisma.CaregiverShiftCreateWithoutRelationshipInput, Prisma.CaregiverShiftUncheckedCreateWithoutRelationshipInput> | Prisma.CaregiverShiftCreateWithoutRelationshipInput[] | Prisma.CaregiverShiftUncheckedCreateWithoutRelationshipInput[]
  connectOrCreate?: Prisma.CaregiverShiftCreateOrConnectWithoutRelationshipInput | Prisma.CaregiverShiftCreateOrConnectWithoutRelationshipInput[]
  upsert?: Prisma.CaregiverShiftUpsertWithWhereUniqueWithoutRelationshipInput | Prisma.CaregiverShiftUpsertWithWhereUniqueWithoutRelationshipInput[]
  createMany?: Prisma.CaregiverShiftCreateManyRelationshipInputEnvelope
  set?: Prisma.CaregiverShiftWhereUniqueInput | Prisma.CaregiverShiftWhereUniqueInput[]
  disconnect?: Prisma.CaregiverShiftWhereUniqueInput | Prisma.CaregiverShiftWhereUniqueInput[]
  delete?: Prisma.CaregiverShiftWhereUniqueInput | Prisma.CaregiverShiftWhereUniqueInput[]
  connect?: Prisma.CaregiverShiftWhereUniqueInput | Prisma.CaregiverShiftWhereUniqueInput[]
  update?: Prisma.CaregiverShiftUpdateWithWhereUniqueWithoutRelationshipInput | Prisma.CaregiverShiftUpdateWithWhereUniqueWithoutRelationshipInput[]
  updateMany?: Prisma.CaregiverShiftUpdateManyWithWhereWithoutRelationshipInput | Prisma.CaregiverShiftUpdateManyWithWhereWithoutRelationshipInput[]
  deleteMany?: Prisma.CaregiverShiftScalarWhereInput | Prisma.CaregiverShiftScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type CaregiverShiftCreateWithoutRelationshipInput = {
  id?: string
  shiftDate: Date | string
  startTime: string
  endTime: string
  hoursWorked: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: string
  notes?: string | null
  payAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type CaregiverShiftUncheckedCreateWithoutRelationshipInput = {
  id?: string
  shiftDate: Date | string
  startTime: string
  endTime: string
  hoursWorked: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: string
  notes?: string | null
  payAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type CaregiverShiftCreateOrConnectWithoutRelationshipInput = {
  where: Prisma.CaregiverShiftWhereUniqueInput
  create: Prisma.XOR<Prisma.CaregiverShiftCreateWithoutRelationshipInput, Prisma.CaregiverShiftUncheckedCreateWithoutRelationshipInput>
}

export type CaregiverShiftCreateManyRelationshipInputEnvelope = {
  data: Prisma.CaregiverShiftCreateManyRelationshipInput | Prisma.CaregiverShiftCreateManyRelationshipInput[]
  skipDuplicates?: boolean
}

export type CaregiverShiftUpsertWithWhereUniqueWithoutRelationshipInput = {
  where: Prisma.CaregiverShiftWhereUniqueInput
  update: Prisma.XOR<Prisma.CaregiverShiftUpdateWithoutRelationshipInput, Prisma.CaregiverShiftUncheckedUpdateWithoutRelationshipInput>
  create: Prisma.XOR<Prisma.CaregiverShiftCreateWithoutRelationshipInput, Prisma.CaregiverShiftUncheckedCreateWithoutRelationshipInput>
}

export type CaregiverShiftUpdateWithWhereUniqueWithoutRelationshipInput = {
  where: Prisma.CaregiverShiftWhereUniqueInput
  data: Prisma.XOR<Prisma.CaregiverShiftUpdateWithoutRelationshipInput, Prisma.CaregiverShiftUncheckedUpdateWithoutRelationshipInput>
}

export type CaregiverShiftUpdateManyWithWhereWithoutRelationshipInput = {
  where: Prisma.CaregiverShiftScalarWhereInput
  data: Prisma.XOR<Prisma.CaregiverShiftUpdateManyMutationInput, Prisma.CaregiverShiftUncheckedUpdateManyWithoutRelationshipInput>
}

export type CaregiverShiftScalarWhereInput = {
  AND?: Prisma.CaregiverShiftScalarWhereInput | Prisma.CaregiverShiftScalarWhereInput[]
  OR?: Prisma.CaregiverShiftScalarWhereInput[]
  NOT?: Prisma.CaregiverShiftScalarWhereInput | Prisma.CaregiverShiftScalarWhereInput[]
  id?: Prisma.StringFilter<"CaregiverShift"> | string
  relationshipId?: Prisma.StringFilter<"CaregiverShift"> | string
  shiftDate?: Prisma.DateTimeFilter<"CaregiverShift"> | Date | string
  startTime?: Prisma.StringFilter<"CaregiverShift"> | string
  endTime?: Prisma.StringFilter<"CaregiverShift"> | string
  hoursWorked?: Prisma.DecimalFilter<"CaregiverShift"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringFilter<"CaregiverShift"> | string
  notes?: Prisma.StringNullableFilter<"CaregiverShift"> | string | null
  payAmount?: Prisma.DecimalNullableFilter<"CaregiverShift"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFilter<"CaregiverShift"> | Date | string
}

export type CaregiverShiftCreateManyRelationshipInput = {
  id?: string
  shiftDate: Date | string
  startTime: string
  endTime: string
  hoursWorked: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: string
  notes?: string | null
  payAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type CaregiverShiftUpdateWithoutRelationshipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shiftDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverShiftUncheckedUpdateWithoutRelationshipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shiftDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaregiverShiftUncheckedUpdateManyWithoutRelationshipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shiftDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CaregiverShiftSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  relationshipId?: boolean
  shiftDate?: boolean
  startTime?: boolean
  endTime?: boolean
  hoursWorked?: boolean
  status?: boolean
  notes?: boolean
  payAmount?: boolean
  createdAt?: boolean
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverShift"]>

export type CaregiverShiftSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  relationshipId?: boolean
  shiftDate?: boolean
  startTime?: boolean
  endTime?: boolean
  hoursWorked?: boolean
  status?: boolean
  notes?: boolean
  payAmount?: boolean
  createdAt?: boolean
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverShift"]>

export type CaregiverShiftSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  relationshipId?: boolean
  shiftDate?: boolean
  startTime?: boolean
  endTime?: boolean
  hoursWorked?: boolean
  status?: boolean
  notes?: boolean
  payAmount?: boolean
  createdAt?: boolean
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caregiverShift"]>

export type CaregiverShiftSelectScalar = {
  id?: boolean
  relationshipId?: boolean
  shiftDate?: boolean
  startTime?: boolean
  endTime?: boolean
  hoursWorked?: boolean
  status?: boolean
  notes?: boolean
  payAmount?: boolean
  createdAt?: boolean
}

export type CaregiverShiftOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "relationshipId" | "shiftDate" | "startTime" | "endTime" | "hoursWorked" | "status" | "notes" | "payAmount" | "createdAt", ExtArgs["result"]["caregiverShift"]>
export type CaregiverShiftInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}
export type CaregiverShiftIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}
export type CaregiverShiftIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  relationship?: boolean | Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>
}

export type $CaregiverShiftPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CaregiverShift"
  objects: {
    relationship: Prisma.$AgencyCaregiverRelationshipPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    relationshipId: string
    shiftDate: Date
    startTime: string
    endTime: string
    hoursWorked: runtime.Decimal
    status: string
    notes: string | null
    payAmount: runtime.Decimal | null
    createdAt: Date
  }, ExtArgs["result"]["caregiverShift"]>
  composites: {}
}

export type CaregiverShiftGetPayload<S extends boolean | null | undefined | CaregiverShiftDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload, S>

export type CaregiverShiftCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CaregiverShiftFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CaregiverShiftCountAggregateInputType | true
  }

export interface CaregiverShiftDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CaregiverShift'], meta: { name: 'CaregiverShift' } }
  /**
   * Find zero or one CaregiverShift that matches the filter.
   * @param {CaregiverShiftFindUniqueArgs} args - Arguments to find a CaregiverShift
   * @example
   * // Get one CaregiverShift
   * const caregiverShift = await prisma.caregiverShift.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CaregiverShiftFindUniqueArgs>(args: Prisma.SelectSubset<T, CaregiverShiftFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CaregiverShiftClient<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CaregiverShift that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CaregiverShiftFindUniqueOrThrowArgs} args - Arguments to find a CaregiverShift
   * @example
   * // Get one CaregiverShift
   * const caregiverShift = await prisma.caregiverShift.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CaregiverShiftFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CaregiverShiftFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CaregiverShiftClient<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CaregiverShift that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverShiftFindFirstArgs} args - Arguments to find a CaregiverShift
   * @example
   * // Get one CaregiverShift
   * const caregiverShift = await prisma.caregiverShift.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CaregiverShiftFindFirstArgs>(args?: Prisma.SelectSubset<T, CaregiverShiftFindFirstArgs<ExtArgs>>): Prisma.Prisma__CaregiverShiftClient<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CaregiverShift that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverShiftFindFirstOrThrowArgs} args - Arguments to find a CaregiverShift
   * @example
   * // Get one CaregiverShift
   * const caregiverShift = await prisma.caregiverShift.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CaregiverShiftFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CaregiverShiftFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CaregiverShiftClient<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CaregiverShifts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverShiftFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CaregiverShifts
   * const caregiverShifts = await prisma.caregiverShift.findMany()
   * 
   * // Get first 10 CaregiverShifts
   * const caregiverShifts = await prisma.caregiverShift.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const caregiverShiftWithIdOnly = await prisma.caregiverShift.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CaregiverShiftFindManyArgs>(args?: Prisma.SelectSubset<T, CaregiverShiftFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CaregiverShift.
   * @param {CaregiverShiftCreateArgs} args - Arguments to create a CaregiverShift.
   * @example
   * // Create one CaregiverShift
   * const CaregiverShift = await prisma.caregiverShift.create({
   *   data: {
   *     // ... data to create a CaregiverShift
   *   }
   * })
   * 
   */
  create<T extends CaregiverShiftCreateArgs>(args: Prisma.SelectSubset<T, CaregiverShiftCreateArgs<ExtArgs>>): Prisma.Prisma__CaregiverShiftClient<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CaregiverShifts.
   * @param {CaregiverShiftCreateManyArgs} args - Arguments to create many CaregiverShifts.
   * @example
   * // Create many CaregiverShifts
   * const caregiverShift = await prisma.caregiverShift.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CaregiverShiftCreateManyArgs>(args?: Prisma.SelectSubset<T, CaregiverShiftCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CaregiverShifts and returns the data saved in the database.
   * @param {CaregiverShiftCreateManyAndReturnArgs} args - Arguments to create many CaregiverShifts.
   * @example
   * // Create many CaregiverShifts
   * const caregiverShift = await prisma.caregiverShift.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CaregiverShifts and only return the `id`
   * const caregiverShiftWithIdOnly = await prisma.caregiverShift.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CaregiverShiftCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CaregiverShiftCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CaregiverShift.
   * @param {CaregiverShiftDeleteArgs} args - Arguments to delete one CaregiverShift.
   * @example
   * // Delete one CaregiverShift
   * const CaregiverShift = await prisma.caregiverShift.delete({
   *   where: {
   *     // ... filter to delete one CaregiverShift
   *   }
   * })
   * 
   */
  delete<T extends CaregiverShiftDeleteArgs>(args: Prisma.SelectSubset<T, CaregiverShiftDeleteArgs<ExtArgs>>): Prisma.Prisma__CaregiverShiftClient<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CaregiverShift.
   * @param {CaregiverShiftUpdateArgs} args - Arguments to update one CaregiverShift.
   * @example
   * // Update one CaregiverShift
   * const caregiverShift = await prisma.caregiverShift.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CaregiverShiftUpdateArgs>(args: Prisma.SelectSubset<T, CaregiverShiftUpdateArgs<ExtArgs>>): Prisma.Prisma__CaregiverShiftClient<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CaregiverShifts.
   * @param {CaregiverShiftDeleteManyArgs} args - Arguments to filter CaregiverShifts to delete.
   * @example
   * // Delete a few CaregiverShifts
   * const { count } = await prisma.caregiverShift.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CaregiverShiftDeleteManyArgs>(args?: Prisma.SelectSubset<T, CaregiverShiftDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CaregiverShifts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverShiftUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CaregiverShifts
   * const caregiverShift = await prisma.caregiverShift.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CaregiverShiftUpdateManyArgs>(args: Prisma.SelectSubset<T, CaregiverShiftUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CaregiverShifts and returns the data updated in the database.
   * @param {CaregiverShiftUpdateManyAndReturnArgs} args - Arguments to update many CaregiverShifts.
   * @example
   * // Update many CaregiverShifts
   * const caregiverShift = await prisma.caregiverShift.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CaregiverShifts and only return the `id`
   * const caregiverShiftWithIdOnly = await prisma.caregiverShift.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CaregiverShiftUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CaregiverShiftUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CaregiverShift.
   * @param {CaregiverShiftUpsertArgs} args - Arguments to update or create a CaregiverShift.
   * @example
   * // Update or create a CaregiverShift
   * const caregiverShift = await prisma.caregiverShift.upsert({
   *   create: {
   *     // ... data to create a CaregiverShift
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CaregiverShift we want to update
   *   }
   * })
   */
  upsert<T extends CaregiverShiftUpsertArgs>(args: Prisma.SelectSubset<T, CaregiverShiftUpsertArgs<ExtArgs>>): Prisma.Prisma__CaregiverShiftClient<runtime.Types.Result.GetResult<Prisma.$CaregiverShiftPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CaregiverShifts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverShiftCountArgs} args - Arguments to filter CaregiverShifts to count.
   * @example
   * // Count the number of CaregiverShifts
   * const count = await prisma.caregiverShift.count({
   *   where: {
   *     // ... the filter for the CaregiverShifts we want to count
   *   }
   * })
  **/
  count<T extends CaregiverShiftCountArgs>(
    args?: Prisma.Subset<T, CaregiverShiftCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CaregiverShiftCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CaregiverShift.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverShiftAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CaregiverShiftAggregateArgs>(args: Prisma.Subset<T, CaregiverShiftAggregateArgs>): Prisma.PrismaPromise<GetCaregiverShiftAggregateType<T>>

  /**
   * Group by CaregiverShift.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaregiverShiftGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CaregiverShiftGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CaregiverShiftGroupByArgs['orderBy'] }
      : { orderBy?: CaregiverShiftGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CaregiverShiftGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCaregiverShiftGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CaregiverShift model
 */
readonly fields: CaregiverShiftFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CaregiverShift.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CaregiverShiftClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  relationship<T extends Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AgencyCaregiverRelationshipDefaultArgs<ExtArgs>>): Prisma.Prisma__AgencyCaregiverRelationshipClient<runtime.Types.Result.GetResult<Prisma.$AgencyCaregiverRelationshipPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CaregiverShift model
 */
export interface CaregiverShiftFieldRefs {
  readonly id: Prisma.FieldRef<"CaregiverShift", 'String'>
  readonly relationshipId: Prisma.FieldRef<"CaregiverShift", 'String'>
  readonly shiftDate: Prisma.FieldRef<"CaregiverShift", 'DateTime'>
  readonly startTime: Prisma.FieldRef<"CaregiverShift", 'String'>
  readonly endTime: Prisma.FieldRef<"CaregiverShift", 'String'>
  readonly hoursWorked: Prisma.FieldRef<"CaregiverShift", 'Decimal'>
  readonly status: Prisma.FieldRef<"CaregiverShift", 'String'>
  readonly notes: Prisma.FieldRef<"CaregiverShift", 'String'>
  readonly payAmount: Prisma.FieldRef<"CaregiverShift", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"CaregiverShift", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CaregiverShift findUnique
 */
export type CaregiverShiftFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverShift to fetch.
   */
  where: Prisma.CaregiverShiftWhereUniqueInput
}

/**
 * CaregiverShift findUniqueOrThrow
 */
export type CaregiverShiftFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverShift to fetch.
   */
  where: Prisma.CaregiverShiftWhereUniqueInput
}

/**
 * CaregiverShift findFirst
 */
export type CaregiverShiftFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverShift to fetch.
   */
  where?: Prisma.CaregiverShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverShifts to fetch.
   */
  orderBy?: Prisma.CaregiverShiftOrderByWithRelationInput | Prisma.CaregiverShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CaregiverShifts.
   */
  cursor?: Prisma.CaregiverShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverShifts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverShifts.
   */
  distinct?: Prisma.CaregiverShiftScalarFieldEnum | Prisma.CaregiverShiftScalarFieldEnum[]
}

/**
 * CaregiverShift findFirstOrThrow
 */
export type CaregiverShiftFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverShift to fetch.
   */
  where?: Prisma.CaregiverShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverShifts to fetch.
   */
  orderBy?: Prisma.CaregiverShiftOrderByWithRelationInput | Prisma.CaregiverShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CaregiverShifts.
   */
  cursor?: Prisma.CaregiverShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverShifts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverShifts.
   */
  distinct?: Prisma.CaregiverShiftScalarFieldEnum | Prisma.CaregiverShiftScalarFieldEnum[]
}

/**
 * CaregiverShift findMany
 */
export type CaregiverShiftFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftInclude<ExtArgs> | null
  /**
   * Filter, which CaregiverShifts to fetch.
   */
  where?: Prisma.CaregiverShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaregiverShifts to fetch.
   */
  orderBy?: Prisma.CaregiverShiftOrderByWithRelationInput | Prisma.CaregiverShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CaregiverShifts.
   */
  cursor?: Prisma.CaregiverShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaregiverShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaregiverShifts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaregiverShifts.
   */
  distinct?: Prisma.CaregiverShiftScalarFieldEnum | Prisma.CaregiverShiftScalarFieldEnum[]
}

/**
 * CaregiverShift create
 */
export type CaregiverShiftCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftInclude<ExtArgs> | null
  /**
   * The data needed to create a CaregiverShift.
   */
  data: Prisma.XOR<Prisma.CaregiverShiftCreateInput, Prisma.CaregiverShiftUncheckedCreateInput>
}

/**
 * CaregiverShift createMany
 */
export type CaregiverShiftCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CaregiverShifts.
   */
  data: Prisma.CaregiverShiftCreateManyInput | Prisma.CaregiverShiftCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CaregiverShift createManyAndReturn
 */
export type CaregiverShiftCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * The data used to create many CaregiverShifts.
   */
  data: Prisma.CaregiverShiftCreateManyInput | Prisma.CaregiverShiftCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CaregiverShift update
 */
export type CaregiverShiftUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftInclude<ExtArgs> | null
  /**
   * The data needed to update a CaregiverShift.
   */
  data: Prisma.XOR<Prisma.CaregiverShiftUpdateInput, Prisma.CaregiverShiftUncheckedUpdateInput>
  /**
   * Choose, which CaregiverShift to update.
   */
  where: Prisma.CaregiverShiftWhereUniqueInput
}

/**
 * CaregiverShift updateMany
 */
export type CaregiverShiftUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CaregiverShifts.
   */
  data: Prisma.XOR<Prisma.CaregiverShiftUpdateManyMutationInput, Prisma.CaregiverShiftUncheckedUpdateManyInput>
  /**
   * Filter which CaregiverShifts to update
   */
  where?: Prisma.CaregiverShiftWhereInput
  /**
   * Limit how many CaregiverShifts to update.
   */
  limit?: number
}

/**
 * CaregiverShift updateManyAndReturn
 */
export type CaregiverShiftUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * The data used to update CaregiverShifts.
   */
  data: Prisma.XOR<Prisma.CaregiverShiftUpdateManyMutationInput, Prisma.CaregiverShiftUncheckedUpdateManyInput>
  /**
   * Filter which CaregiverShifts to update
   */
  where?: Prisma.CaregiverShiftWhereInput
  /**
   * Limit how many CaregiverShifts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CaregiverShift upsert
 */
export type CaregiverShiftUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftInclude<ExtArgs> | null
  /**
   * The filter to search for the CaregiverShift to update in case it exists.
   */
  where: Prisma.CaregiverShiftWhereUniqueInput
  /**
   * In case the CaregiverShift found by the `where` argument doesn't exist, create a new CaregiverShift with this data.
   */
  create: Prisma.XOR<Prisma.CaregiverShiftCreateInput, Prisma.CaregiverShiftUncheckedCreateInput>
  /**
   * In case the CaregiverShift was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CaregiverShiftUpdateInput, Prisma.CaregiverShiftUncheckedUpdateInput>
}

/**
 * CaregiverShift delete
 */
export type CaregiverShiftDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftInclude<ExtArgs> | null
  /**
   * Filter which CaregiverShift to delete.
   */
  where: Prisma.CaregiverShiftWhereUniqueInput
}

/**
 * CaregiverShift deleteMany
 */
export type CaregiverShiftDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CaregiverShifts to delete
   */
  where?: Prisma.CaregiverShiftWhereInput
  /**
   * Limit how many CaregiverShifts to delete.
   */
  limit?: number
}

/**
 * CaregiverShift without action
 */
export type CaregiverShiftDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaregiverShift
   */
  select?: Prisma.CaregiverShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaregiverShift
   */
  omit?: Prisma.CaregiverShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaregiverShiftInclude<ExtArgs> | null
}
