// Demo mode configuration
// When enabled, all pages render with demo data (no auth required, no DB writes)

export const DEMO_MODE = true;

export const DEMO_AGENCY = {
  id: 'demo-agency-001',
  name: 'CareFirst Home Care',
  displayName: 'CareFirst',
  tagline: 'Compassionate care for your loved ones',
  brandColor: '#1E3A8A',
  serviceAreas: ['Toronto', 'Mississauga', 'Brampton', 'Oakville', 'Markham'],
  careTypes: ['personal care', 'companionship', 'medication reminder', 'meal preparation'],
  provinces: ['Ontario'],
  city: 'Toronto',
  status: 'approved' as const,
  planTier: 'professional',
  modulesEnabled: ['core', 'intelligence', 'airecruit'],
};

export const DEMO_CLIENTS = [
  {
    id: 'demo-client-001',
    clientFirstName: 'Eleanor',
    primaryCondition: 'Dementia (moderate)',
    secondaryConditions: ['Mobility limitations', 'Diabetes'],
    mobilityLevel: 'moderate' as const,
    medicationsComplex: true,
    servicesNeeded: ['personal care', 'medication reminder', 'companionship'],
    careIntensity: 'high' as const,
    placementType: 'live-out' as const,
    hoursPerWeek: 40,
    city: 'Toronto',
    state: 'Ontario',
    genderPreference: 'female' as const,
    languageRequired: 'English',
    hourlyRateMax: 35,
    status: 'active' as const,
  },
  {
    id: 'demo-client-002',
    clientFirstName: 'Robert',
    primaryCondition: "Parkinson's disease",
    secondaryConditions: ['Sleep disturbances'],
    mobilityLevel: 'full' as const,
    medicationsComplex: true,
    servicesNeeded: ['companionship', 'meal preparation', 'light housekeeping'],
    careIntensity: 'medium' as const,
    placementType: 'live-out' as const,
    hoursPerWeek: 20,
    city: 'Mississauga',
    state: 'Ontario',
    genderPreference: 'no-preference' as const,
    languageRequired: 'English',
    hourlyRateMax: 30,
    status: 'active' as const,
  },
  {
    id: 'demo-client-003',
    clientFirstName: 'Margaret',
    primaryCondition: 'Post-stroke recovery',
    secondaryConditions: ['Speech impairment', 'Mobility limitations'],
    mobilityLevel: 'limited' as const,
    medicationsComplex: true,
    servicesNeeded: ['personal care', 'medication reminder', 'physio assistance'],
    careIntensity: 'high' as const,
    placementType: 'live-in' as const,
    hoursPerWeek: 56,
    city: 'Brampton',
    state: 'Ontario',
    genderPreference: 'female' as const,
    languageRequired: 'English',
    hourlyRateMax: 40,
    status: 'active' as const,
  },
  {
    id: 'demo-client-004',
    clientFirstName: 'James',
    primaryCondition: 'Hospice care',
    secondaryConditions: ['Chronic pain'],
    mobilityLevel: 'minimal' as const,
    medicationsComplex: true,
    servicesNeeded: ['personal care', 'medication reminder', 'companionship'],
    careIntensity: 'high' as const,
    placementType: 'live-in' as const,
    hoursPerWeek: 56,
    city: 'Oakville',
    state: 'Ontario',
    genderPreference: 'no-preference' as const,
    languageRequired: 'English',
    hourlyRateMax: 45,
    status: 'active' as const,
  },
  {
    id: 'demo-client-005',
    clientFirstName: 'Dorothy',
    primaryCondition: 'Post-surgical recovery',
    secondaryConditions: [],
    mobilityLevel: 'recovering' as const,
    medicationsComplex: false,
    servicesNeeded: ['personal care', 'meal preparation', 'light housekeeping'],
    careIntensity: 'medium' as const,
    placementType: 'live-out' as const,
    hoursPerWeek: 30,
    city: 'Markham',
    state: 'Ontario',
    genderPreference: 'female' as const,
    languageRequired: 'English',
    hourlyRateMax: 32,
    status: 'active' as const,
  },
];

export const DEMO_BANNER = {
  message: 'You are in demo mode — no real data',
  cta: 'Sign up to get started',
  ctaLink: '/sign-up?role=agency',
};