// Careified — Demo Seed Script
// Creates 15 realistic caregivers across varied profiles
// Run: node scripts/seed-demo.js

const { Pool } = require('pg');

const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

const caregivers = [
 {
 first_name: 'Maria', last_name: 'Santos', preferred_name: 'Maria',
 job_title: 'Personal Support Worker',
 email: 'maria.santos@demo.careified.com', phone: '(214) 555-0101',
 city: 'Frisco', state: 'TX', postal_code: '75034',
 gender: 'Female', status: 'approved',
 bio: 'Dedicated PSW with 8 years specializing in dementia and Alzheimer\'s care. Known for patience and building meaningful connections with clients and families.',
 availability_status: 'available_now',
 years_experience: 8,
 aggregate_score: 4.8,
 rating_count: 12,
 services: ['Bathing and showering assistance','Dressing and grooming assistance','Dementia care and support','Medication reminders','Meal planning and preparation','Companionship and conversation'],
 specializations: ["Dementia / Alzheimer's","Memory care","Behavioural support","Medication management"],
 credentials: ['PSW'],
 placement_types: ['Permanent placement','Regular part-time','Live-in care'],
 languages: ['English','Spanish','Tagalog'],
 willing_live_in: true,
 willing_overnight: true,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: true,
 travel_radius: 25,
 open_to_urgent: true,
 pet_tolerance: 'comfortable',
 smoker_household: false,
 technology_comfort: 'comfortable',
 employment_type: 'either',
 lift_experience: ['Hoyer / mechanical lift','Transfer belt'],
 hourly_rate: 28,
 min_hours_per_week: 20,
 max_hours_per_week: 40,
 holiday_available: true,
 profile_completion_pct: 78,
 clients_served_count: 23,
 photo_url: null,
 },
 {
 first_name: 'James', last_name: 'Okafor', preferred_name: 'James',
 job_title: 'Certified Nursing Assistant',
 email: 'james.okafor@demo.careified.com', phone: '(972) 555-0102',
 city: 'McKinney', state: 'TX', postal_code: '75070',
 gender: 'Male', status: 'approved',
 bio: 'CNA with 5 years in post-surgical and stroke recovery care. Trained in mechanical lifts and bariatric care. Calm under pressure.',
 availability_status: 'available_now',
 years_experience: 5,
 aggregate_score: 4.6,
 rating_count: 8,
 services: ['Mobility assistance (walking, standing)','Transfer assistance (bed to chair)','Hoyer/mechanical lift operation','Post-surgical / rehab support','Vital signs monitoring (non-clinical)','Medication reminders'],
 specializations: ['Post-hospital recovery','Stroke recovery','Bariatric care','Mobility and transfer'],
 credentials: ['CNA'],
 placement_types: ['Permanent placement','Casual / relief shifts','Overnight care'],
 languages: ['English','French'],
 willing_live_in: false,
 willing_overnight: true,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: true,
 travel_radius: 20,
 open_to_urgent: true,
 pet_tolerance: 'no_preference',
 smoker_household: false,
 technology_comfort: 'experienced',
 employment_type: 'employee',
 lift_experience: ['Bariatric care','Hoyer / mechanical lift','Two-person assist','Transfer belt'],
 hourly_rate: 24,
 min_hours_per_week: 24,
 max_hours_per_week: 40,
 holiday_available: false,
 profile_completion_pct: 72,
 clients_served_count: 14,
 photo_url: null,
 },
 {
 first_name: 'Priya', last_name: 'Nair', preferred_name: 'Priya',
 job_title: 'Registered Nurse — Home Care',
 email: 'priya.nair@demo.careified.com', phone: '(469) 555-0103',
 city: 'Plano', state: 'TX', postal_code: '75024',
 gender: 'Female', status: 'approved',
 bio: 'RN with 12 years clinical experience transitioning to home care. Specializes in palliative and end-of-life care. Multilingual.',
 availability_status: 'open_to_opportunities',
 years_experience: 12,
 aggregate_score: 4.9,
 rating_count: 19,
 services: ['Medication administration (where permitted)','Wound dressing / post-surgical care','Vital signs monitoring (non-clinical)','Catheter care / ostomy care','Palliative / end-of-life care','Feeding assistance'],
 specializations: ['Palliative / end of life','Hospice support','Medication management','Wound care'],
 credentials: ['RN'],
 placement_types: ['Permanent placement','Regular part-time'],
 languages: ['English','Hindi','Punjabi'],
 willing_live_in: false,
 willing_overnight: false,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: false,
 travel_radius: 15,
 open_to_urgent: false,
 pet_tolerance: 'comfortable',
 smoker_household: false,
 technology_comfort: 'experienced',
 employment_type: 'contractor',
 lift_experience: [],
 hourly_rate: 45,
 min_hours_per_week: 16,
 max_hours_per_week: 32,
 holiday_available: false,
 profile_completion_pct: 81,
 clients_served_count: 41,
 photo_url: null,
 },
 {
 first_name: 'Sandra', last_name: 'Beaumont', preferred_name: 'Sandy',
 job_title: 'Home Health Aide',
 email: 'sandra.beaumont@demo.careified.com', phone: '(214) 555-0104',
 city: 'Allen', state: 'TX', postal_code: '75013',
 gender: 'Female', status: 'approved',
 bio: 'Warm and energetic HHA with 6 years helping elderly clients maintain independence at home. Excellent family communicator.',
 availability_status: 'available_now',
 years_experience: 6,
 aggregate_score: 4.7,
 rating_count: 11,
 services: ['Bathing and showering assistance','Meal planning and preparation','Light housekeeping','Laundry and folding','Companionship and conversation','Grocery shopping / errands','Transportation to appointments'],
 specializations: ["Dementia / Alzheimer's","Diabetes management","Mental health support"],
 credentials: ['HHA'],
 placement_types: ['Permanent placement','Regular part-time','Respite care'],
 languages: ['English','French'],
 willing_live_in: true,
 willing_overnight: false,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: true,
 travel_radius: 30,
 open_to_urgent: false,
 pet_tolerance: 'comfortable',
 smoker_household: true,
 technology_comfort: 'basic',
 employment_type: 'either',
 lift_experience: ['Transfer belt'],
 hourly_rate: 22,
 min_hours_per_week: 20,
 max_hours_per_week: 40,
 holiday_available: true,
 profile_completion_pct: 68,
 clients_served_count: 18,
 photo_url: null,
 },
 {
 first_name: 'David', last_name: 'Kim', preferred_name: 'David',
 job_title: 'Personal Support Worker',
 email: 'david.kim@demo.careified.com', phone: '(972) 555-0105',
 city: 'Frisco', state: 'TX', postal_code: '75035',
 gender: 'Male', status: 'approved',
 bio: 'PSW specializing in Parkinson\'s and ABI care. Background in occupational therapy assistance. Detail-oriented and reliable.',
 availability_status: 'available_now',
 years_experience: 4,
 aggregate_score: 4.5,
 rating_count: 6,
 services: ['Mobility assistance (walking, standing)','Transfer assistance (bed to chair)','Range of motion exercises','Medication reminders','Bathing and showering assistance','Fall prevention and monitoring'],
 specializations: ["Parkinson's disease","Acquired brain injury","Mobility and transfer","Behavioural support"],
 credentials: ['PSW','OT Assistant'],
 placement_types: ['Permanent placement','Regular part-time','Block booking'],
 languages: ['English','Mandarin','Cantonese'],
 willing_live_in: false,
 willing_overnight: false,
 has_vehicle: false,
 has_drivers_license: true,
 willing_to_transport: false,
 transit_accessible: true,
 travel_radius: 15,
 open_to_urgent: true,
 pet_tolerance: 'allergies',
 smoker_household: false,
 technology_comfort: 'comfortable',
 employment_type: 'employee',
 lift_experience: ['Hoyer / mechanical lift','Transfer belt'],
 hourly_rate: 23,
 min_hours_per_week: 16,
 max_hours_per_week: 32,
 holiday_available: true,
 profile_completion_pct: 70,
 clients_served_count: 9,
 photo_url: null,
 },
 {
 first_name: 'Grace', last_name: 'Mensah', preferred_name: 'Grace',
 job_title: 'Companion Caregiver',
 email: 'grace.mensah@demo.careified.com', phone: '(469) 555-0106',
 city: 'Celina', state: 'TX', postal_code: '75009',
 gender: 'Female', status: 'approved',
 bio: 'Compassionate companion caregiver with a gift for emotional support and social engagement. Clients and families consistently describe me as a ray of sunshine.',
 availability_status: 'available_now',
 years_experience: 3,
 aggregate_score: 4.4,
 rating_count: 5,
 services: ['Companionship and conversation','Social outings / recreation activities','Meal planning and preparation','Light housekeeping','Reading aloud','Games and activities','Video calling family assistance'],
 specializations: ['Mental health support',"Dementia / Alzheimer's",'Paediatric care'],
 credentials: ['PSW'],
 placement_types: ['Regular part-time','Casual / relief shifts','Respite care','Weekend specialist'],
 languages: ['English','Arabic'],
 willing_live_in: false,
 willing_overnight: false,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: true,
 travel_radius: 20,
 open_to_urgent: true,
 pet_tolerance: 'comfortable',
 smoker_household: false,
 technology_comfort: 'comfortable',
 employment_type: 'either',
 lift_experience: [],
 hourly_rate: 20,
 min_hours_per_week: 10,
 max_hours_per_week: 25,
 holiday_available: true,
 profile_completion_pct: 62,
 clients_served_count: 7,
 photo_url: null,
 },
 {
 first_name: 'Robert', last_name: 'Delacroix', preferred_name: 'Rob',
 job_title: 'LPN — Home Care Specialist',
 email: 'robert.delacroix@demo.careified.com', phone: '(214) 555-0107',
 city: 'Richardson', state: 'TX', postal_code: '75080',
 gender: 'Male', status: 'approved',
 bio: 'Licensed Practical Nurse with 9 years in home care. Expert in complex wound care and post-surgical recovery. Bilingual English/French.',
 availability_status: 'available_from',
 years_experience: 9,
 aggregate_score: 4.7,
 rating_count: 14,
 services: ['Wound dressing / post-surgical care','Medication administration (where permitted)','Vital signs monitoring (non-clinical)','Catheter care / ostomy care','Post-surgical / rehab support','Mobility assistance (walking, standing)'],
 specializations: ['Post-hospital recovery','Wound care','Medication management','Stroke recovery'],
 credentials: ['LPN / LVN'],
 placement_types: ['Permanent placement','Block booking'],
 languages: ['English','French'],
 willing_live_in: false,
 willing_overnight: false,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: false,
 travel_radius: 20,
 open_to_urgent: false,
 pet_tolerance: 'no_preference',
 smoker_household: false,
 technology_comfort: 'experienced',
 employment_type: 'contractor',
 lift_experience: ['Two-person assist'],
 hourly_rate: 38,
 min_hours_per_week: 20,
 max_hours_per_week: 40,
 holiday_available: false,
 profile_completion_pct: 75,
 clients_served_count: 31,
 photo_url: null,
 },
 {
 first_name: 'Aisha', last_name: 'Mohammed', preferred_name: 'Aisha',
 job_title: 'Dementia Care Specialist',
 email: 'aisha.mohammed@demo.careified.com', phone: '(972) 555-0108',
 city: 'McKinney', state: 'TX', postal_code: '75071',
 gender: 'Female', status: 'approved',
 bio: 'Specialist in dementia and memory care with Teepa Snow certification. 10 years experience. Known for de-escalation skills and family communication.',
 availability_status: 'available_now',
 years_experience: 10,
 aggregate_score: 4.9,
 rating_count: 22,
 services: ['Dementia care and support',"Alzheimer's care",'Memory care activities','Sundowning management','Wandering supervision','Behavioural redirection techniques','Companionship and conversation'],
 specializations: ["Dementia / Alzheimer's","Memory care","Behavioural support","Parkinson's disease"],
 credentials: ['PSW','CNA'],
 placement_types: ['Permanent placement','Live-in care','Overnight care'],
 languages: ['English','Arabic','French'],
 willing_live_in: true,
 willing_overnight: true,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: true,
 travel_radius: 35,
 open_to_urgent: false,
 pet_tolerance: 'comfortable',
 smoker_household: false,
 technology_comfort: 'comfortable',
 employment_type: 'either',
 lift_experience: ['Transfer belt','Hoyer / mechanical lift'],
 hourly_rate: 32,
 min_hours_per_week: 24,
 max_hours_per_week: 48,
 holiday_available: true,
 profile_completion_pct: 82,
 clients_served_count: 38,
 photo_url: null,
 },
 {
 first_name: 'Chen', last_name: 'Wei', preferred_name: 'Michael',
 job_title: 'Personal Support Worker',
 email: 'chen.wei@demo.careified.com', phone: '(469) 555-0109',
 city: 'Frisco', state: 'TX', postal_code: '75033',
 gender: 'Male', status: 'approved',
 bio: 'Reliable PSW serving Frisco/Plano area. Strong Mandarin and Cantonese speaker. Experienced with elderly Chinese clients and culturally specific care.',
 availability_status: 'available_now',
 years_experience: 5,
 aggregate_score: 4.3,
 rating_count: 7,
 services: ['Bathing and showering assistance','Meal planning and preparation','Medication reminders','Companionship and conversation','Transportation to appointments','Light housekeeping'],
 specializations: ["Dementia / Alzheimer's","Diabetes management","Mobility and transfer"],
 credentials: ['PSW'],
 placement_types: ['Permanent placement','Regular part-time','Live-in care'],
 languages: ['English','Mandarin','Cantonese'],
 willing_live_in: true,
 willing_overnight: false,
 has_vehicle: false,
 has_drivers_license: false,
 willing_to_transport: false,
 transit_accessible: true,
 travel_radius: 10,
 open_to_urgent: false,
 pet_tolerance: 'no_preference',
 smoker_household: false,
 technology_comfort: 'basic',
 employment_type: 'employee',
 lift_experience: [],
 hourly_rate: 21,
 min_hours_per_week: 20,
 max_hours_per_week: 40,
 holiday_available: false,
 profile_completion_pct: 65,
 clients_served_count: 11,
 photo_url: null,
 },
 {
 first_name: 'Patricia', last_name: 'OBrien', preferred_name: 'Pat',
 job_title: 'Palliative Care Specialist',
 email: 'patricia.obrien@demo.careified.com', phone: '(214) 555-0110',
 city: 'Prosper', state: 'TX', postal_code: '75078',
 gender: 'Female', status: 'approved',
 bio: 'Experienced palliative and hospice care worker with 14 years. Trained grief counsellor. Families describe me as calm, present and deeply compassionate.',
 availability_status: 'open_to_opportunities',
 years_experience: 14,
 aggregate_score: 5.0,
 rating_count: 27,
 services: ['Palliative / end-of-life care','Companionship and emotional support','Medication reminders','Personal hygiene support','Feeding assistance','Family communication support'],
 specializations: ['Palliative / end of life','Hospice support','Mental health support',"Dementia / Alzheimer's"],
 credentials: ['PSW','HHA'],
 placement_types: ['Permanent placement','Live-in care'],
 languages: ['English'],
 willing_live_in: true,
 willing_overnight: true,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: false,
 travel_radius: 30,
 open_to_urgent: false,
 pet_tolerance: 'comfortable',
 smoker_household: false,
 technology_comfort: 'basic',
 employment_type: 'either',
 lift_experience: ['Transfer belt'],
 hourly_rate: 30,
 min_hours_per_week: 24,
 max_hours_per_week: 48,
 holiday_available: true,
 profile_completion_pct: 79,
 clients_served_count: 52,
 photo_url: null,
 },
 {
 first_name: 'Marcus', last_name: 'Thompson', preferred_name: 'Marcus',
 job_title: 'Home Health Aide',
 email: 'marcus.thompson@demo.careified.com', phone: '(972) 555-0111',
 city: 'Garland', state: 'TX', postal_code: '75040',
 gender: 'Male', status: 'approved',
 bio: 'Energetic HHA with background in fitness and mobility support. Specializes in post-surgical recovery and helping clients regain independence.',
 availability_status: 'available_now',
 years_experience: 3,
 aggregate_score: 4.2,
 rating_count: 4,
 services: ['Mobility assistance (walking, standing)','Exercise assistance and encouragement','Post-surgical / rehab support','Range of motion exercises','Meal planning and preparation','Light housekeeping'],
 specializations: ['Post-hospital recovery','Mobility and transfer','Diabetes management'],
 credentials: ['HHA','CNA'],
 placement_types: ['Regular part-time','Casual / relief shifts','Weekend specialist'],
 languages: ['English','Spanish'],
 willing_live_in: false,
 willing_overnight: false,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: true,
 travel_radius: 25,
 open_to_urgent: true,
 pet_tolerance: 'comfortable',
 smoker_household: true,
 technology_comfort: 'comfortable',
 employment_type: 'contractor',
 lift_experience: ['Transfer belt','Two-person assist'],
 hourly_rate: 20,
 min_hours_per_week: 16,
 max_hours_per_week: 32,
 holiday_available: true,
 profile_completion_pct: 60,
 clients_served_count: 6,
 photo_url: null,
 },
 {
 first_name: 'Fatima', last_name: 'Al-Hassan', preferred_name: 'Fatima',
 job_title: 'Nursing Student — Practical Placement',
 email: 'fatima.alhassan@demo.careified.com', phone: '(469) 555-0112',
 city: 'Frisco', state: 'TX', postal_code: '75034',
 gender: 'Female', status: 'approved',
 bio: 'Third-year nursing student with supervised practical experience. Eager, fast learner, and genuinely passionate about geriatric care.',
 availability_status: 'available_now',
 years_experience: 1,
 aggregate_score: 4.1,
 rating_count: 3,
 services: ['Companionship and conversation','Medication reminders','Light housekeeping','Meal planning and preparation','Bathing and showering assistance'],
 specializations: ["Dementia / Alzheimer's",'Mental health support'],
 credentials: ['Nursing Student'],
 placement_types: ['Casual / relief shifts','Weekend specialist','Respite care'],
 languages: ['English','Arabic','French'],
 willing_live_in: false,
 willing_overnight: false,
 has_vehicle: false,
 has_drivers_license: true,
 willing_to_transport: false,
 transit_accessible: true,
 travel_radius: 10,
 open_to_urgent: true,
 pet_tolerance: 'comfortable',
 smoker_household: false,
 technology_comfort: 'experienced',
 employment_type: 'employee',
 lift_experience: [],
 hourly_rate: 17,
 min_hours_per_week: 8,
 max_hours_per_week: 20,
 holiday_available: true,
 profile_completion_pct: 52,
 clients_served_count: 4,
 photo_url: null,
 },
 {
 first_name: 'Helen', last_name: 'Kowalski', preferred_name: 'Helen',
 job_title: 'Senior PSW — Complex Care',
 email: 'helen.kowalski@demo.careified.com', phone: '(214) 555-0113',
 city: 'Wylie', state: 'TX', postal_code: '75098',
 gender: 'Female', status: 'approved',
 bio: 'Senior PSW with 16 years in complex and bariatric care. Trained in all major mechanical lift systems. Rock-solid reliability.',
 availability_status: 'available_now',
 years_experience: 16,
 aggregate_score: 4.8,
 rating_count: 31,
 services: ['Hoyer/mechanical lift operation','Transfer assistance (bed to chair)','Bathing and showering assistance','Continence care / incontinence support','Wound dressing / post-surgical care','Medication reminders'],
 specializations: ['Bariatric care','Mobility and transfer','Complex personal care','Post-hospital recovery'],
 credentials: ['PSW','HHA'],
 placement_types: ['Permanent placement','Live-in care','Block booking'],
 languages: ['English','Polish'],
 willing_live_in: true,
 willing_overnight: true,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: true,
 travel_radius: 30,
 open_to_urgent: true,
 pet_tolerance: 'no_preference',
 smoker_household: true,
 technology_comfort: 'basic',
 employment_type: 'either',
 lift_experience: ['Bariatric care','Hoyer / mechanical lift','Two-person assist','Transfer belt'],
 hourly_rate: 33,
 min_hours_per_week: 32,
 max_hours_per_week: 48,
 holiday_available: true,
 profile_completion_pct: 77,
 clients_served_count: 44,
 photo_url: null,
 },
 {
 first_name: 'Kevin', last_name: 'Nguyen', preferred_name: 'Kevin',
 job_title: 'Personal Support Worker',
 email: 'kevin.nguyen@demo.careified.com', phone: '(972) 555-0114',
 city: 'Little Elm', state: 'TX', postal_code: '75068',
 gender: 'Male', status: 'approved',
 bio: 'Bilingual PSW with 7 years in paediatric and special needs care. Patient, creative, and skilled at building trust with children and families.',
 availability_status: 'available_now',
 years_experience: 7,
 aggregate_score: 4.6,
 rating_count: 9,
 services: ['Companionship and conversation','Mobility assistance (walking, standing)','Meal planning and preparation','Behavioural redirection techniques','Social outings / recreation activities','Transportation to appointments'],
 specializations: ['Paediatric care','Acquired brain injury','Behavioural support','Mental health support'],
 credentials: ['PSW'],
 placement_types: ['Permanent placement','Regular part-time','Respite care'],
 languages: ['English','Vietnamese'],
 willing_live_in: false,
 willing_overnight: false,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: true,
 travel_radius: 20,
 open_to_urgent: false,
 pet_tolerance: 'comfortable',
 smoker_household: false,
 technology_comfort: 'comfortable',
 employment_type: 'employee',
 lift_experience: [],
 hourly_rate: 25,
 min_hours_per_week: 20,
 max_hours_per_week: 40,
 holiday_available: false,
 profile_completion_pct: 71,
 clients_served_count: 16,
 photo_url: null,
 },
 {
 first_name: 'Diane', last_name: 'Tremblay', preferred_name: 'Di',
 job_title: 'Live-in Care Specialist',
 email: 'diane.tremblay@demo.careified.com', phone: '(214) 555-0115',
 city: 'Prosper', state: 'TX', postal_code: '75078',
 gender: 'Female', status: 'approved',
 bio: 'Specialist in live-in care arrangements with 11 years experience. Discreet, professional, and highly adaptable. Clients consistently extend placements.',
 availability_status: 'available_now',
 years_experience: 11,
 aggregate_score: 4.7,
 rating_count: 16,
 services: ['Live-in care','24-hour care','Bathing and showering assistance','Meal planning and preparation','Medication reminders','Light housekeeping','Companionship and conversation','Transportation to appointments'],
 specializations: ["Dementia / Alzheimer's","Parkinson's disease",'Palliative / end of life','Complex personal care'],
 credentials: ['PSW','HHA'],
 placement_types: ['Permanent placement','Live-in care','Block booking'],
 languages: ['English','French'],
 willing_live_in: true,
 willing_overnight: true,
 has_vehicle: true,
 has_drivers_license: true,
 willing_to_transport: true,
 willing_client_vehicle: true,
 travel_radius: 50,
 open_to_urgent: false,
 pet_tolerance: 'comfortable',
 smoker_household: false,
 technology_comfort: 'comfortable',
 employment_type: 'either',
 lift_experience: ['Transfer belt','Hoyer / mechanical lift'],
 hourly_rate: 31,
 min_hours_per_week: 40,
 max_hours_per_week: 56,
 holiday_available: true,
 profile_completion_pct: 80,
 clients_served_count: 29,
 photo_url: null,
 },
];

async function seed() {
 const client = await pool.connect();
 let created = 0;
 let skipped = 0;

 try {
 for (const cg of caregivers) {
   const existing = await client.query(
     'SELECT id FROM caregivers WHERE email = $1',
     [cg.email]
   );

   if (existing.rows.length > 0) {
     console.log('⏭ Skipped (exists): ' + cg.first_name + ' ' + cg.last_name);
     skipped++;
     continue;
   }

   await client.query(`
     INSERT INTO caregivers (id, 
       first_name, last_name, preferred_name, job_title,
       email, phone, city, state, postal_code,
       gender, status, bio, availability_status,
       years_experience, aggregate_score, rating_count,
       services, specializations, credentials, placement_types,
       languages, willing_live_in, willing_overnight,
       has_vehicle, has_drivers_license, willing_to_transport,
       willing_client_vehicle, transit_accessible,
       travel_radius, open_to_urgent,
       pet_tolerance, smoker_household, technology_comfort,
       employment_type, lift_experience, hourly_rate,
       min_hours_per_week, max_hours_per_week, holiday_available,
       profile_completion_pct, clients_served_count
     ) VALUES (gen_random_uuid(),
       $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,
       $17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
       $31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41
     )
   `, [
     cg.first_name, cg.last_name, cg.preferred_name, cg.job_title,
     cg.email, cg.phone, cg.city, cg.state, cg.postal_code,
     cg.gender, cg.status, cg.bio, cg.availability_status,
     cg.years_experience, cg.aggregate_score, cg.rating_count,
     cg.services, cg.specializations, cg.credentials, cg.placement_types,
     cg.languages, cg.willing_live_in, cg.willing_overnight,
     cg.has_vehicle, cg.has_drivers_license, cg.willing_to_transport,
     cg.willing_client_vehicle || false, cg.transit_accessible || false,
     cg.travel_radius, cg.open_to_urgent,
     cg.pet_tolerance, cg.smoker_household, cg.technology_comfort,
     cg.employment_type, cg.lift_experience, cg.hourly_rate,
     cg.min_hours_per_week, cg.max_hours_per_week, cg.holiday_available,
     cg.profile_completion_pct, cg.clients_served_count,
   ]);

   console.log('✅ Created: ' + cg.first_name + ' ' + cg.last_name + ' — ' + cg.job_title + ' — ' + cg.aggregate_score + '★');
   created++;
 }

   console.log('\n🎉 Seed complete. ' + created + ' created, ' + skipped + ' skipped.');

   const summary = await client.query(`
     SELECT
       COUNT(*) as total,
       COUNT(*) FILTER (WHERE status = 'approved') as approved,
       AVG(aggregate_score)::numeric(3,2) as avg_score,
       AVG(profile_completion_pct)::numeric(4,1) as avg_completion
     FROM caregivers
     WHERE email LIKE '%demo.careified.com'
   `);
   console.log('\nDemo caregivers summary:');
   console.log(summary.rows[0]);

 } catch (err) {
   console.error('❌ Seed failed:', err.message);
 } finally {
   client.release();
   pool.end();
 }
}

seed();
